### ISSUE TITLE
Add Fathom to the list of accepted analytics tools

### ISSUE THREAD

**Issue by marcuslindblom** [Webperf-se/webperf_core#101]
Use this page to verify: [https://nimbleinitiatives.com/](https://nimbleinitiatives.com)

**Comment by 7h3Rabbit** [comment]
Fathom Analytics website: https://usefathom.com/

**Comment by 7h3Rabbit** [comment]
@marcuslindblom 
Not done yet and there are a lot of testing for other parts of the code but here are a preview:
![image](https://user-images.githubusercontent.com/62792609/152658291-8fc4e462-f856-4eae-8b1d-df938f0b6f50.png)

(please note that the test was running on GitHub servers so if you have any handling for GDPR it could be misrepresented in above screenshot)

**Comment by 7h3Rabbit** [comment]
Solved and closed
