### ISSUE TITLE
Work with texts and translation

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#106]
Some texts are a bit confusing depending in some contexts.

Example of texts found this far:
* “Fel statuskod. Fick 404 när 404 vore korrekt. ( 5.00 betyg )” - see https://webperf.se/site/sollentuna_se/
* All ratings in parenthesis, should they really include extra spaces? Can make surprising line breaks occur.

**Comment by 7h3Rabbit** [comment]
@marcusosterberg spaces where added for readability. it was very hard and slow to read before in the terminal.
