### ISSUE TITLE
Sv: Tidszon/kulturinställningar

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#11]
Lägga på en timme på testernas tidsstämpel eller ange tidzon i skriptet så det sköter sig självt?

**Comment by 7h3Rabbit** [comment]
@marcusosterberg Where do you mean?
is it here?

![image](https://user-images.githubusercontent.com/62792609/205460212-cbec8462-0638-4f6c-837a-a690dc09a4b7.png)
