### ISSUE TITLE
Documentation - Add funding section under Contribute

### ISSUE THREAD

**Issue by 7h3Rabbit** [Webperf-se/webperf_core#113]
This is not for our project, but I want to show the projects we depend on.
For example Yellow Lab Tools have a donate section.

Basically, if people want to donate they are very welcome to do so at the projects we are using in the background :)

**Comment by marcusosterberg** [comment]
There is also a way to donate to sitespeed.io

Dataskydd for Webbkoll?

**Comment by 7h3Rabbit** [comment]
@marcusosterberg I'm taking this issue from you because of inactivity ❤️
