### ISSUE TITLE
Identify CMS

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#114]
Have some info gathering such as which CMS is used.

**Comment by peterk** [comment]
Suggestion: https://whatcms.org/API

**Comment by 7h3Rabbit** [comment]
might have started something I shouldn't....

![image](https://user-images.githubusercontent.com/62792609/209873175-6e36a172-0820-4db7-bf2f-47be5ae6a3da.png)

**Comment by 7h3Rabbit** [comment]
Currently work with:
- WordPress
- Joomla
- Wix
- TYPO3
- Contao
- concrete (concrete5)
- EPiServer
- Drupal
- SiteCore
- Orchard

**Comment by marcusosterberg** [comment]
Not sure how frequent they are but have previously lost clients towards Umbraco as a CMS:
https://umbraco.com/

**Comment by 7h3Rabbit** [comment]
@marcusosterberg added

**Comment by 7h3Rabbit** [comment]
currrent progress when using the sample rule file included in repo.
Please note that a developer can add, change or remove rules for them self by placing their own rules in a file located here:  `data\software-rules.json`.
![image](https://user-images.githubusercontent.com/62792609/210274735-30efc213-7d2b-4c30-bf69-aba923d00773.png)

**Comment by 7h3Rabbit** [comment]
Last update for a while
![image](https://user-images.githubusercontent.com/62792609/210278881-dcc63c5e-46a1-425d-830c-27c071dbb891.png)

**Comment by 7h3Rabbit** [comment]
![image](https://user-images.githubusercontent.com/62792609/211060514-3e97ac5d-57c2-41bc-94f0-d171dd974d9b.png)

**Comment by 7h3Rabbit** [comment]
Solved and closed.
See https://github.com/Webperf-se/webperf_core/blob/main/docs/tests/software.md for more info
