### ISSUE TITLE
Unable to load disconnect-services.json in tracking_validator.py

### ISSUE THREAD

**Issue by jonasboman** [Webperf-se/webperf_core#117]
https://github.com/Webperf-se/webperf_core/blob/ff7741982dfcf617f73db3306561691f8b02939e/tests/tracking_validator.py#L108

Changing to opening file as utf-8 solved this.
`with open(filename, 'r', encoding='utf-8') as json_input_file:`

**Comment by 7h3Rabbit** [comment]
Thanks @jonasboman for your contribution :)
