### ISSUE TITLE
Check for tosdr.txt

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#120]
Implement the Term of Service classification in Webperf Core's privacy-test?
Used in the DuckDuckGo browser for instance.

More on the standard:
https://tosdr.org/txt

**Comment by 7h3Rabbit** [comment]
@marcusosterberg  Can you describe more? Why would it be good to test for this? any site that support it today?

**Comment by 7h3Rabbit** [comment]
Is there an RFC for this? or a draft for a RFC?

**Comment by 7h3Rabbit** [comment]
_IF_ we should add this I would recommend adding it to standard files.
Is it a standard file?
