### ISSUE TITLE
Set custom timeout for http_validator

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#121]
https://github.com/Webperf-se/webperf_core/blob/9ed002b276f01b4fd19dce3b5e95cb2aad59ed62/tests/http_validator.py#L356

Suggesting:
dns_record = dns.resolver.query(hostname, record_type, timeout = 30)

Perhaps to reuse some timeout value already set in the config file.

**Comment by marcusosterberg** [comment]
Tried the suggested code on my _really_ slow 4G connection but it still cannot do the test. Now it's complaining about *InsecureRequestWarning* instead.

Ideas?

**Comment by 7h3Rabbit** [comment]
@marcusosterberg can you please describe more about your problem?
maybe some screenshot of your test and expected results
