### ISSUE TITLE
Test Improvement  - Energy efficiency

### ISSUE THREAD

**Issue by 7h3Rabbit** [Webperf-se/webperf_core#138]
### Suggested improvements:
- Use actual data for Sweden regarding co2 consumption.
  - Can we differentiate co2 depending on response country?
- Can we adjust data/calculation from Energymyndigheten for Sweden?
- Add load time into calculation for energy use?

### Possible references:
- https://www.dataportal.se/
- https://www.nowtricity.com/country/sweden/
- https://www.iea.org/countries/sweden
- https://sweden.se/climate/sustainability/energy-use-in-sweden
- https://www.eea.europa.eu/data-and-maps/data/co2-intensity-of-electricity-generation

**Comment by cockroacher** [comment]
This was a good idea **BUT** there is no one right now willing to spend the time required doing research or paying cash for existing api/serviced/databases.
Closing issue
