### ISSUE TITLE
Move tests (checks) to separate files

### ISSUE THREAD

**Issue by flowertwig-org** [Webperf-se/webperf_core#14]
I want to move our tests (checks) to separate files in similar way that we have the "engines" working.

Benefit by doing this would be:
- easier to find and read specific test
- easier to know what test who have what dependency
- easier to add/remove tests (or change between versions)

**Comment by marcusosterberg** [comment]
Go ahead, sounds great!

**Comment by surffilip** [comment]
...so this one's done now right? @flowertwig-org

**Comment by flowertwig-org** [comment]
Solved and closed :)
