### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#16]
When webperf_core is in a versioned state, then keep a changelog file. Inspiration from:
https://keepachangelog.com/en/1.0.0/

**Comment by 7h3Rabbit** [comment]
@marcusosterberg Are we not doing this now?

https://github.com/Webperf-se/webperf_core/releases for example ?

**Comment by 7h3Rabbit** [comment]
Solved and done
