### ISSUE TITLE
Enable sitemap as input

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#17]
How about if webperf core can accept a sitemap to harvest URL:s to test? To complement CSV and SQL which is currently available.

I think you also need to specify number of URL:s to test since some sitemaps contain lots of URL:s.

**Comment by flowertwig-org** [comment]
@marcusosterberg  We could add sitemap url as input source for sites. Basically adding sitemap as read only engine. This would also allow you to create a database with every url in a sitemap for later testing. Should I implement it?

**Comment by flowertwig-org** [comment]
you can now use a sitemap.xml as source for your test, example:
`python3 default.py -t 9 -r -i https://webperf.se/sitemap-posts.xml`

Please note:
- This source is read only and can not store site-urls.
- url to sitemap has to end with '.xml' to work
- it currently takes all of them (no limitation)

checked in into 'features' branch

**Comment by flowertwig-org** [comment]
@marcusosterberg  & @puggan how would you like the command to be to limit number of sites/urls? (this would be for all the input engines ofcourse).
Would below be any good for you?
`--input-start <number>`
and 
`--input-end <number>`

**Comment by flowertwig-org** [comment]
`--input-skip <number>`
and
`--input-take <number>`
might be better. agree?

**Comment by flowertwig-org** [comment]
--input-skip and --input-take is implemented for all engines

**Comment by flowertwig-org** [comment]
solved in "features" branch, closing issue.
