### ISSUE TITLE
Software and Integrity: Detect Fathom and Plausible Analytics

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#193]
## Fathom
A [Fathom](https://usefathom.com/) sample is to be found on https://nimbleinitiatives.com/

The request syntax is:
> https://anl.nimbleinitiatives.com/?h=https%3A%2F%2Fnimbleinitiatives.com&p=%2F&r=https%3A%2F%2Fwww.google.com%2F&sid=XJRNEWFG&qs=%7B%7D&cid=67254428

**Comment by marcusosterberg** [comment]
On usefathom they request:
> https://quick-esteemed.usefathom.com/

Common is that they both have below code to start their JS:
```
window.fathom = function() {
    function trackPageview() {
        window.fathom.trackPageview()
    }
```

**Comment by marcusosterberg** [comment]
## Plausible 
[According to their documentation](https://plausible.io/docs/troubleshoot-integration#check-for-the-plausible-snippet-in-your-source-code), the way to find if a website is using Plausible Analytics is to look for this in the HEAD-tag:
> <script src="https://plausible.io/js/script.js" defer="defer" data-domain="plausible.io">

But the *data-domain* is going to be the same as the website we're looking at.

**Comment by marcusosterberg** [comment]
## Fathom examples
https://merch.ironmaiden.com
> <script src="https://cdn.usefathom.com/script.js" data-site="KFOTXSNV" defer></script>

vuejs.org
> <script src="https://cdn.usefathom.com/script.js" data-site="XNOLWPLB" data-spa="auto" defer=""></script>

https://www.sciencemuseum.org.uk/
> <script id="fathom" data-site="VDTZGSMQ" src="https://cdn.usefathom.com/script.js"></script>

https://www.insurancejournal.com/
> <script src="https://cdn.usefathom.com/script.js" data-site="CPGXVVIC" defer=""></script>

https://seedandspark.com/
> <script src="https://cdn.usefathom.com/script.js" data-site="OZBIAJAY" defer="" type="text/javascript"></script>

https://www.vagrantup.com/
> <script id="fathom-script" async="" data-site="KVKPBTGU" src="https://tarantula.hashicorp.com/script.js" data-included-domains="vagrantup.com,www.vagrantup.com"></script>

https://usefathom.com/
> <script src="https://quick-esteemed.usefathom.com/" data-site="BIABKBRK" defer=""></script>

## Hotjar (for heatmaps)
https://inside.com/
> https://static.hotjar.com/c/hotjar-2859169.js?sv=7
> https://script.hotjar.com/modules.f0ba8b655d2d90cf7a94.js

https://jobs.citizensbank.com/
> <script async="" src="https://static.hotjar.com/c/hotjar-2650353.js?sv=6"></script>
> <script async="" src="https://script.hotjar.com/modules.f0ba8b655d2d90cf7a94.js" charset="utf-8"></script>
```
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:2650353,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
```

https://tgifridays.com/
> <script type="text/javascript" async="" src="https://static.hotjar.com/c/hotjar-1318513.js?sv=7"></script>

https://bab.la/
> <script async="" src="https://static.hotjar.com/c/hotjar-1695067.js?sv=6"></script>
> <script async="" src="https://script.hotjar.com/modules.f0ba8b655d2d90cf7a94.js" charset="utf-8"></script>
```
<script type="text/javascript">
            var loadResources = true;
            var hotjarID = "1695067"; 

            function OptanonWrapper() { 
                if (loadResources && hotjarID) {
                    <!-- Hotjar Tracking Code for https://bab.la/ -->
                    (function(h,o,t,j,a,r){
                    h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
                    h._hjSettings={hjid:hotjarID,hjsv:6};
                    a=o.getElementsByTagName('head')[0];
                    r=o.createElement('script');r.async=1;
                    r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
                    a.appendChild(r);
                    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');

                    loadResources = false;
                }
            }
        </script>
```

https://birdeye.com/
> <script type="text/javascript" async="" src="https://static.hotjar.com/c/hotjar-601601.js?sv=7"></script>

https://www.template.net/
> <script async="" src="https://static.hotjar.com/c/hotjar-949989.js?sv=6"></script>
> <script async="" src="https://script.hotjar.com/modules.f0ba8b655d2d90cf7a94.js" charset="utf-8"></script>
> <script async="" src="https://static.hotjar.com/c/hotjar-949989.js?sv=6"></script>
```
<script>
              (function(h,o,t,j,a,r){ h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)}; h._hjSettings={hjid:949989,hjsv:6}; a=o.getElementsByTagName('head')[0]; r=o.createElement('script');r.async=1; r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv; a.appendChild(r); })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');</script>
```

https://brickseek.com/
> <script type="text/javascript" async="" src="https://static.hotjar.com/c/hotjar-1040092.js?sv=7"></script>

**Comment by marcusosterberg** [comment]
## Plausible examples
https://maps.metmuseum.org/?screenmode=base&floor=1#hash=17/40.779448/-73.963517/-61
> <script defer="defer" data-domain="maps.metmuseum.org" src="https://plausible.io/js/plausible.outbound-links.js"></script>

https://www.artspace.com/
> <script defer="" data-domain="artspace.com" src="https://plausible.io/js/plausible.js"></script>

https://nypd-surveillance.amnesty.org/
> <script defer="" data-domain="nypd-surveillance.amnesty.org" src="https://plausible.io/js/plausible.outbound-links.js"></script>

https://livesport.expressen.se/
> <script type="text/javascript" data-domain="livesport.expressen.se" async="" defer="" src="https://plausible.io/js/plausible.js"></script>

https://athemes.com/
> <script type="text/javascript" async="" defer="" data-domain="athemes.com" data-api="https://plausible.io/api/event" src="https://plausible.io/js/plausible.outbound-links.js?ver=1.2.6"></script>

https://www.macropoint.com/
> <script type="text/javascript" id="" src="https://plausible.io/js/plausible.js"></script>

https://mavin.io/
> <script async="" defer="" data-domain="mavin.io" src="https://plausible.io/js/script.hash.js"></script>

https://opendeur.annefrank.org/
> <script defer="" data-domain="opendeur.annefrank.org" src="https://plausible.io/js/script.js"></script>

https://momentumdash.com/
> <script defer="" data-domain="momentumdash.com" src="https://plausible.io/js/plausible.js"></script>

**Comment by marcusosterberg** [comment]
## Monsido (a Siteimprove competitor)
https://www.americansale.com/
> <script type="text/javascript" src="//cdn.monsido.com/page-assist/v2/mon-page-assist-loader.js"></script>
> <script type="text/javascript" src="//pagecorrect.monsido.com/v1/page-correct.js"></script>
> <script type="text/javascript" async="" src="https://app-script.monsido.com/v2/monsido-script.js"></script>
> <script type="text/javascript" src="https://monsido-consent.com/v1/mcm.js"></script>
```
<script type="text/javascript">
            window.MonsidoCookieOnLoad = function() {
                var cookiePreferencesEl = document.querySelector(".preview-monside-cookie-c");
                
                if (cookiePreferencesEl) {
                    cookiePreferencesEl.addEventListener("click", function(e) {
                        e.preventDefault();
                        window.monsidoConsentManager.showBanner("cookie-preferences");
                    });
                }
    
                var mcmEl = document.querySelector('mon-cb-main');
    
                if (mcmEl) {
                    mcmEl.classList.add('mcm-slide-up');
                }
            };
        </script>
```
 
https://www.auckland.ac.nz/en.html
> <script type="text/javascript" id="" src="https://app-script.monsido.com/v2/monsido-script.js"></script>
`<script type="text/javascript" id="">window._monsido=window._monsido||{token:"XZIYZpgmCXf6SOQI4W2B7A",statistics:{enabled:!0,documentTracking:{enabled:!0,documentCls:"monsido_download",documentIgnoreCls:"monsido_ignore_download",documentExt:["pdf","docx","xlsx","pptx"]}}};</script>`

https://easternflorida.edu/
> <script type="text/javascript" async="" src="https://app-script.monsido.com/v2/monsido-script.js"></script>

https://myboca.us/
> <script type="text/javascript" src="//cdn.monsido.com/page-assist/v2/mon-page-assist-loader.js"></script>
> <script type="text/javascript" src="//pagecorrect.monsido.com/v1/page-correct.js"></script>
> <script type="text/javascript" async="" src="https://app-script.monsido.com/v2/monsido-script.js"></script>

https://www.endlesspools.com/
> <script type="text/javascript" src="//pagecorrect.monsido.com/v1/page-correct.js"></script>
> <script type="text/javascript" async="" src="https://app-script.monsido.com/v2/monsido-script.js"></script>

https://michiganfirst.com/
> <script type="text/javascript" id="" src="https://app-script.monsido.com/v2/monsido-script.js"></script>
`<script type="text/javascript" id="">window._monsido=window._monsido||{token:"-RzSasd4W_lP17DV1UwhWA"};</script>`

**Comment by 7h3Rabbit** [comment]
@marcusosterberg Do you have an old version?
![image](https://user-images.githubusercontent.com/62792609/232585261-cdd72f8c-39b3-4930-8a72-d8ec4fbdae7d.png)

**Comment by 7h3Rabbit** [comment]
Solved and closed
