### ISSUE TITLE
Webbkoll: CSP rating based on share of failed tests

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#202]
Currently, if Webbkoll's heading for CSP has a red x in it the website get a 1.0 rating. Perhaps we should count the share of failed against the successful checks and giva a more granular rating?

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/1117123/233075835-26123894-bc64-4cf5-bc32-2438dc806d6f.png">

**Comment by 7h3Rabbit** [comment]
This ONLY happens when Webbkoll determine the severity of the error is so big that everything on that header should fail.
In this example allowing `unsafe-eval`, basically nullifying the CSP for both script and style.

**Comment by 7h3Rabbit** [comment]
This as been discussed in Slack and community has decided to not change this for Webbkoll.
BUT, there we now have a new CSP section in test 21 that works similar to this.
Closing issue.
