### ISSUE TITLE
Tracking to detect Piano Analytics

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#211]
Research:

- https://trends.builtwith.com/websitelist/Piano/Sweden
- https://www.thelocal.fr/
- https://api-esp.piano.io/publisher/fusion/lucid/data/517?email=&visitor=&stored_visitor=&pnespid=

**Comment by 7h3Rabbit** [comment]
@marcusosterberg Please view issue #216 as I have changed how rules are added.
