### ISSUE TITLE
Bug - Testing URL's with questionmarks do not always work out

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#220]
Seem to be at least the Sitespeed-based tests and Webbkoll.
Example of URL not making it:
`https://webperf.se/events/?typ=Intran%C3%A4t`

**Comment by 7h3Rabbit** [comment]
Sitespeed io based tests had problem with urls that had querystring.
webbkollen based tests have url encoding problems

**Comment by 7h3Rabbit** [comment]
Solved and closed
