### ISSUE TITLE
Webbkoll check cannot manage Nordic characters in headers

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#233]
Example:
https://webbkoll.dataskydd.net/sv/results?url=http%3A%2F%2Fwebperf.app

Header: `Osäker: HTTPS används ej som standard`
Picked up by Webperf Core as: `- Osker: HTTPS anvnds ej som standard är dåligt. ( 1.00 betyg )`

**Comment by 7h3Rabbit** [comment]
Looks solved to me but awaits confirmation from @marcusosterberg before merging

**Comment by marcusosterberg** [comment]
Works like a charm. 
> python default.py -r -L sv  -t 20 -u https://webperf.cloud

Merging
