### ISSUE TITLE
Explain the energy section more

### ISSUE THREAD

**Issue by mgifford** [Webperf-se/webperf_core#242]
I'm not sure what this is doing:

https://github.com/Webperf-se/webperf_core/blob/main/docs/tests/energy-efficiency.md

Just CO2.js? Something similar?

**Comment by 7h3Rabbit** [comment]
> We are doing this by taking the weight of the url in KiB and calculating a value from this.

What are you missing? What can be improved?

You can look at the code here: [tests/energy_efficiency.py](https://github.com/Webperf-se/webperf_core/blob/main/tests/energy_efficiency.py)

Calculating co2 from KiB originally comes from: [wholegrain/carbon-api-2-0](https://gitlab.com/wholegrain/carbon-api-2-0).

We take the value calculated for the page tested and compare it with values from other sites measured at webperf.se.

For example on [webperf.se/site/eskilstuna_se](https://webperf.se/site/eskilstuna_se/#22)
you can see that compared to over 2000+ sites measured by webperf.se in dec 2022 it was considered cleaner then 95% of other sites.
Yellow color: co2 in gram.
Blue color: how site is compared to others and when the comparison data was last calculated.
Orange color: the kb of webpage that is converted to co2.

![image](https://github.com/Webperf-se/webperf_core/assets/62792609/c14d4993-0bd6-44eb-a684-ea149fa984a9)

we have for a long time wanted to improve this test by for example using average energy creation type of electricity in the countries the resources are coming from but have found a up to date and reliable source yet.

**Comment by 7h3Rabbit** [comment]
closing issue as @mgifford have not responded if it helped or if he had more questions after a week.
