### ISSUE TITLE
Path is not included in 404 test

### ISSUE THREAD

**Issue by perragnarl** [Webperf-se/webperf_core#258]
When building the url for which to trigger the 404 page the path of the original URL is excluded.

F.e. https://www.url.com/path becomes https://www.url.com/173e1/finns-det-en-sida/pa-den-har-adressen/testanrop/

Not sure if this is deliberately excluded for some reason?

**Comment by marcusosterberg** [comment]
It's because Webperf Core's origin of focusing on the domain and/or start page. 

I guess you have some "virtual folder" application of sorts? 

I raise no objections on a change where the test keeps the path.

**Comment by 7h3Rabbit** [comment]
solved and closed, thanks for suggestion @perragnarl
