### ISSUE TITLE
Syntax error in models.py

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#276]
Line 16 results in:
`SyntaxError: f-string: unmatched '['`
https://github.com/Webperf-se/webperf_core/blob/c41d8953267fc1df1fab323c8b4cdf83280fa5a6/models.py#L16C9-L16C88

Should be wrapped by double quotes like this:
`return f"DefaultInfo(name={self.info['name']}, version={self.info['version']})"`

**Comment by 7h3Rabbit** [comment]
@marcusosterberg should fix only solve syntax or should it also make it printable?
it doesn't seem the DefaultInfo object is printable still.
