### ISSUE TITLE
Sitespeed based tests have issues with .html file extensions

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#284]
For instance, if you test CSS for https://www.bastad.se/om-bastad.se/om-kakor.html and it's already in the cache the test fails.

**Comment by cockroacher** [comment]
@marcusosterberg Hey there, I’m totally up for trying to fix this bug as a step in trying to learn more about how webperf_core works. But it was super unclear on https://github.com/Webperf-se/webperf_core/blob/main/docs/CONTRIBUTING.md about how and if you guys wanted support with bug fixes. What should and shouldn’t I do? Are there any lint files/settings I should use?

**Comment by marcusosterberg** [comment]
@cockroacher hi!
Everyone is welcome to contribute with whatever.

I think @7h3Rabbit is better fit to explain how to help out. Personally more involved in translations and minor changes nowadays.

**Comment by cockroacher** [comment]
@marcusosterberg  I’m not allowed to assign myself to this issue, can you give me the access?

**Comment by cockroacher** [comment]
It looks like the error you’re getting is due to https://github.com/sitespeedio/browsertime/issues/1487. I’ve come up with a solution that’s more independent of the file structure than the previous solution. Let me know what you think.
A solution is coming soon.

**Comment by cockroacher** [comment]
https://github.com/Webperf-se/webperf_core/pull/287

**Comment by 7h3Rabbit** [comment]
Welcome! :)
All help is welcomed.
To be honest we havn't been enough people contributing to feel a need for contribution text, but maybe we should.
If you have any idea/suggestion what should be there, please tell us or create a PR with it :)

Your PR, looks good, I will approve and merge it. great work

**Comment by 7h3Rabbit** [comment]
solved and closed
