### ISSUE TITLE
Need for a more Comprehensive CONTRIBUTING.md

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#288]
Hello,

I've recently come across this project. I find it really interesting and I'd love to contribute. However, I noticed that there isn't a detailed `CONTRIBUTING.md` file in the repository.

Having a well-structured `CONTRIBUTING.md` can be really beneficial for new contributors like me. It can provide clear guidelines on how to get started, the process for submitting pull requests, the project's code of conduct, and any other expectations for contributors.

This would not only make it easier for newcomers to contribute, but it could also help maintain a consistent code style and project structure, making the project more robust and easier to maintain in the long run.

I believe that adding a comprehensive `CONTRIBUTING.md` could really enhance the contributor experience and the overall quality of the project. To help with this, I am currently working on a draft for a `CONTRIBUTING.md` and will be submitting a PR soon with my suggestions.

Looking forward to hearing your thoughts on this.

**Comment by 7h3Rabbit** [comment]
@cockroacher Looks good, nice that you included `failures.log`.
Solved and closed
