### ISSUE TITLE
PyLint for Improved Code Quality - verify_result.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#292]
### ************* Module verify_result
.github/workflows/verify_result.py:137:0: C0301: Line too long (113/100) (line-too-long)
.github/workflows/verify_result.py:143:0: C0301: Line too long (137/100) (line-too-long)
.github/workflows/verify_result.py:172:0: C0301: Line too long (107/100) (line-too-long)
.github/workflows/verify_result.py:309:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
.github/workflows/verify_result.py:315:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
.github/workflows/verify_result.py:337:0: C0301: Line too long (106/100) (line-too-long)
.github/workflows/verify_result.py:343:0: C0301: Line too long ([12](https://github.com/cockroacher/webperf_core/actions/runs/8343608393/job/22834150313#step:5:13)1/100) (line-too-long)
.github/workflows/verify_result.py:352:0: C0301: Line too long (123/100) (line-too-long)
.github/workflows/verify_result.py:369:0: C0301: Line too long (178/100) (line-too-long)
.github/workflows/verify_result.py:395:0: C0301: Line too long ([13](https://github.com/cockroacher/webperf_core/actions/runs/8343608393/job/22834150313#step:5:14)0/100) (line-too-long)
.github/workflows/verify_result.py:400:0: C0301: Line too long (195/100) (line-too-long)
.github/workflows/verify_result.py:432:0: C0301: Line too long (137/100) (line-too-long)
.github/workflows/verify_result.py:448:0: C0301: Line too long (108/100) (line-too-long)
.github/workflows/verify_result.py:472:0: C0301: Line too long (105/100) (line-too-long)
.github/workflows/verify_result.py:483:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
.github/workflows/verify_result.py:495:0: C0301: Line too long (101/100) (line-too-long)
.github/workflows/verify_result.py:1:0: C01[14](https://github.com/cockroacher/webperf_core/actions/runs/8343608393/job/22834150313#step:5:15): Missing module docstring (missing-module-docstring)
.github/workflows/verify_result.py:11:0: W0404: Reimport 'sys' (imported line 6) (reimported)
.github/workflows/verify_result.py:12:0: W0404: Reimport 'getopt' (imported line 7) (reimported)
.github/workflows/verify_result.py:[15](https://github.com/cockroacher/webperf_core/actions/runs/8343608393/job/22834150313#step:5:16):0: E0401: Unable to import 'requests' (import-error)
.github/workflows/verify_result.py:18:0: C01[16](https://github.com/cockroacher/webperf_core/actions/runs/8343608393/job/22834150313#step:5:17): Missing function or method docstring (missing-function-docstring)
.github/workflows/verify_result.py:18:0: R0914: Too many local variables (16/15) (too-many-locals)
.github/workflows/verify_result.py:35:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
.github/workflows/verify_result.py:46:33: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
.github/workflows/verify_result.py:47:19: R[17](https://github.com/cockroacher/webperf_core/actions/runs/8343608393/job/22834150313#step:5:18)14: Consider merging these comparisons with 'in' by using 'value in ('True', 'False', 'None')'. Use a set instead if elements are hashable. (consider-using-in)
.github/workflows/verify_result.py:48:38: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
.github/workflows/verify_result.py:50:38: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
.github/workflows/verify_result.py:57:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
.github/workflows/verify_result.py:42:16: W0612: Unused variable 'pair' (unused-variable)
.github/workflows/verify_result.py:66:0: C0116: Missing function or method docstring (missing-function-docstring)
.github/workflows/verify_result.py:67:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
.github/workflows/verify_result.py:68:15: E1101: Module 'json' has no 'load' member (no-member)
.github/workflows/verify_result.py:73:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
.github/workflows/verify_result.py:74:8: E1101: Module 'json' has no 'dump' member (no-member)
.github/workflows/verify_result.py:77:0: C0116: Missing function or method docstring (missing-function-docstring)
.github/workflows/verify_result.py:79:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
.github/workflows/verify_result.py:85:0: C0116: Missing function or method docstring (missing-function-docstring)
.github/workflows/verify_result.py:88:16: R1734: Consider using [] instead of list() (use-list-literal)
.github/workflows/verify_result.py:297:0: R0912: Too many branches (15/12) (too-many-branches)
.github/workflows/verify_result.py:333:34: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
.github/workflows/verify_result.py:335:32: W0612: Unused variable 'error' (unused-variable)
.github/workflows/verify_result.py:336:24: W0612: Unused variable 'result' (unused-variable)
.github/workflows/verify_result.py:363:0: C0103: Function name "httpRequestGetContent" doesn't conform to snake_case naming style (invalid-name)
.github/workflows/verify_result.py:398:4: W0702: No exception type(s) specified (bare-except)
.github/workflows/verify_result.py:379:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
.github/workflows/verify_result.py:380:8: W0107: Unnecessary pass statement (unnecessary-pass)
.github/workflows/verify_result.py:382:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
.github/workflows/verify_result.py:386:[18](https://github.com/cockroacher/webperf_core/actions/runs/8343608393/job/22834150313#step:5:19): C0[20](https://github.com/cockroacher/webperf_core/actions/runs/8343608393/job/22834150313#step:5:21)9: Formatting a regular string which could be an f-string (consider-using-f-string)
.github/workflows/verify_result.py:388:8: W0107: Unnecessary pass statement (unnecessary-pass)
.github/workflows/verify_result.py:390:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
.github/workflows/verify_result.py:395:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
.github/workflows/verify_result.py:397:8: W0107: Unnecessary pass statement (unnecessary-pass)
.github/workflows/verify_result.py:400:12: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
.github/workflows/verify_result.py:401:8: W0107: Unnecessary pass statement (unnecessary-pass)
.github/workflows/verify_result.py:404:0: C0116: Missing function or method docstring (missing-function-docstring)
.github/workflows/verify_result.py:412:0: C0116: Missing function or method docstring (missing-function-docstring)
.github/workflows/verify_result.py:413:4: W06[21](https://github.com/cockroacher/webperf_core/actions/runs/8343608393/job/22834150313#step:5:22): Redefining name 'sys' from outer scope (line 6) (redefined-outer-name)
.github/workflows/verify_result.py:425:12: W06[22](https://github.com/cockroacher/webperf_core/actions/runs/8343608393/job/22834150313#step:5:23): Redefining built-in 'dir' (redefined-builtin)
.github/workflows/verify_result.py:413:4: W0404: Reimport 'sys' (imported line 6) (reimported)
.github/workflows/verify_result.py:413:4: C0415: Import outside toplevel (sys) (import-outside-toplevel)
.github/workflows/verify_result.py:422:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
.github/workflows/verify_result.py:422:11: C0121: Comparison 'msgfmt_path != None' should be 'msgfmt_path is not None' (singleton-comparison)
.github/workflows/verify_result.py:438:0: C0116: Missing function or method docstring (missing-function-docstring)
.github/workflows/verify_result.py:438:22: W0622: Redefining built-in 'dir' (redefined-builtin)
.github/workflows/verify_result.py:453:11: W0718: Catching too general exception Exception (broad-exception-caught)
.github/workflows/verify_result.py:442:8: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
.github/workflows/verify_result.py:445:0: W1404: Implicit string concatenation found in call (implicit-str-concat)
.github/workflows/verify_result.py:483:8: C2801: Unnecessarily calls dunder method __len__. Use len built-in function. (unnecessary-dunder-call)
.github/workflows/verify_result.py:488:8: R17[23](https://github.com/cockroacher/webperf_core/actions/runs/8343608393/job/22834150313#step:5:24): Unnecessary "elif" after "break", remove the leading "el" from "elif" (no-else-break)
.github/workflows/verify_result.py:491:12: W0101: Unreachable code (unreachable)
.github/workflows/verify_result.py:458:0: R0912: Too many branches (14/12) (too-many-branches)
.github/workflows/verify_result.py:477:14: W0612: Unused variable 'args' (unused-variable)
.github/workflows/verify_result.py:520:0: W0105: String statement has no effect (pointless-string-statement)
.github/workflows/verify_result.py:11:0: C0[41](https://github.com/cockroacher/webperf_core/actions/runs/8343608393/job/22834150313#step:5:42)2: Imports from package sys are not grouped (ungrouped-imports)
.github/workflows/verify_result.py:12:0: C0412: Imports from package getopt are not grouped (ungrouped-imports)

**Comment by 7h3Rabbit** [comment]
@cockroacher 
Great work! Looks really good 🦾 

Following seem to still be an issue or is the test wrong?
************* Module verify_result
.github/workflows/verify_result.py:1:0: C0114: Missing module docstring (missing-module-docstring)
.github/workflows/verify_result.py:64:19: R1714: Consider merging these comparisons with 'in' by using 'value in ('True', 'False', 'None')'. Use a set instead if elements are hashable. (consider-using-in)
.github/workflows/verify_result.py:101:15: E1101: Module 'json' has no 'load' member (no-member)
.github/workflows/verify_result.py:107:8: E1101: Module 'json' has no 'dump' member (no-member)
.github/workflows/verify_result.py:154:16: R1734: Consider using [] instead of list() (use-list-literal)
.github/workflows/verify_result.py:198:0: R0914: Too many local variables (16/15) (too-many-locals)
.github/workflows/verify_result.py:239:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
.github/workflows/verify_result.py:233:4: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
.github/workflows/verify_result.py:198:0: R0911: Too many return statements (7/6) (too-many-return-statements)
.github/workflows/verify_result.py:198:0: R09[12](https://github.com/Webperf-se/webperf_core/actions/runs/8357722694/job/22877479590#step:5:13): Too many branches (18/12) (too-many-branches)
.github/workflows/verify_result.py:198:0: R09[15](https://github.com/Webperf-se/webperf_core/actions/runs/8357722694/job/22877479590#step:5:16): Too many statements (59/50) (too-many-statements)
.github/workflows/verify_result.py:482:26: R1734: Consider using [] instead of list() (use-list-literal)
.github/workflows/verify_result.py:488:4: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
.github/workflows/verify_result.py:455:0: R0912: Too many branches (15/12) (too-many-branches)
.github/workflows/verify_result.py:5[16](https://github.com/Webperf-se/webperf_core/actions/runs/8357722694/job/22877479590#step:5:17):34: R[17](https://github.com/Webperf-se/webperf_core/actions/runs/8357722694/job/22877479590#step:5:18)32: Consider using 'with' for resource-allocating operations (consider-using-with)
.github/workflows/verify_result.py:689:8: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
