### ISSUE TITLE
PyLint for Improved Code Quality - SAMPLE-config.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#293]
*************** Module SAMPLE-config
SAMPLE-config.py:11:0: C0301: Line too long ([156] (line-too-long)
SAMPLE-config.py:44:0: C0301: Line too long (128/100) (line-too-long)
SAMPLE-config.py:60:0: C0301: Line too long (122/100) (line-too-long)
SAMPLE-config.py:1:0: C0103: Module name "SAMPLE-config" doesn't conform to snake_case naming style (invalid-name)
SAMPLE-config.py:11:0: C0103: Constant name "useragent" doesn't conform to UPPER_CASE naming style (invalid-name)
SAMPLE-config.py:14:0: C0103: Constant name "googlePageSpeedApiKey" doesn't conform to UPPER_CASE naming style (invalid-name)
SAMPLE-config.py:16:0: C0103: Constant name "http_request_timeout" doesn't conform to UPPER_CASE naming style (invalid-name)
SAMPLE-config.py:19:0: C0103: Constant name "webbkoll_sleep" doesn't conform to UPPER_CASE naming style (invalid-name)
SAMPLE-config.py:22:0: C0103: Constant name "css_review_group_errors" doesn't conform to UPPER_CASE naming style (invalid-name)
SAMPLE-config.py:25:0: C0103: Constant name "review_show_improvements_only" doesn't conform to UPPER_CASE naming style (invalid-name)
SAMPLE-config.py:28:0: C0103: Constant name "ylt_use_api" doesn't conform to UPPER_CASE naming style (invalid-name)
SAMPLE-config.py:31:0: C0103: Constant name "lighthouse_use_api" doesn't conform to UPPER_CASE naming style (invalid-name)
SAMPLE-config.py:34:0: C0103: Constant name "sitespeed_use_docker" doesn't conform to UPPER_CASE naming style (invalid-name)
SAMPLE-config.py:37:0: C0103: Constant name "sitespeed_timeout" doesn't conform to UPPER_CASE naming style (invalid-name)
SAMPLE-config.py:40:0: C0103: Constant name "sitespeed_iterations" doesn't conform to UPPER_CASE naming style (invalid-name)
SAMPLE-config.py:45:0: C0103: Constant name "locales" doesn't conform to UPPER_CASE naming style (invalid-name)
SAMPLE-config.py:48:0: C0103: Constant name "cache_when_possible" doesn't conform to UPPER_CASE naming style (invalid-name)
SAMPLE-config.py:55:0: C0103: Constant name "github_api_key" doesn't conform to UPPER_CASE naming style (invalid-name)
SAMPLE-config.py:58:0: C0103: Constant name "use_detailed_report" doesn't conform to UPPER_CASE naming style (invalid-name)
SAMPLE-config.py:61:0: C0103: Constant name "csp_only" doesn't conform to UPPER_CASE naming style (invalid-name)
SAMPLE-config.py:64:0: C0103: Constant name "dns_server" doesn't conform to UPPER_CASE naming style (invalid-name)
SAMPLE-config.py:67:0: C0103: Constant name "software_use_stealth" doesn't conform to UPPER_CASE naming style (invalid-name)
SAMPLE-config.py:71:0: C0103: Constant name "software_github_adadvisory_database_path" doesn't conform to UPPER_CASE naming style (invalid-name)
SAMPLE-config.py:74:0: C0103: Constant name "software_browser" doesn't conform to UPPER_CASE naming style (invalid-name)

**Comment by 7h3Rabbit** [comment]
Solved and closed.
@cockroacher great work!
