### ISSUE TITLE
PyLint for Improved Code Quality - carbon-rating.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#294]
************* Module carbon-rating
carbon-rating.py:43:0: C0301: Line too long (107/100) (line-too-long)
carbon-rating.py:44:0: C0301: Line too long ([170])/100) (line-too-long)
carbon-rating.py:70:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
carbon-rating.py:83:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
carbon-rating.py:85:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
carbon-rating.py:90:0: C0325: Unnecessary parens after 'elif' keyword (superfluous-parens)
carbon-rating.py:92:0: C0325: Unnecessary parens after 'elif' keyword (superfluous-parens)
carbon-rating.py:132:0: C0325: Unnecessary parens after 'while' keyword (superfluous-parens)
carbon-rating.py:148:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
carbon-rating.py:44:93: W1401: Anomalous backslash in string: '\c'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
carbon-rating.py:44:130: W1401: Anomalous backslash in string: '\e'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
carbon-rating.py:1:0: C0114: Missing module docstring (missing-module-docstring)
carbon-rating.py:1:0: C0103: Module name "carbon-rating" doesn't conform to snake_case naming style (invalid-name)
carbon-rating.py:7:0: W0404: Reimport 'datetime' (imported line 4) (reimported)
carbon-rating.py:9:0: W0404: Reimport 'gettext' (imported line 5) (reimported)
carbon-rating.py:16:0: C0116: Missing function or method docstring (missing-function-docstring)
carbon-rating.py:16:0: C0103: Function name "getPercentile" doesn't conform to snake_case naming style (invalid-name)
carbon-rating.py:19:4: C0103: Variable name "fractionPart" doesn't conform to snake_case naming style (invalid-name)
carbon-rating.py:20:4: C0103: Variable name "intPart" doesn't conform to snake_case naming style (invalid-name)
carbon-rating.py:32:0: C0116: Missing function or method docstring (missing-function-docstring)
carbon-rating.py:33:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
carbon-rating.py:37:0: R0914: Too many local variables (27/15) (too-many-locals)
carbon-rating.py:54:4: C0103: Variable name "langCode" doesn't conform to snake_case naming style (invalid-name)
carbon-rating.py:70:8: C2801: Unnecessarily calls dunder method __len__. Use len built-in function. (unnecessary-dunder-call)
carbon-rating.py:89:16: C0415: Import outside toplevel (engines.sqlite.read_sites, engines.sqlite.add_site, engines.sqlite.delete_site) (import-outside-toplevel)
carbon-rating.py:91:16: C0415: Import outside toplevel (engines.csv.read_sites, engines.csv.add_site, engines.csv.delete_site) (import-outside-toplevel)
carbon-rating.py:93:16: C0415: Import outside toplevel (engines.sitemap.read_sites, engines.sitemap.add_site, engines.sitemap.delete_site) (import-outside-toplevel)
carbon-rating.py:95:16: C0415: Import outside toplevel (engines.json.read_tests, engines.json.read_sites, engines.json.add_site, engines.json.delete_site) (import-outside-toplevel)
carbon-rating.py:96:12: W0107: Unnecessary pass statement (unnecessary-pass)
carbon-rating.py:99:12: W0107: Unnecessary pass statement (unnecessary-pass)
carbon-rating.py:103:11: R[173](https://github.com/cockroacher/webperf_core/actions/runs/8343608393/job/22834150313#step:5:174)4: Consider using [] instead of list() (use-list-literal)
carbon-rating.py:111:15: E1101: Module 'json' has no 'loads' member (no-member)
carbon-rating.py:118:21: C0[209](https://github.com/cockroacher/webperf_core/actions/runs/8343608393/job/22834150313#step:5:210): Formatting a regular string which could be an f-string (consider-using-f-string)
carbon-rating.py:121:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
carbon-rating.py:129:16: R1734: Consider using [] instead of list() (use-list-literal)
carbon-rating.py:138:34: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
carbon-rating.py:140:30: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
carbon-rating.py:142:30: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
carbon-rating.py:37:0: R0912: Too many branches (20/12) (too-many-branches)
carbon-rating.py:37:0: R0915: Too many statements (73/50) (too-many-statements)
carbon-rating.py:64:14: W0612: Unused variable 'args' (unused-variable)
carbon-rating.py:89:16: W0611: Unused read_sites imported from engines.sqlite (unused-import)
carbon-rating.py:89:16: W0611: Unused add_site imported from engines.sqlite (unused-import)
carbon-rating.py:89:16: W0611: Unused delete_site imported from engines.sqlite (unused-import)
carbon-rating.py:152:0: W0105: String statement has no effect (pointless-string-statement)
carbon-rating.py:7:0: C0412: Imports from package datetime are not grouped (ungrouped-imports)
carbon-rating.py:9:0: C0412: Imports from package gettext are not grouped (ungrouped-imports)

**Comment by 7h3Rabbit** [comment]
carbon-rating.py:41:0: C0301: Line too long (107/100) (line-too-long)
carbon-rating.py:42:0: C0301: Line too long (170/100) (line-too-long)
carbon-rating.py:68:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
carbon-rating.py:114:0: C0325: Unnecessary parens after 'while' keyword (superfluous-parens)
carbon-rating.py:130:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
carbon-rating.py:42:93: W1401: Anomalous backslash in string: '\c'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
carbon-rating.py:42:130: W1401: Anomalous backslash in string: '\e'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
carbon-rating.py:1:0: C0103: Module name "carbon-rating" doesn't conform to snake_case naming style (invalid-name)
carbon-rating.py:7:0: W0404: Reimport 'gettext' (imported line 4) (reimported)
carbon-rating.py:14:0: C0116: Missing function or method docstring (missing-function-docstring)
carbon-rating.py:14:0: C0103: Function name "getPercentile" doesn't conform to snake_case naming style (invalid-name)
carbon-rating.py:17:4: C0103: Variable name "fractionPart" doesn't conform to snake_case naming style (invalid-name)
carbon-rating.py:18:4: C0103: Variable name "intPart" doesn't conform to snake_case naming style (invalid-name)
carbon-rating.py:30:0: C0116: Missing function or method docstring (missing-function-docstring)
carbon-rating.py:31:9: W[15](https://github.com/Webperf-se/webperf_core/actions/runs/8588845582/job/23534216988#step:6:16)14: Using open without explicitly specifying an encoding (unspecified-encoding)
carbon-rating.py:35:0: R0914: Too many local variables (22/15) (too-many-locals)
carbon-rating.py:52:4: C0103: Variable name "langCode" doesn't conform to snake_case naming style (invalid-name)
carbon-rating.py:68:8: C2801: Unnecessarily calls dunder method __len__. Use len built-in function. (unnecessary-dunder-call)
carbon-rating.py:78:12: C0415: Import outside toplevel (engines.json_engine.read_tests) (import-outside-toplevel)
carbon-rating.py:81:12: W0107: Unnecessary pass statement (unnecessary-pass)
carbon-rating.py:100:21: C0[20](https://github.com/Webperf-se/webperf_core/actions/runs/8588845582/job/23534216988#step:6:21)9: Formatting a regular string which could be an f-string (consider-using-f-string)
carbon-rating.py:103:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
carbon-rating.py:120:34: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
carbon-rating.py:1[22](https://github.com/Webperf-se/webperf_core/actions/runs/8588845582/job/23534216988#step:6:23):30: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
carbon-rating.py:124:30: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
carbon-rating.py:35:0: R0912: Too many branches (14/12) (too-many-branches)
carbon-rating.py:35:0: R0915: Too many statements (59/50) (too-many-statements)
carbon-rating.py:62:14: W0612: Unused variable 'args' (unused-variable)
carbon-rating.py:134:0: W0105: String statement has no effect (pointless-string-statement)
carbon-rating.py:7:0: C0412: Imports from package gettext are not grouped (ungrouped-imports)
