### ISSUE TITLE
PyLint for Improved Code Quality - engines/csv.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#296]
************* Module csv
engines/csv.py:33:0: C0[325]: Unnecessary parens after 'if' keyword (superfluous-parens)
engines/csv.py:1:0: C0114: Missing module docstring (missing-module-docstring)
engines/csv.py:4:0: W0406: Module import itself (import-self)
engines/csv.py:7:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/csv.py:7:33: C0103: Argument name "siteTests" doesn't conform to snake_case naming style (invalid-name)
engines/csv.py:8:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
engines/csv.py:9:17: E1101: Module 'csv' has no 'DictWriter' member (no-member)
engines/csv.py:7:44: W0613: Unused argument 'sites' (unused-argument)
engines/csv.py:15:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/csv.py:18:4: W0622: Redefining built-in 'id' (redefined-builtin)
engines/csv.py:22:10: E0602: Undefined variable '_' (undefined-variable)
engines/csv.py:27:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/csv.py:29:4: C0103: Variable name "tmpSites" doesn't conform to snake_case naming style (invalid-name)
engines/csv.py:29:15: R1734: Consider using [] instead of list() (use-list-literal)
engines/csv.py:38:10: E0602: Undefined variable '_' (undefined-variable)
engines/csv.py:43:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/csv.py:44:12: R1734: Consider using [] instead of list() (use-list-literal)
engines/csv.py:46:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
engines/csv.py:47:18: E1101: Module 'csv' has no 'Sniffer' member (no-member)
engines/csv.py:49:17: E1101: Module 'csv' has no 'reader' member (no-member)
engines/csv.py:51:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
engines/csv.py:52:21: E1101: Module 'csv' has no 'reader' member (no-member)
engines/csv.py:49:8: W0612: Unused variable 'reader' (unused-variable)
engines/csv.py:70:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/csv.py:71:19: R1734: Consider using [] instead of list() (use-list-literal)
engines/csv.py:78:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
engines/csv.py:79:17: E1101: Module 'csv' has no 'DictWriter' member (no-member)
engines/csv.py:4:0: C0411: standard import "csv" should be placed before first party imports "models.Sites", "engines.utils.use_item"  (wrong-import-order)

**Comment by 7h3Rabbit** [comment]
Solved and closed
