### ISSUE TITLE
PyLint for Improved Code Quality - engines/gov.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#297]
************* Module gov
engines/gov.py:14:0: C0301: Line too long (267/100) (line-too-long)
engines/gov.py:26:0: C0303: Trailing whitespace (trailing-whitespace)
engines/gov.py:30:0: C0304: Final newline missing (missing-final-newline)
engines/gov.py:1:0: C0114: Missing module docstring (missing-module-docstring)
engines/gov.py:7:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/gov.py:7:33: C0103: Argument name "siteTests" doesn't conform to snake_case naming style (invalid-name)
engines/gov.py:9:21: R1734: Consider using [] instead of list() (use-list-literal)
engines/gov.py:14:13: R0916: Too many boolean expressions in if statement (9/5) (too-many-boolean-expressions)
engines/gov.py:19:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
engines/gov.py:20:17: E1101: Module 'csv' has no 'DictWriter' member (no-member)
engines/gov.py:24:12: C0103: Variable name "siteTest" doesn't conform to snake_case naming style (invalid-name)
engines/gov.py:4:0: C0411: standard import "csv" should be placed before first party imports "models.Sites", "engines.utils.use_item"  (wrong-import-order)
engines/gov.py:2:0: W0611: Unused Sites imported from models (unused-import)
engines/gov.py:3:0: W0611: Unused use_item imported from engines.utils (unused-import)

**Comment by 7h3Rabbit** [comment]
solved and closed
