### ISSUE TITLE
PyLint for Improved Code Quality - engines/json.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#298]
************* Module json
engines/json.py:24:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
engines/json.py:1:0: C0114: Missing module docstring (missing-module-docstring)
engines/json.py:3:0: W0406: Module import itself (import-self)
engines/json.py:6:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/json.py:9:4: W0622: Redefining built-in 'id' (redefined-builtin)
engines/json.py:13:10: E0602: Undefined variable '_' (undefined-variable)
engines/json.py:18:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/json.py:20:4: C0103: Variable name "tmpSites" doesn't conform to snake_case naming style (invalid-name)
engines/json.py:20:15: R1734: Consider using [] instead of list() (use-list-literal)
engines/json.py:29:10: E0602: Undefined variable '_' (undefined-variable)
engines/json.py:34:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/json.py:35:12: R1734: Consider using [] instead of list() (use-list-literal)
engines/json.py:36:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
engines/json.py:37:15: E1101: Module 'json' has no 'load' member (no-member)
engines/json.py:46:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/json.py:47:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
engines/json.py:49:8: C0103: Variable name "jsonSites" doesn't conform to snake_case naming style (invalid-name)
engines/json.py:49:20: R1734: Consider using [] instead of list() (use-list-literal)
engines/json.py:58:8: C0103: Variable name "sitesContainerObject" doesn't conform to snake_case naming style (invalid-name)
engines/json.py:61:8: E1101: Module 'json' has no 'dump' member (no-member)
engines/json.py:64:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/json.py:65:13: R1734: Consider using [] instead of list() (use-list-literal)
engines/json.py:66:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
engines/json.py:67:15: E1101: Module 'json' has no 'load' member (no-member)
engines/json.py:80:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/json.py:80:33: C0103: Argument name "siteTests" doesn't conform to snake_case naming style (invalid-name)
engines/json.py:81:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
engines/json.py:83:8: C0103: Variable name "testsContainerObject" doesn't conform to snake_case naming style (invalid-name)
engines/json.py:86:8: E1101: Module 'json' has no 'dump' member (no-member)
engines/json.py:80:44: W0613: Unused argument 'sites' (unused-argument)
engines/json.py:3:0: C0411: standard import "json" should be placed before first party import "engines.utils.use_item"  (wrong-import-order)

**Comment by 7h3Rabbit** [comment]
solved and closed
