### ISSUE TITLE
PyLint for Improved Code Quality - engines/sitemap.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#299]
************* Module sitemap
engines/sitemap.py:52:0: C0301: Line too long (108/100) (line-too-long)
engines/sitemap.py:61:0: C0301: Line too long (122/100) (line-too-long)
engines/sitemap.py:69:0: C0301: Line too long (122/100) (line-too-long)
engines/sitemap.py:1:0: C0114: Missing module docstring (missing-module-docstring)
engines/sitemap.py:4:0: E0[401]: Unable to import 'config' (import-error)
engines/sitemap.py:5:0: W0401: Wildcard import tests.utils (wildcard-import)
engines/sitemap.py:11:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/sitemap.py:12:4: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
engines/sitemap.py:24:16: R1734: Consider using [] instead of list() (use-list-literal)
engines/sitemap.py:27:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/sitemap.py:28:12: R1734: Consider using [] instead of list() (use-list-literal)
engines/sitemap.py:37:8: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
engines/sitemap.py:52:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
engines/sitemap.py:37:8: W0612: Unused variable 'matchNum' (unused-variable)
engines/sitemap.py:60:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/sitemap.py:60:29: W0613: Unused argument 'url' (unused-argument)
engines/sitemap.py:68:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/sitemap.py:68:32: W0613: Unused argument 'url' (unused-argument)
engines/sitemap.py:4:0: C0411: third party import "config" should be placed before first party imports "models.Sites", "engines.utils.use_item"  (wrong-import-order)
engines/sitemap.py:6:0: C0411: standard import "re" should be placed before third party import "config" and first party imports "models.Sites", "engines.utils.use_item", "tests.utils.*"  (wrong-import-order)
engines/sitemap.py:7:0: C0411: standard import "gzip" should be placed before third party import "config" and first party imports "models.Sites", "engines.utils.use_item", "tests.utils.*"  (wrong-import-order)
engines/sitemap.py:8:0: C0411: standard import "io" should be placed before third party import "config" and first party imports "models.Sites", "engines.utils.use_item", "tests.utils.*"  (wrong-import-order)
engines/sitemap.py:2:0: W0611: Unused Sites imported from models (unused-import)
engines/sitemap.py:5:0: W0614: Unused import(s) hashlib, shutil, sys, socket, ssl, json, time, requests, urllib, uuid, dns, IP2Location, os, ip2location_db, ex, request_timeout, useragent, googlePageSpeedApiKey, gitHubApiKey, use_cache, cache_time_delta, dns_server, change_url_to_test_url, is_file_older_than, get_cache_path, get_cache_file, has_cache_file, clean_cache_files, set_cache_file, get_url_headers, has_redirect, get_guid, convert_to_seconds, is_sitemap, dns_lookup, dns_response_to_list, get_eu_countries, get_exception_countries, is_country_code_in_eu, is_country_code_in_exception_list, is_country_code_in_eu_or_on_exception_list, get_country_code_from_ip2location, get_best_country_code, get_friendly_url_name, datetime, timedelta, Path, BeautifulSoup, ParseResult, urlparse and urlunparse from wildcard import of tests.utils (unused-wildcard-import)

**Comment by 7h3Rabbit** [comment]
it will be less after issue #243 is finished:
engines/sitemap.py:47:0: C0303: Trailing whitespace (trailing-whitespace)
engines/sitemap.py:9:0: E0611: No name 'merge_dicts' in module 'utils' (no-name-in-module)
engines/sitemap.py:11:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/sitemap.py:21:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/sitemap.py:50:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/sitemap.py:50:0: R0914: Too many local variables (21/15) (too-many-locals)
engines/sitemap.py:64:8: R1723: Unnecessary "elif" after "break", remove the leading "el" from "elif" (no-else-break)
engines/sitemap.py:77:19: R1714: Consider merging these comparisons with 'in' by using 'child.name in ('url', 'sitemap')'. Use a set instead if elements are hashable. (consider-using-in)
engines/sitemap.py:111:19: R1716: Simplify chained comparison between the operands (chained-comparison)
engines/sitemap.py:114:19: R1714: Consider merging these comparisons with 'in' by using 'item_type not in ('html', 'htm')'. Use a set instead if elements are hashable. (consider-using-in)
engines/sitemap.py:120:16: R1724: Unnecessary "elif" after "continue", remove the leading "el" from "elif" (no-else-continue)
engines/sitemap.py:50:0: R0912: Too many branches (15/12) (too-many-branches)
engines/sitemap.py:132:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/sitemap.py:141:0: C0116: Missing function or method docstring (missing-function-docstring)

**Comment by 7h3Rabbit** [comment]
solved and closed
