### ISSUE TITLE
Check all requirements

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#3]
Not all of them is necessary for webperf_core.

**Comment by marcusosterberg** [comment]
Anyone who not yet has the environment set up (or keen on virtual environment) that'd like to check exactly what from requirement.txt actually is needed?

**Comment by flowertwig-org** [comment]
Borde vi inte kunna se detta rätt lätt genom att gå igenom vilka imports som faktiskt krävs i Python filerna och sedan ta bort de från requirements.txt om de ej behövs?

**Comment by flowertwig-org** [comment]
Delvis gjort i pull request #13

**Comment by 7h3Rabbit** [comment]
I will update all packages and reinstall webperf-core on new VM, when doing this I will remove all requirements not needed to run our code

**Comment by 7h3Rabbit** [comment]
The only requirements left are:
- beautifulsoup4==4.9.3
- lxml==4.6.2
- requests==2.25.1
- urllib3==1.26.2

**Comment by flowertwig-org** [comment]
Solved and closed
