### ISSUE TITLE
PyLint for Improved Code Quality - engines/sqlite.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#302]
************* Module sqlite
engines/sqlite.py:59:0: C0301: Line too long (103/100) (line-too-long)
engines/sqlite.py:74:0: C0301: Line too long (141/100) (line-too-long)
engines/sqlite.py:85:0: C0301: Line too long (247/100) (line-too-long)
engines/sqlite.py:86:0: C0301: Line too long (121/100) (line-too-long)
engines/sqlite.py:88:0: C0301: Line too long (125/100) (line-too-long)
engines/sqlite.py:90:0: C0301: Line too long (227/100) (line-too-long)
engines/sqlite.py:97:0: C0301: Line too long (256/100) (line-too-long)
engines/sqlite.py:1:0: C0114: Missing module docstring (missing-module-docstring)
engines/sqlite.py:6:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/sqlite.py:18:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/sqlite.py:30:10: E0602: Undefined variable '_' (undefined-variable)
engines/sqlite.py:35:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/sqlite.py:46:10: E0602: Undefined variable '_' (undefined-variable)
engines/sqlite.py:51:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/sqlite.py:52:12: R1734: Consider using [] instead of list() (use-list-literal)
engines/sqlite.py:59:25: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
engines/sqlite.py:67:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/sqlite.py:67:33: C0103: Argument name "siteTests" doesn't conform to snake_case naming style (invalid-name)
engines/sqlite.py:96:11: W0718: Catching too general exception Exception (broad-exception-caught)
engines/sqlite.py:97:11: R0916: Too many boolean expressions in if statement (8/5) (too-many-boolean-expressions)
engines/sqlite.py:108:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/sqlite.py:3:0: C0411: standard import "sqlite3" should be placed before first party import "engines.utils.use_item"  (wrong-import-order)

**Comment by 7h3Rabbit** [comment]
Solved and closed
