### ISSUE TITLE
PyLint for Improved Code Quality - engines/webperf.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#304]
************* Module webperf
engines/webperf.py:57:0: C0301: Line too long (135/100) (line-too-long)
engines/webperf.py:65:0: C0301: Line too long (135/100) (line-too-long)
engines/webperf.py:1:0: C0114: Missing module docstring (missing-module-docstring)
engines/webperf.py:4:0: E0401: Unable to import 'config' (import-error)
engines/webperf.py:5:0: W0401: Wildcard import tests.utils (wildcard-import)
engines/webperf.py:9:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/webperf.py:9:0: R0914: Too many local variables (16/15) (too-many-locals)
engines/webperf.py:10:12: R1734: Consider using [] instead of list() (use-list-literal)
engines/webperf.py:33:20: R1734: Consider using [] instead of list() (use-list-literal)
engines/webperf.py:35:8: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
engines/webperf.py:38:25: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
engines/webperf.py:35:8: W0612: Unused variable 'matchNum' (unused-variable)
engines/webperf.py:56:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/webperf.py:56:29: W0613: Unused argument 'url' (unused-argument)
engines/webperf.py:64:0: C0116: Missing function or method docstring (missing-function-docstring)
engines/webperf.py:64:32: W0613: Unused argument 'url' (unused-argument)
engines/webperf.py:4:0: C0411: third party import "config" should be placed before first party imports "models.Sites", "engines.utils.use_item"  (wrong-import-order)
engines/webperf.py:6:0: C0411: standard import "re" should be placed before third party import "config" and first party imports "models.Sites", "engines.utils.use_item", "tests.utils.*"  (wrong-import-order)
engines/webperf.py:2:0: W0611: Unused Sites imported from models (unused-import)
engines/webperf.py:4:0: W0611: Unused import config (unused-import)
engines/webperf.py:5:0: W0614: Unused import(s) hashlib, shutil, sys, socket, ssl, json, time, requests, urllib, uuid, dns, IP2Location, os, ip2location_db, ex, request_timeout, useragent, googlePageSpeedApiKey, gitHubApiKey, use_cache, cache_time_delta, dns_server, change_url_to_test_url, is_file_older_than, get_cache_path, get_cache_file, has_cache_file, clean_cache_files, set_cache_file, get_content_type, get_url_headers, has_redirect, get_guid, convert_to_seconds, is_sitemap, dns_lookup, dns_response_to_list, get_eu_countries, get_exception_countries, is_country_code_in_eu, is_country_code_in_exception_list, is_country_code_in_eu_or_on_exception_list, get_country_code_from_ip2location, get_best_country_code, get_friendly_url_name, datetime, timedelta, Path, BeautifulSoup, ParseResult, urlparse and urlunparse from wildcard import of tests.utils (unused-wildcard-import)

**Comment by 7h3Rabbit** [comment]
Solved and closed.
