### ISSUE TITLE
PyLint for Improved Code Quality - filter-unknown-sources.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#305]
************* Module filter-unknown-sources
filter-unknown-sources.py:60:0: C0303: Trailing whitespace (trailing-whitespace)
filter-unknown-sources.py:1:0: C0114: Missing module docstring (missing-module-docstring)
filter-unknown-sources.py:1:0: C0103: Module name "filter-unknown-sources" doesn't conform to snake_case naming style (invalid-name)
filter-unknown-sources.py:3:0: E0401: Unable to import 'config' (import-error)
filter-unknown-sources.py:6:0: W0404: Reimport 'sys' (imported line 2) (reimported)
filter-unknown-sources.py:9:0: W0404: Reimport 'config' (imported line 3) (reimported)
filter-unknown-sources.py:9:0: E0401: Unable to import 'config' (import-error)
filter-unknown-sources.py:11:0: W0401: Wildcard import tests.utils (wildcard-import)
filter-unknown-sources.py:12:0: E0401: Unable to import 'packaging.version' (import-error)
filter-unknown-sources.py:50:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
filter-unknown-sources.py:14:9: W0613: Unused argument 'argv' (unused-argument)
filter-unknown-sources.py:57:0: C0116: Missing function or method docstring (missing-function-docstring)
filter-unknown-sources.py:58:4: W0622: Redefining built-in 'dir' (redefined-builtin)
filter-unknown-sources.py:61:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
filter-unknown-sources.py:63:20: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
filter-unknown-sources.py:65:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
filter-unknown-sources.py:69:11: E1101: Module 'json' has no 'dumps' member (no-member)
filter-unknown-sources.py:73:0: C0116: Missing function or method docstring (missing-function-docstring)
filter-unknown-sources.py:74:4: W0622: Redefining built-in 'dir' (redefined-builtin)
filter-unknown-sources.py:77:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
filter-unknown-sources.py:79:20: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
filter-unknown-sources.py:81:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
filter-unknown-sources.py:87:9: W1[514]: Using open without explicitly specifying an encoding (unspecified-encoding)
filter-unknown-sources.py:88:21: E1101: Module 'json' has no 'load' member (no-member)
filter-unknown-sources.py:104:0: W0105: String statement has no effect (pointless-string-statement)
filter-unknown-sources.py:4:0: C0411: standard import "datetime.datetime" should be placed before third party import "config" (wrong-import-order)
filter-unknown-sources.py:5:0: C0411: standard import "pathlib.Path" should be placed before third party import "config" (wrong-import-order)
filter-unknown-sources.py:6:0: C0411: standard import "sys" should be placed before third party import "config" (wrong-import-order)
filter-unknown-sources.py:7:0: C0411: standard import "json" should be placed before third party import "config" (wrong-import-order)
filter-unknown-sources.py:8:0: C0411: standard import "re" should be placed before third party import "config" (wrong-import-order)
filter-unknown-sources.py:10:0: C0411: standard import "os" should be placed before third party imports "config", "config" (wrong-import-order)
filter-unknown-sources.py:12:0: C0411: third party import "packaging.version" should be placed before first party import "tests.utils.*"  (wrong-import-order)
filter-unknown-sources.py:6:0: C0412: Imports from package sys are not grouped (ungrouped-imports)
filter-unknown-sources.py:3:0: W0611: Unused import config (unused-import)
filter-unknown-sources.py:4:0: W0611: Unused datetime imported from datetime (unused-import)
filter-unknown-sources.py:8:0: W0611: Unused import re (unused-import)
filter-unknown-sources.py:12:0: W0611: Unused import packaging.version (unused-import)
filter-unknown-sources.py:11:0: W0614: Unused import(s) hashlib, shutil, socket, ssl, time, requests, urllib, uuid, dns, IP2Location, ip2location_db, ex, request_timeout, useragent, googlePageSpeedApiKey, gitHubApiKey, use_cache, cache_time_delta, dns_server, change_url_to_test_url, is_file_older_than, get_cache_path, get_cache_file, has_cache_file, clean_cache_files, set_cache_file, httpRequestGetContent, get_content_type, get_url_headers, has_redirect, get_guid, convert_to_seconds, is_sitemap, dns_lookup, dns_response_to_list, get_eu_countries, get_exception_countries, is_country_code_in_eu, is_country_code_in_exception_list, is_country_code_in_eu_or_on_exception_list, get_country_code_from_ip2location, get_best_country_code, get_friendly_url_name, timedelta, BeautifulSoup, ParseResult, urlparse and urlunparse from wildcard import of tests.utils (unused-wildcard-import)

**Comment by 7h3Rabbit** [comment]
filter-unknown-sources.py:54:0: C0303: Trailing whitespace (trailing-whitespace)
filter-unknown-sources.py:1:0: C0103: Module name "filter-unknown-sources" doesn't conform to snake_case naming style (invalid-name)
filter-unknown-sources.py:4:0: W0404: Reimport 'sys' (imported line 2) (reimported)
filter-unknown-sources.py:44:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
filter-unknown-sources.py:8:9: W0613: Unused argument 'argv' (unused-argument)
filter-unknown-sources.py:51:0: C0116: Missing function or method docstring (missing-function-docstring)
filter-unknown-sources.py:52:4: W0622: Redefining built-in 'dir' (redefined-builtin)
filter-unknown-sources.py:55:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
filter-unknown-sources.py:57:20: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
filter-unknown-sources.py:59:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
filter-unknown-sources.py:67:0: C0116: Missing function or method docstring (missing-function-docstring)
filter-unknown-sources.py:68:4: W0622: Redefining built-in 'dir' (redefined-builtin)
filter-unknown-sources.py:71:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
filter-unknown-sources.py:73:20: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
filter-unknown-sources.py:75:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
filter-unknown-sources.py:81:9: W1[51](https://github.com/Webperf-se/webperf_core/actions/runs/8588845582/job/23534216988#step:6:52)4: Using open without explicitly specifying an encoding (unspecified-encoding)
filter-unknown-sources.py:98:0: W0105: String statement has no effect (pointless-string-statement)
filter-unknown-sources.py:4:0: C0412: Imports from package sys are not grouped (ungrouped-imports)

**Comment by 7h3Rabbit** [comment]
Solved and closed
