### ISSUE TITLE
PyLint for Improved Code Quality - models.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#306]
************* Module models
models.py:17:0: C0303: Trailing whitespace (trailing-whitespace)
models.py:23:0: C0303: Trailing whitespace (trailing-whitespace)
models.py:26:0: C0303: Trailing whitespace (trailing-whitespace)
models.py:29:0: C0301: Line too long (310/100) (line-too-long)
models.py:32:0: C0301: Line too long (132/100) (line-too-long)
models.py:92:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
models.py:94:0: C0325: Unnecessary parens after 'elif' keyword (superfluous-parens)
models.py:108:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
models.py:110:0: C0325: Unnecessary parens after 'elif' keyword (superfluous-parens)
models.py:124:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
models.py:126:0: C0325: Unnecessary parens after 'elif' keyword (superfluous-parens)
models.py:140:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
models.py:142:0: C0325: Unnecessary parens after 'elif' keyword (superfluous-parens)
models.py:156:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
models.py:158:0: C0325: Unnecessary parens after 'elif' keyword (superfluous-parens)
models.py:208:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
models.py:218:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
models.py:226:0: C0301: Line too long (145/100) (line-too-long)
models.py:227:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
models.py:235:0: C0301: Line too long (101/100) (line-too-long)
models.py:236:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
models.py:244:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
models.py:252:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
models.py:266:0: C0325: Unnecessary parens after 'elif' keyword (superfluous-parens)
models.py:273:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
models.py:276:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
models.py:278:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
models.py:280:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
models.py:353:0: C0301: Line too long (103/100) (line-too-long)
models.py:1:0: C0114: Missing module docstring (missing-module-docstring)
models.py:4:0: C0115: Missing class docstring (missing-class-docstring)
models.py:5:4: R0913: Too many arguments (8/5) (too-many-arguments)
models.py:27:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
models.py:34:0: C0115: Missing class docstring (missing-class-docstring)
models.py:34:0: R0205: Class 'Sites' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
models.py:42:23: W0622: Redefining built-in 'id' (redefined-builtin)
models.py:46:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:54:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:59:15: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
models.py:62:0: C0115: Missing class docstring (missing-class-docstring)
models.py:62:0: R0205: Class 'Rating' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
models.py:62:0: R0902: Too many instance attributes (18/7) (too-many-instance-attributes)
models.py:89:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:102:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:105:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:118:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:121:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:134:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:137:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:150:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:153:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:166:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:169:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:172:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:173:21: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
models.py:175:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:191:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:202:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:208:8: R1720: Unnecessary "else" after "raise", remove the "else" and de-indent the code inside it (no-else-raise)
models.py:211:15: C0121: Comparison 'self._ != None' should be 'self._ is not None' (singleton-comparison)
models.py:259:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:262:8: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
models.py:287:0: C0115: Missing class docstring (missing-class-docstring)
models.py:287:0: R0205: Class 'SiteTests' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
models.py:287:0: R0902: Too many instance attributes (14/7) (too-many-instance-attributes)
models.py:307:4: R0913: Too many arguments (6/5) (too-many-arguments)
models.py:324:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:329:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:349:4: C0116: Missing function or method docstring (missing-function-docstring)
models.py:357:15: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)

**Comment by 7h3Rabbit** [comment]
@cockroacher  Nice :)

Solved and closed
