### ISSUE TITLE
PyLint for Improved Code Quality - tests/email_validator.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#314]
************* Module tests.email_validator
tests/email_validator.py:18:0: C0301: Line too long (124/100) (line-too-long)
tests/email_validator.py:215:0: C0301: Line too long (190/100) (line-too-long)
tests/email_validator.py:241:0: C0301: Line too long (101/100) (line-too-long)
tests/email_validator.py:243:0: C0301: Line too long (159/100) (line-too-long)
tests/email_validator.py:245:0: C0301: Line too long (160/100) (line-too-long)
tests/email_validator.py:247:0: C0301: Line too long (126/100) (line-too-long)
tests/email_validator.py:249:0: C0301: Line too long (125/100) (line-too-long)
tests/email_validator.py:251:0: C0301: Line too long (101/100) (line-too-long)
tests/email_validator.py:253:0: C0301: Line too long (114/100) (line-too-long)
tests/email_validator.py:308:0: C0301: Line too long (123/100) (line-too-long)
tests/email_validator.py:638:0: C0301: Line too long (105/100) (line-too-long)
tests/email_validator.py:770:0: C0301: Line too long (105/100) (line-too-long)
tests/email_validator.py:778:0: C0301: Line too long (124/100) (line-too-long)
tests/email_validator.py:793:0: C0301: Line too long (114/100) (line-too-long)
tests/email_validator.py:812:0: C0301: Line too long (105/100) (line-too-long)
tests/email_validator.py:820:0: C0301: Line too long (124/100) (line-too-long)
tests/email_validator.py:835:0: C0301: Line too long (114/100) (line-too-long)
tests/email_validator.py:948:0: C0301: Line too long (104/100) (line-too-long)
tests/email_validator.py:713:21: W0511: TODO: What do this do and should we rate on it? (fixme)
tests/email_validator.py:716:21: W0511: TODO: What do this do and should we rate on it? (fixme)
tests/email_validator.py:722:21: W0511: TODO: What do this do and should we rate on it? (fixme)
tests/email_validator.py:725:21: W0511: TODO: What do this do and should we rate on it? (fixme)
tests/email_validator.py:728:21: W0511: TODO: What do this do and should we rate on it? (fixme)
tests/email_validator.py:1:0: C0114: Missing module docstring (missing-module-docstring)
tests/email_validator.py:3:0: E0401: Unable to import 'bs4' (import-error)
tests/email_validator.py:10:0: W0404: Reimport 'datetime' (imported line 5) (reimported)
tests/email_validator.py:15:0: E0401: Unable to import 'dns' (import-error)
tests/email_validator.py:16:0: E0401: Unable to import 'config' (import-error)
tests/email_validator.py:32:0: C0115: Missing class docstring (missing-class-docstring)
tests/email_validator.py:32:0: C0103: Class name "SMTP_WEBPERF" doesn't conform to PascalCase naming style (invalid-name)
tests/email_validator.py:32:0: R0902: Too many instance attributes (9/7) (too-many-instance-attributes)
tests/email_validator.py:33:4: W0231: __init__ method from base class 'SMTP' is not called (super-init-not-called)
tests/email_validator.py:33:4: R0913: Too many arguments (6/5) (too-many-arguments)
tests/email_validator.py:489:0: C0103: Function name "Rate_Use_of_PTR_for_SPF_Policies" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:501:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:501:0: C0103: Function name "Rate_Fail_Configuration_for_SPF_Policies" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:545:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:545:0: C0103: Function name "Rate_Invalid_format_SPF_Policies" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:565:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:565:0: C0103: Function name "Rate_has_SPF_Policies" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:585:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:585:0: C0103: Function name "Rate_Too_many_DNS_lookup_for_SPF_Policies" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:598:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:598:0: C0103: Function name "Rate_GDPR_for_SPF_Policies" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:599:20: R1734: Consider using [] instead of list() (use-list-literal)
tests/email_validator.py:601:34: R1734: Consider using [] instead of list() (use-list-literal)
tests/email_validator.py:603:34: R1734: Consider using [] instead of list() (use-list-literal)
tests/email_validator.py:617:11: R1714: Consider merging these comparisons with 'in' by using 'country_code in ('', '-')'. Use a set instead if elements are hashable. (consider-using-in)
tests/email_validator.py:649:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:649:0: C0103: Function name "Validate_SPF_Policy" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:732:15: W0718: Catching too general exception Exception (broad-exception-caught)
tests/email_validator.py:686:50: R1734: Consider using [] instead of list() (use-list-literal)
tests/email_validator.py:691:50: R1734: Consider using [] instead of list() (use-list-literal)
tests/email_validator.py:649:0: R0912: Too many branches (26/12) (too-many-branches)
tests/email_validator.py:649:0: R0915: Too many statements (58/50) (too-many-statements)
tests/email_validator.py:711:20: W0612: Unused variable 'c' (unused-variable)
tests/email_validator.py:738:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:739:24: R1734: Consider using [] instead of list() (use-list-literal)
tests/email_validator.py:751:37: C2801: Unnecessarily calls dunder method __format__. Use format built-in function, format string method, or f-string. (unnecessary-dunder-call)
tests/email_validator.py:751:37: C2801: Unnecessarily calls dunder method __getitem__. Access item via subscript. (unnecessary-dunder-call)
tests/email_validator.py:753:37: C2801: Unnecessarily calls dunder method __format__. Use format built-in function, format string method, or f-string. (unnecessary-dunder-call)
tests/email_validator.py:753:37: C2801: Unnecessarily calls dunder method __getitem__. Access item via subscript. (unnecessary-dunder-call)
tests/email_validator.py:763:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:763:0: C0103: Function name "Validate_IPv6_Operation_Status" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:764:31: R1734: Consider using [] instead of list() (use-list-literal)
tests/email_validator.py:766:40: R1734: Consider using [] instead of list() (use-list-literal)
tests/email_validator.py:777:15: W0718: Catching too general exception Exception (broad-exception-caught)
tests/email_validator.py:805:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:805:0: C0103: Function name "Validate_IPv4_Operation_Status" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:806:31: R1734: Consider using [] instead of list() (use-list-literal)
tests/email_validator.py:808:40: R1734: Consider using [] instead of list() (use-list-literal)
tests/email_validator.py:819:15: W0718: Catching too general exception Exception (broad-exception-caught)
tests/email_validator.py:847:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:847:0: C0103: Function name "Validate_MX_Records" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:847:0: R0914: Too many local variables (25/15) (too-many-locals)
tests/email_validator.py:851:20: R1734: Consider using [] instead of list() (use-list-literal)
tests/email_validator.py:853:19: R1734: Consider using [] instead of list() (use-list-literal)
tests/email_validator.py:854:19: R1734: Consider using [] instead of list() (use-list-literal)
tests/email_validator.py:855:20: R1734: Consider using [] instead of list() (use-list-literal)
tests/email_validator.py:927:11: R1714: Consider merging these comparisons with 'in' by using 'country_code in ('', '-')'. Use a set instead if elements are hashable. (consider-using-in)
tests/email_validator.py:847:0: R0912: Too many branches (17/12) (too-many-branches)
tests/email_validator.py:847:0: R0915: Too many statements (77/50) (too-many-statements)
tests/email_validator.py:849:4: W0612: Unused variable 'has_mx_records_rating' (unused-variable)
tests/email_validator.py:4:0: C0411: standard import "smtplib" should be placed before third party import "bs4.BeautifulSoup" (wrong-import-order)
tests/email_validator.py:5:0: C0411: standard import "datetime" should be placed before third party import "bs4.BeautifulSoup" (wrong-import-order)
tests/email_validator.py:6:0: C0411: standard import "socket" should be placed before third party import "bs4.BeautifulSoup" (wrong-import-order)
tests/email_validator.py:7:0: C0411: standard import "ipaddress" should be placed before third party import "bs4.BeautifulSoup" (wrong-import-order)
tests/email_validator.py:8:0: C0411: standard import "sys" should be placed before third party import "bs4.BeautifulSoup" (wrong-import-order)
tests/email_validator.py:9:0: C0411: standard import "urllib.parse" should be placed before third party import "bs4.BeautifulSoup" (wrong-import-order)
tests/email_validator.py:10:0: C0411: standard import "datetime" should be placed before third party import "bs4.BeautifulSoup" (wrong-import-order)
tests/email_validator.py:11:0: C0411: standard import "time" should be placed before third party import "bs4.BeautifulSoup" (wrong-import-order)
tests/email_validator.py:13:0: C0411: standard import "urllib" should be placed before third party import "bs4.BeautifulSoup" (wrong-import-order)
tests/email_validator.py:19:0: C0411: standard import "gettext" should be placed before third party imports "bs4.BeautifulSoup", "dns", "config" and first party imports "models.Rating", "tests.utils.dns_lookup"  (wrong-import-order)
tests/email_validator.py:10:0: C0412: Imports from package datetime are not grouped (ungrouped-imports)
tests/email_validator.py:13:0: C0412: Imports from package urllib are not grouped (ungrouped-imports)

**Comment by 7h3Rabbit** [comment]
tests/email_validator.py:210:0: C0301: Line too long (190/100) (line-too-long)
tests/email_validator.py:236:0: C0301: Line too long (101/100) (line-too-long)
tests/email_validator.py:238:0: C0301: Line too long (159/100) (line-too-long)
tests/email_validator.py:240:0: C0301: Line too long (160/100) (line-too-long)
tests/email_validator.py:242:0: C0301: Line too long (126/100) (line-too-long)
tests/email_validator.py:244:0: C0301: Line too long (125/100) (line-too-long)
tests/email_validator.py:246:0: C0301: Line too long (101/100) (line-too-long)
tests/email_validator.py:248:0: C0301: Line too long (114/100) (line-too-long)
tests/email_validator.py:482:0: C0301: Line too long (107/100) (line-too-long)
tests/email_validator.py:486:0: C0301: Line too long (109/100) (line-too-long)
tests/email_validator.py:758:0: C0301: Line too long (103/100) (line-too-long)
tests/email_validator.py:762:0: C0301: Line too long (105/100) (line-too-long)
tests/email_validator.py:765:0: C0301: Line too long (105/100) (line-too-long)
tests/email_validator.py:351:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:[351](https://github.com/Webperf-se/webperf_core/actions/runs/8588845582/job/23534216988#step:6:352):0: C0103: Function name "Validate_MTA_STS_Policy" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:351:0: R0914: Too many local variables (24/15) (too-many-locals)
tests/email_validator.py:376:8: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/email_validator.py:428:21: R1714: Consider merging these comparisons with 'in' by using 'value in ('testing', 'none')'. Use a set instead if elements are hashable. (consider-using-in)
tests/email_validator.py:351:0: R0912: Too many branches (21/12) (too-many-branches)
tests/email_validator.py:351:0: R0915: Too many statements (80/50) (too-many-statements)
tests/email_validator.py:427:20: W0612: Unused variable 'a' (unused-variable)
tests/email_validator.py:481:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:481:0: C0103: Function name "Validate_DMARC_Policies" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:491:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:491:0: C0103: Function name "Validate_DMARC_Policy" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:623:15: W0718: Catching too general exception Exception (broad-exception-caught)
tests/email_validator.py:534:23: R1714: Consider merging these comparisons with 'in' by using 'data in ('none', 'quarantine', 'reject')'. Use a set instead if elements are hashable. (consider-using-in)
tests/email_validator.py:541:23: R1714: Consider merging these comparisons with 'in' by using 'data in ('none', 'quarantine', 'reject')'. Use a set instead if elements are hashable. (consider-using-in)
tests/email_validator.py:578:29: R1714: Consider merging these comparisons with 'in' by using 'field in ('1', 'd', 's')'. Use a set instead if elements are hashable. (consider-using-in)
tests/email_validator.py:502:4: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
tests/email_validator.py:502:4: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
tests/email_validator.py:491:0: R0912: Too many branches (39/12) (too-many-branches)
tests/email_validator.py:491:0: R0915: Too many statements (92/50) (too-many-statements)
tests/email_validator.py:502:4: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
tests/email_validator.py:491:26: W0613: Unused argument 'global_translation' (unused-argument)
tests/email_validator.py:631:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:631:0: C0103: Function name "Rate_has_DMARC_Policies" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:631:0: R0912: Too many branches (22/12) (too-many-branches)
tests/email_validator.py:631:0: R0915: Too many statements (83/50) (too-many-statements)
tests/email_validator.py:757:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:757:0: C0103: Function name "Validate_SPF_Policies" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:775:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:775:0: C0103: Function name "Rate_Use_of_PTR_for_SPF_Policies" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:787:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:787:0: C0103: Function name "Rate_Fail_Configuration_for_SPF_Policies" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:831:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:831:0: C0103: Function name "Rate_Invalid_format_SPF_Policies" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:851:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:851:0: C0103: Function name "Rate_has_SPF_Policies" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:871:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:871:0: C0103: Function name "Rate_Too_many_DNS_lookup_for_SPF_Policies" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:884:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:884:0: C0103: Function name "Rate_GDPR_for_SPF_Policies" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:903:11: R1714: Consider merging these comparisons with 'in' by using 'country_code in ('', '-')'. Use a set instead if elements are hashable. (consider-using-in)
tests/email_validator.py:935:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:935:0: C0103: Function name "Validate_SPF_Policy" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:1018:15: W0718: Catching too general exception Exception (broad-exception-caught)
tests/email_validator.py:935:0: R0912: Too many branches (26/12) (too-many-branches)
tests/email_validator.py:935:0: R0915: Too many statements (58/50) (too-many-statements)
tests/email_validator.py:997:20: W0612: Unused variable 'c' (unused-variable)
tests/email_validator.py:1024:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1037:37: C2801: Unnecessarily calls dunder method __format__. Use format built-in function, format string method, or f-string. (unnecessary-dunder-call)
tests/email_validator.py:1037:37: C2801: Unnecessarily calls dunder method __getitem__. Access item via subscript. (unnecessary-dunder-call)
tests/email_validator.py:1039:37: C2801: Unnecessarily calls dunder method __format__. Use format built-in function, format string method, or f-string. (unnecessary-dunder-call)
tests/email_validator.py:1039:37: C2801: Unnecessarily calls dunder method __getitem__. Access item via subscript. (unnecessary-dunder-call)
tests/email_validator.py:1049:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1049:0: C0103: Function name "Validate_IPv6_Operation_Status" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:1063:15: W0718: Catching too general exception Exception (broad-exception-caught)
tests/email_validator.py:1091:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1091:0: C0103: Function name "Validate_IPv4_Operation_Status" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:1105:15: W0718: Catching too general exception Exception (broad-exception-caught)
tests/email_validator.py:1133:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1133:0: C0103: Function name "Validate_MX_Records" doesn't conform to snake_case naming style (invalid-name)
tests/email_validator.py:1133:0: R0914: Too many local variables (29/15) (too-many-locals)
tests/email_validator.py:1217:11: R1714: Consider merging these comparisons with 'in' by using 'country_code in ('', '-')'. Use a set instead if elements are hashable. (consider-using-in)
tests/email_validator.py:1133:0: R0912: Too many branches (19/12) (too-many-branches)
tests/email_validator.py:1133:0: R0915: Too many statements (80/50) (too-many-statements)
tests/email_validator.py:1135:4: W0612: Unused variable 'has_mx_records_rating' (unused-variable)

**Comment by 7h3Rabbit** [comment]
************* Module tests.email_validator
tests/email_validator.py:1:0: C0302: Too many lines in module (1331/1000) (too-many-lines)
tests/email_validator.py:29:0: C0115: Missing class docstring (missing-class-docstring)
tests/email_validator.py:30:4: W0231: __init__ method from base class 'SMTP' is not called (super-init-not-called)
tests/email_validator.py:167:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:274:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:333:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:337:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:352:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:395:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:395:0: R0914: Too many local variables (23/15) (too-many-locals)
tests/email_validator.py:395:0: R0912: Too many branches (21/12) (too-many-branches)
tests/email_validator.py:395:0: R0915: Too many statements (80/50) (too-many-statements)
tests/email_validator.py:522:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:536:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:536:0: R0912: Too many branches (38/12) (too-many-branches)
tests/email_validator.py:536:0: R0915: Too many statements (89/50) (too-many-statements)
tests/email_validator.py:669:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:669:0: R0912: Too many branches (22/12) (too-many-branches)
tests/email_validator.py:669:0: R0915: Too many statements (83/50) (too-many-statements)
tests/email_validator.py:795:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:8[25](https://github.com/Webperf-se/webperf_core/actions/runs/8835154063/job/24258595037#step:6:26):0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:837:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:885:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:905:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:925:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:942:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:995:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:995:0: R0912: Too many branches (25/12) (too-many-branches)
tests/email_validator.py:995:0: R0915: Too many statements (55/50) (too-many-statements)
tests/email_validator.py:1073:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1097:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1143:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1186:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1205:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1212:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1[26](https://github.com/Webperf-se/webperf_core/actions/runs/8835154063/job/24258595037#step:6:27)3:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1287:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1311:0: C0116: Missing function or method docstring (missing-function-docstring)

**Comment by 7h3Rabbit** [comment]
************* Module tests.email_validator
tests/email_validator.py:522:0: C0303: Trailing whitespace (trailing-whitespace)
tests/email_validator.py:687:0: C0303: Trailing whitespace (trailing-whitespace)
tests/email_validator.py:717:0: C0303: Trailing whitespace (trailing-whitespace)
tests/email_validator.py:1005:0: C0303: Trailing whitespace (trailing-whitespace)
tests/email_validator.py:1:0: C0302: Too many lines in module (1398/1000) (too-many-lines)
tests/email_validator.py:29:0: C0115: Missing class docstring (missing-class-docstring)
tests/email_validator.py:30:4: W0[23](https://github.com/Webperf-se/webperf_core/actions/runs/8837816807/job/24267526243#step:6:24)1: __init__ method from base class 'SMTP' is not called (super-init-not-called)
tests/email_validator.py:167:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:274:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:333:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:337:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:352:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:395:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:395:0: R0914: Too many local variables (22/15) (too-many-locals)
tests/email_validator.py:395:0: R0912: Too many branches (19/12) (too-many-branches)
tests/email_validator.py:395:0: R0915: Too many statements (71/50) (too-many-statements)
tests/email_validator.py:508:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:526:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:540:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:586:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:644:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:660:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:690:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:721:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:751:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:763:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:811:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:831:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:851:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:868:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:920:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:926:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:932:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:938:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:942:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:946:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:950:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:954:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:957:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:962:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:990:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:998:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1006:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1018:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1030:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1046:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1051:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1056:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1062:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1077:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1088:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1106:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1140:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1164:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1210:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1[25](https://github.com/Webperf-se/webperf_core/actions/runs/8837816807/job/24267526243#step:6:26)3:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1272:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1[27](https://github.com/Webperf-se/webperf_core/actions/runs/8837816807/job/24267526243#step:6:28)9:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1330:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1354:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/email_validator.py:1378:0: C0116: Missing function or method docstring (missing-function-docstring)
