### ISSUE TITLE
PyLint for Improved Code Quality - tests/energy_efficiency.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#315]
************* Module tests.energy_efficiency
tests/energy_efficiency.py:26:0: C0301: Line too long (156/100) (line-too-long)
tests/energy_efficiency.py:38:0: C0301: Line too long (174/100) (line-too-long)
tests/energy_efficiency.py:64:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
tests/energy_efficiency.py:132:0: C0301: Line too long (106/100) (line-too-long)
tests/energy_efficiency.py:134:0: C0301: Line too long (111/100) (line-too-long)
tests/energy_efficiency.py:146:0: C0301: Line too long (101/100) (line-too-long)
tests/energy_efficiency.py:1:0: C0114: Missing module docstring (missing-module-docstring)
tests/energy_efficiency.py:6:0: R0402: Use 'from tests import energy_efficiency_carbon_percentiles' instead (consider-using-from-import)
tests/energy_efficiency.py:8:0: W0401: Wildcard import tests.utils (wildcard-import)
tests/energy_efficiency.py:25:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/energy_efficiency.py:29:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/energy_efficiency.py:29:23: C0103: Argument name "bytesAdjusted" doesn't conform to snake_case naming style (invalid-name)
tests/energy_efficiency.py:33:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/energy_efficiency.py:41:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/energy_efficiency.py:42:4: C0103: Variable name "bytesAdjusted" doesn't conform to snake_case naming style (invalid-name)
tests/energy_efficiency.py:44:4: C0103: Variable name "co2Grid" doesn't conform to snake_case naming style (invalid-name)
tests/energy_efficiency.py:49:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/energy_efficiency.py:69:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/energy_efficiency.py:80:16: C0103: Argument name "langCode" doesn't conform to snake_case naming style (invalid-name)
tests/energy_efficiency.py:113:19: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/energy_efficiency.py:5:0: C0411: standard import "datetime" should be placed before first party imports "tests.performance_lighthouse.run_test", "models.Rating"  (wrong-import-order)
tests/energy_efficiency.py:9:0: C0411: standard import "gettext" should be placed before first party imports "tests.performance_lighthouse.run_test", "models.Rating", "tests.energy_efficiency_carbon_percentiles", "tests.energy_efficiency_carbon_percentiles2021", "tests.utils.*"  (wrong-import-order)
tests/energy_efficiency.py:2:0: W0611: Unused truncate imported from os (unused-import)
tests/energy_efficiency.py:8:0: W0614: Unused import(s) hashlib, shutil, sys, socket, ssl, json, time, requests, urllib, uuid, re, dns, config, IP2Location, os, ip2location_db, ex, request_timeout, useragent, googlePageSpeedApiKey, gitHubApiKey, use_cache, cache_time_delta, dns_server, change_url_to_test_url, is_file_older_than, get_cache_path, get_cache_file, has_cache_file, clean_cache_files, set_cache_file, httpRequestGetContent, get_content_type, get_url_headers, has_redirect, get_guid, convert_to_seconds, is_sitemap, dns_lookup, dns_response_to_list, get_eu_countries, get_exception_countries, is_country_code_in_eu, is_country_code_in_exception_list, is_country_code_in_eu_or_on_exception_list, get_country_code_from_ip2location, get_best_country_code, get_friendly_url_name, timedelta, Path, BeautifulSoup, ParseResult, urlparse and urlunparse from wildcard import of tests.utils (unused-wildcard-import)
************* Module tests.energy_efficiency_carbon_percentiles
tests/energy_efficiency_carbon_percentiles.py:3:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
tests/energy_efficiency_carbon_percentiles.py:6:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
tests/energy_efficiency_carbon_percentiles.py:116:0: C0304: Final newline missing (missing-final-newline)
tests/energy_efficiency_carbon_percentiles.py:1:0: C0114: Missing module docstring (missing-module-docstring)
tests/energy_efficiency_carbon_percentiles.py:2:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/energy_efficiency_carbon_percentiles.py:5:0: C0116: Missing function or method docstring (missing-function-docstring)
************* Module tests.energy_efficiency_carbon_percentiles2021
tests/energy_efficiency_carbon_percentiles2021.py:3:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
tests/energy_efficiency_carbon_percentiles2021.py:6:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
tests/energy_efficiency_carbon_percentiles2021.py:116:0: C0304: Final newline missing (missing-final-newline)
tests/energy_efficiency_carbon_percentiles2021.py:1:0: C0114: Missing module docstring (missing-module-docstring)
tests/energy_efficiency_carbon_percentiles2021.py:2:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/energy_efficiency_carbon_percentiles2021.py:5:0: C0116: Missing function or method docstring (missing-function-docstring)
************* Module tests.energy_efficiency_websitecarbon
tests/energy_efficiency_websitecarbon.py:1:0: C0114: Missing module docstring (missing-module-docstring)
tests/energy_efficiency_websitecarbon.py:8:0: E0401: Unable to import 'requests' (import-error)
tests/energy_efficiency_websitecarbon.py:12:0: E0401: Unable to import 'bs4' (import-error)
tests/energy_efficiency_websitecarbon.py:15:0: E0401: Unable to import 'config' (import-error)
tests/energy_efficiency_websitecarbon.py:16:0: W0401: Wildcard import tests.utils (wildcard-import)
tests/energy_efficiency_websitecarbon.py:21:16: C0103: Argument name "langCode" doesn't conform to snake_case naming style (invalid-name)
tests/energy_efficiency_websitecarbon.py:36:8: E1101: Class 'datetime' has no 'datetime' member (no-member)
tests/energy_efficiency_websitecarbon.py:39:8: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/energy_efficiency_websitecarbon.py:40:18: E1101: Module 'json' has no 'loads' member (no-member)
tests/energy_efficiency_websitecarbon.py:58:19: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/energy_efficiency_websitecarbon.py:84:8: E1101: Class 'datetime' has no 'datetime' member (no-member)
tests/energy_efficiency_websitecarbon.py:3:0: C0411: standard import "datetime" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/energy_efficiency_websitecarbon.py:4:0: C0411: standard import "sys" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/energy_efficiency_websitecarbon.py:5:0: C0411: standard import "socket" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/energy_efficiency_websitecarbon.py:6:0: C0411: standard import "ssl" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/energy_efficiency_websitecarbon.py:7:0: C0411: standard import "json" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/energy_efficiency_websitecarbon.py:8:0: C0411: third party import "requests" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/energy_efficiency_websitecarbon.py:9:0: C0411: standard import "urllib" should be placed before third party import "requests" and first party import "models.Rating"  (wrong-import-order)
tests/energy_efficiency_websitecarbon.py:10:0: C0411: standard import "uuid" should be placed before third party import "requests" and first party import "models.Rating"  (wrong-import-order)
tests/energy_efficiency_websitecarbon.py:11:0: C0411: standard import "re" should be placed before third party import "requests" and first party import "models.Rating"  (wrong-import-order)
tests/energy_efficiency_websitecarbon.py:12:0: C0411: third party import "bs4.BeautifulSoup" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/energy_efficiency_websitecarbon.py:13:0: C0411: standard import "decimal.Decimal" should be placed before third party imports "requests", "bs4.BeautifulSoup" and first party import "models.Rating"  (wrong-import-order)
tests/energy_efficiency_websitecarbon.py:15:0: C0411: third party import "config" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/energy_efficiency_websitecarbon.py:17:0: C0411: standard import "gettext" should be placed before third party imports "requests", "bs4.BeautifulSoup", "config" and first party imports "models.Rating", "tests.utils.*"  (wrong-import-order)
tests/energy_efficiency_websitecarbon.py:4:0: W0611: Unused import sys (unused-import)
tests/energy_efficiency_websitecarbon.py:5:0: W0611: Unused import socket (unused-import)
tests/energy_efficiency_websitecarbon.py:6:0: W0611: Unused import ssl (unused-import)
tests/energy_efficiency_websitecarbon.py:8:0: W0611: Unused import requests (unused-import)
tests/energy_efficiency_websitecarbon.py:9:0: W0611: Unused import urllib (unused-import)
tests/energy_efficiency_websitecarbon.py:10:0: W0611: Unused import uuid (unused-import)
tests/energy_efficiency_websitecarbon.py:11:0: W0611: Unused import re (unused-import)
tests/energy_efficiency_websitecarbon.py:12:0: W0611: Unused BeautifulSoup imported from bs4 (unused-import)
tests/energy_efficiency_websitecarbon.py:15:0: W0611: Unused import config (unused-import)
tests/energy_efficiency_websitecarbon.py:16:0: W0614: Unused import(s) hashlib, shutil, time, dns, IP2Location, os, ip2location_db, ex, request_timeout, useragent, googlePageSpeedApiKey, gitHubApiKey, use_cache, cache_time_delta, dns_server, change_url_to_test_url, is_file_older_than, get_cache_path, get_cache_file, has_cache_file, clean_cache_files, set_cache_file, get_content_type, get_url_headers, has_redirect, get_guid, convert_to_seconds, is_sitemap, dns_lookup, dns_response_to_list, get_eu_countries, get_exception_countries, is_country_code_in_eu, is_country_code_in_exception_list, is_country_code_in_eu_or_on_exception_list, get_country_code_from_ip2location, get_best_country_code, get_friendly_url_name, timedelta, Path, ParseResult, urlparse and urlunparse from wildcard import of tests.utils (unused-wildcard-import)

**Comment by 7h3Rabbit** [comment]
tests/energy_efficiency.py:23:0: C0301: Line too long (156/100) (line-too-long)
tests/energy_efficiency.py:35:0: C0301: Line too long (174/100) (line-too-long)
tests/energy_efficiency.py:61:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
tests/energy_efficiency.py:123:0: C0301: Line too long (106/100) (line-too-long)
tests/energy_efficiency.py:125:0: C0301: Line too long (111/100) (line-too-long)
tests/energy_efficiency.py:132:0: C0301: Line too long (101/100) (line-too-long)
tests/energy_efficiency.py:3:0: R0402: Use 'from tests import energy_efficiency_carbon_percentiles' instead (consider-using-from-import)
tests/energy_efficiency.py:22:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/energy_efficiency.py:26:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/energy_efficiency.py:26:23: C0103: Argument name "bytesAdjusted" doesn't conform to snake_case naming style (invalid-name)
tests/energy_efficiency.py:30:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/energy_efficiency.py:38:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/energy_efficiency.py:39:4: C0103: Variable name "bytesAdjusted" doesn't conform to snake_case naming style (invalid-name)
tests/energy_efficiency.py:41:4: C0103: Variable name "co2Grid" doesn't conform to snake_case naming style (invalid-name)
tests/energy_efficiency.py:46:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/energy_efficiency.py:66:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/energy_efficiency.py:104:19: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/energy_efficiency.py:7:0: C0412: Imports from package tests are not grouped (ungrouped-imports)
************* Module tests.energy_efficiency_carbon_percentiles
tests/energy_efficiency_carbon_percentiles.py:3:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
tests/energy_efficiency_carbon_percentiles.py:6:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
tests/energy_efficiency_carbon_percentiles.py:116:0: C0304: Final newline missing (missing-final-newline)
tests/energy_efficiency_carbon_percentiles.py:2:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/energy_efficiency_carbon_percentiles.py:5:0: C0116: Missing function or method docstring (missing-function-docstring)
************* Module tests.energy_efficiency_carbon_percentiles2021
tests/energy_efficiency_carbon_percentiles2021.py:3:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
tests/energy_efficiency_carbon_percentiles2021.py:6:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
tests/energy_efficiency_carbon_percentiles2021.py:116:0: C0304: Final newline missing (missing-final-newline)
tests/energy_efficiency_carbon_percentiles2021.py:2:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/energy_efficiency_carbon_percentiles2021.py:5:0: C0116: Missing function or method docstring (missing-function-docstring)
************* Module tests.energy_efficiency_carbon_percentiles2022
tests/energy_efficiency_carbon_percentiles2022.py:3:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
tests/energy_efficiency_carbon_percentiles2022.py:6:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
tests/energy_efficiency_carbon_percentiles2022.py:116:0: C0304: Final newline missing (missing-final-newline)
tests/energy_efficiency_carbon_percentiles2022.py:2:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/energy_efficiency_carbon_percentiles2022.py:5:0: C0116: Missing function or method docstring (missing-function-docstring)

**Comment by 7h3Rabbit** [comment]
solved and closed
