### ISSUE TITLE
PyLint for Improved Code Quality - tests/http_validator.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#318]
************* Module tests.http_validator
tests/http_validator.py:155:0: C0303: Trailing whitespace (trailing-whitespace)
tests/http_validator.py:160:0: C0301: Line too long (103/100) (line-too-long)
tests/http_validator.py:166:0: C0301: Line too long (106/100) (line-too-long)
tests/http_validator.py:173:0: C0301: Line too long (103/100) (line-too-long)
tests/http_validator.py:179:0: C0301: Line too long (106/100) (line-too-long)
tests/http_validator.py:185:0: C0301: Line too long (103/100) (line-too-long)
tests/http_validator.py:190:0: C0301: Line too long (106/100) (line-too-long)
tests/http_validator.py:196:0: C0301: Line too long (103/100) (line-too-long)
tests/http_validator.py:201:0: C0301: Line too long (106/100) (line-too-long)
tests/http_validator.py:209:0: C0303: Trailing whitespace (trailing-whitespace)
tests/http_validator.py:210:0: C0301: Line too long (101/100) (line-too-long)
tests/http_validator.py:218:0: C0301: Line too long (102/100) (line-too-long)
tests/http_validator.py:221:0: C0301: Line too long (101/100) (line-too-long)
tests/http_validator.py:229:0: C0301: Line too long (102/100) (line-too-long)
tests/http_validator.py:390:0: C0301: Line too long (203/100) (line-too-long)
tests/http_validator.py:391:0: C0301: Line too long (116/100) (line-too-long)
tests/http_validator.py:397:0: C0301: Line too long (103/100) (line-too-long)
tests/http_validator.py:400:0: C0301: Line too long (474/100) (line-too-long)
tests/http_validator.py:401:0: C0301: Line too long (298/100) (line-too-long)
tests/http_validator.py:402:0: C0301: Line too long (162/100) (line-too-long)
tests/http_validator.py:404:0: C0301: Line too long (107/100) (line-too-long)
tests/http_validator.py:405:0: C0301: Line too long (125/100) (line-too-long)
tests/http_validator.py:407:0: C0301: Line too long (113/100) (line-too-long)
tests/http_validator.py:414:0: C0301: Line too long (118/100) (line-too-long)
tests/http_validator.py:420:0: C0301: Line too long (118/100) (line-too-long)
tests/http_validator.py:440:0: C0301: Line too long (124/100) (line-too-long)
tests/http_validator.py:445:0: C0301: Line too long (170/100) (line-too-long)
tests/http_validator.py:453:0: C0301: Line too long (179/100) (line-too-long)
tests/http_validator.py:458:0: C0301: Line too long (179/100) (line-too-long)
tests/http_validator.py:464:0: C0301: Line too long (124/100) (line-too-long)
tests/http_validator.py:471:0: C0301: Line too long (136/100) (line-too-long)
tests/http_validator.py:472:0: C0301: Line too long (149/100) (line-too-long)
tests/http_validator.py:477:0: C0301: Line too long (130/100) (line-too-long)
tests/http_validator.py:478:0: C0301: Line too long (143/100) (line-too-long)
tests/http_validator.py:485:0: C0301: Line too long (136/100) (line-too-long)
tests/http_validator.py:486:0: C0301: Line too long (149/100) (line-too-long)
tests/http_validator.py:492:0: C0301: Line too long (130/100) (line-too-long)
tests/http_validator.py:493:0: C0301: Line too long (143/100) (line-too-long)
tests/http_validator.py:503:0: C0301: Line too long (123/100) (line-too-long)
tests/http_validator.py:2413:4: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:2422:4: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:2425:15: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
tests/http_validator.py:2418:8: W0201: Attribute 'poolmanager' defined outside __init__ (attribute-defined-outside-init)
tests/http_validator.py:2428:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:2442:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2477:11: W0718: Catching too general exception Exception (broad-exception-caught)
tests/http_validator.py:2451:11: R1714: Consider merging these comparisons with 'in' by using 'a.status_code in (200, 301, 302, 404)'. Use a set instead if elements are hashable. (consider-using-in)
tests/http_validator.py:2464:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2467:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2470:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2479:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2428:0: R0911: Too many return statements (9/6) (too-many-return-statements)
tests/http_validator.py:2471:4: W0612: Unused variable 'sslerror' (unused-variable)
tests/http_validator.py:2474:4: W0612: Unused variable 'conex' (unused-variable)
tests/http_validator.py:2482:0: C0115: Missing class docstring (missing-class-docstring)
tests/http_validator.py:2486:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
tests/http_validator.py:2488:4: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:2492:8: W0201: Attribute 'poolmanager' defined outside __init__ (attribute-defined-outside-init)
tests/http_validator.py:2482:0: R0903: Too few public methods (1/2) (too-few-public-methods)
tests/http_validator.py:2497:0: C0115: Missing class docstring (missing-class-docstring)
tests/http_validator.py:2501:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
tests/http_validator.py:2503:4: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:2508:8: W0201: Attribute 'poolmanager' defined outside __init__ (attribute-defined-outside-init)
tests/http_validator.py:2497:0: R0903: Too few public methods (1/2) (too-few-public-methods)
tests/http_validator.py:2513:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:2555:11: W0718: Catching too general exception Exception (broad-exception-caught)
tests/http_validator.py:2533:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
tests/http_validator.py:2534:26: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2536:27: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2539:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2542:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2545:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2548:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2557:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2513:0: R0911: Too many return statements (10/6) (too-many-return-statements)
tests/http_validator.py:2549:4: W0612: Unused variable 'sslerror' (unused-variable)
tests/http_validator.py:2552:4: W0612: Unused variable 'conex' (unused-variable)
tests/http_validator.py:15:0: C0411: standard import "urllib" should be placed before third party imports "requests", "requests.adapters.HTTPAdapter", "requests.packages.urllib3.poolmanager.PoolManager", "requests.packages.urllib3.util.ssl_" (wrong-import-order)
tests/http_validator.py:21:0: C0411: third party import "dns.name" should be placed before first party imports "models.Rating", "tests.utils.dns_lookup", "tests.utils.*", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/http_validator.py:22:0: C0411: third party import "dns.query" should be placed before first party imports "models.Rating", "tests.utils.dns_lookup", "tests.utils.*", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/http_validator.py:23:0: C0411: third party import "dns.dnssec" should be placed before first party imports "models.Rating", "tests.utils.dns_lookup", "tests.utils.*", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/http_validator.py:24:0: C0411: third party import "dns.message" should be placed before first party imports "models.Rating", "tests.utils.dns_lookup", "tests.utils.*", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/http_validator.py:25:0: C0411: third party import "dns.resolver" should be placed before first party imports "models.Rating", "tests.utils.dns_lookup", "tests.utils.*", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/http_validator.py:26:0: C0411: third party import "dns.rdatatype" should be placed before first party imports "models.Rating", "tests.utils.dns_lookup", "tests.utils.*", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/http_validator.py:27:0: C0411: standard import "hashlib" should be placed before third party imports "requests", "requests.adapters.HTTPAdapter", "requests.packages.urllib3.poolmanager.PoolManager" (...) "dns.message", "dns.resolver", "dns.rdatatype" and first party imports "models.Rating", "tests.utils.dns_lookup", "tests.utils.*", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/http_validator.py:28:0: C0411: standard import "base64" should be placed before third party imports "requests", "requests.adapters.HTTPAdapter", "requests.packages.urllib3.poolmanager.PoolManager" (...) "dns.message", "dns.resolver", "dns.rdatatype" and first party imports "models.Rating", "tests.utils.dns_lookup", "tests.utils.*", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/http_validator.py:29:0: C0411: standard import "datetime" should be placed before third party imports "requests", "requests.adapters.HTTPAdapter", "requests.packages.urllib3.poolmanager.PoolManager" (...) "dns.message", "dns.resolver", "dns.rdatatype" and first party imports "models.Rating", "tests.utils.dns_lookup", "tests.utils.*", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/http_validator.py:30:0: C0411: standard import "gettext" should be placed before third party imports "requests", "requests.adapters.HTTPAdapter", "requests.packages.urllib3.poolmanager.PoolManager" (...) "dns.message", "dns.resolver", "dns.rdatatype" and first party imports "models.Rating", "tests.utils.dns_lookup", "tests.utils.*", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/http_validator.py:6:0: C0412: Imports from package datetime are not grouped (ungrouped-imports)
tests/http_validator.py:15:0: C0412: Imports from package urllib are not grouped (ungrouped-imports)
tests/http_validator.py:29:0: C0412: Imports from package datetime are not grouped (ungrouped-imports)
tests/http_validator.py:19:0: W0614: Unused import(s) use_cache, cache_time_delta, shutil, socket, time, uuid, IP2Location, ip2location_db, ex, googlePageSpeedApiKey, gitHubApiKey, dns_server, is_file_older_than, get_cache_path, get_cache_file, has_cache_file, clean_cache_files, set_cache_file, httpRequestGetContent, get_content_type, get_url_headers, has_redirect, get_guid, convert_to_seconds, is_sitemap, dns_response_to_list, get_eu_countries, get_exception_countries, is_country_code_in_eu, is_country_code_in_exception_list, is_country_code_in_eu_or_on_exception_list, get_country_code_from_ip2location, get_best_country_code, get_friendly_url_name, Path, BeautifulSoup, ParseResult, urlparse and urlunparse from wildcard import of tests.utils (unused-wildcard-import)

**Comment by 7h3Rabbit** [comment]
tests/http_validator.py:16:0: C0301: Line too long (111/100) (line-too-long)
tests/http_validator.py:115:0: C0301: Line too long (103/100) (line-too-long)
tests/http_validator.py:117:0: C0301: Line too long (102/100) (line-too-long)
tests/http_validator.py:118:0: C0301: Line too long (120/100) (line-too-long)
tests/http_validator.py:126:0: C0303: Trailing whitespace (trailing-whitespace)
tests/http_validator.py:130:0: C0301: Line too long (101/100) (line-too-long)
tests/http_validator.py:131:0: C0301: Line too long (114/100) (line-too-long)
tests/http_validator.py:136:0: C0301: Line too long (104/100) (line-too-long)
tests/http_validator.py:137:0: C0301: Line too long (117/100) (line-too-long)
tests/http_validator.py:2021:4: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
tests/http_validator.py:2050:19: C0121: Comparison 'scheme != None' should be 'scheme is not None' (singleton-comparison)
tests/http_validator.py:2017:0: R0912: Too many branches (16/12) (too-many-branches)
tests/http_validator.py:2060:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:2101:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:2104:8: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
tests/http_validator.py:2114:44: R1714: Consider merging these comparisons with 'in' by using 'policy_name in ('frame-ancestors', 'report-uri', 'sandbox')'. Use a set instead if elements are hashable. (consider-using-in)
tests/http_validator.py:2116:51: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2104:8: W0612: Unused variable 'matchNum' (unused-variable)
tests/http_validator.py:2123:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:2133:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:2237:0: C0115: Missing class docstring (missing-class-docstring)
tests/http_validator.py:2241:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
tests/http_validator.py:2255:15: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
tests/http_validator.py:2258:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:2272:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2307:11: W0718: Catching too general exception Exception (broad-exception-caught)
tests/http_validator.py:2281:11: R1714: Consider merging these comparisons with 'in' by using 'a.status_code in (200, 301, 302, 404)'. Use a set instead if elements are hashable. (consider-using-in)
tests/http_validator.py:2294:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2297:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2300:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2309:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2258:0: R0[911](https://github.com/Webperf-se/webperf_core/actions/runs/8588845582/job/23534216988#step:6:912): Too many return statements (9/6) (too-many-return-statements)
tests/http_validator.py:2301:4: W0612: Unused variable 'sslerror' (unused-variable)
tests/http_validator.py:2304:4: W0612: Unused variable 'conex' (unused-variable)
tests/http_validator.py:2325:0: C0115: Missing class docstring (missing-class-docstring)
tests/http_validator.py:2329:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
tests/http_validator.py:2343:15: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
tests/http_validator.py:2346:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:2360:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2395:11: W0718: Catching too general exception Exception (broad-exception-caught)
tests/http_validator.py:2369:11: R1714: Consider merging these comparisons with 'in' by using 'a.status_code in (200, 301, 302, 404)'. Use a set instead if elements are hashable. (consider-using-in)
tests/http_validator.py:2382:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2385:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2388:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2397:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2346:0: R0911: Too many return statements (9/6) (too-many-return-statements)
tests/http_validator.py:2389:4: W0612: Unused variable 'sslerror' (unused-variable)
tests/http_validator.py:2392:4: W0612: Unused variable 'conex' (unused-variable)
tests/http_validator.py:2400:0: C0115: Missing class docstring (missing-class-docstring)
tests/http_validator.py:2404:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
tests/http_validator.py:2415:0: C0115: Missing class docstring (missing-class-docstring)
tests/http_validator.py:2419:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
tests/http_validator.py:2431:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:2473:11: W0718: Catching too general exception Exception (broad-exception-caught)
tests/http_validator.py:2451:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
tests/http_validator.py:2452:26: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2454:27: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2457:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2460:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2463:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2466:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2475:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:2431:0: R0911: Too many return statements (10/6) (too-many-return-statements)
tests/http_validator.py:2467:4: W0612: Unused variable 'sslerror' (unused-variable)
tests/http_validator.py:2470:4: W0612: Unused variable 'conex' (unused-variable)
tests/http_validator.py:14:0: C0411: standard import "urllib" should be placed before third party imports "requests", "requests.adapters.HTTPAdapter", "requests.packages.urllib3.poolmanager.PoolManager", "requests.packages.urllib3.util.ssl_" (wrong-import-order)
tests/http_validator.py:18:0: C0411: third party import "dns.name" should be placed before first party imports "models.Rating", "tests.utils.change_url_to_test_url", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/http_validator.py:19:0: C0411: third party import "dns.query" should be placed before first party imports "models.Rating", "tests.utils.change_url_to_test_url", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/http_validator.py:20:0: C0411: third party import "dns.dnssec" should be placed before first party imports "models.Rating", "tests.utils.change_url_to_test_url", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/http_validator.py:21:0: C0411: third party import "dns.message" should be placed before first party imports "models.Rating", "tests.utils.change_url_to_test_url", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/http_validator.py:22:0: C0411: third party import "dns.resolver" should be placed before first party imports "models.Rating", "tests.utils.change_url_to_test_url", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/http_validator.py:23:0: C0411: third party import "dns.rdatatype" should be placed before first party imports "models.Rating", "tests.utils.change_url_to_test_url", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/http_validator.py:24:0: C0411: standard import "hashlib" should be placed before third party imports "requests", "requests.adapters.HTTPAdapter", "requests.packages.urllib3.poolmanager.PoolManager" (...) "dns.message", "dns.resolver", "dns.rdatatype" and first party imports "models.Rating", "tests.utils.change_url_to_test_url", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/http_validator.py:25:0: C0411: standard import "base64" should be placed before third party imports "requests", "requests.adapters.HTTPAdapter", "requests.packages.urllib3.poolmanager.PoolManager" (...) "dns.message", "dns.resolver", "dns.rdatatype" and first party imports "models.Rating", "tests.utils.change_url_to_test_url", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/http_validator.py:14:0: C0412: Imports from package urllib are not grouped (ungrouped-imports)

**Comment by 7h3Rabbit** [comment]
************* Module tests.http_validator
tests/http_validator.py:2:0: C0302: Too many lines in module (2053/1000) (too-many-lines)
tests/http_validator.py:405:5: W0511: TODO: We should check if X-Frame-Options is used and (fixme)
tests/http_validator.py:552:17: W0511: TODO: Validate correct format ( '<hash-algorithm>-<base64-value>' ) (fixme)
tests/http_validator.py:577:17: W0511: TODO: we should check nonce length as it should not be guessable. (fixme)
tests/http_validator.py:1598:5: W0511: TODO: check cipher security (fixme)
tests/http_validator.py:1599:5: W0511: TODO: re add support for identify wrong certificate (fixme)
tests/http_validator.py:13:0: E0401: Unable to import 'requests.packages.urllib3.poolmanager' (import-error)
tests/http_validator.py:14:0: E0401: Unable to import 'requests.packages.urllib3.util' (import-error)
tests/http_validator.py:48:4: W0603: Using the global statement (global-statement)
tests/http_validator.py:98:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:145:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:211:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:245:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:245:0: R0914: Too many local variables (18/15) (too-many-locals)
tests/http_validator.py:245:0: R0912: Too many branches (43/12) (too-many-branches)
tests/http_validator.py:245:0: R0915: Too many statements (125/50) (too-many-statements)
tests/http_validator.py:396:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:396:0: R0913: Too many arguments (7/5) (too-many-arguments)
tests/http_validator.py:396:0: R0914: Too many local variables (38/15) (too-many-locals)
tests/http_validator.py:402:7: R1714: Consider merging these comparisons with 'in' by using 'domain not in (org_domain, org_www_domain)'. Use a set instead if elements are hashable. (consider-using-in)
tests/http_validator.py:808:13: R1714: Consider merging these comparisons with 'in' by using 'domain in (org_domain, org_www_domain)'. Use a set instead if elements are hashable. (consider-using-in)
tests/http_validator.py:396:0: R0912: Too many branches (59/12) (too-many-branches)
tests/http_validator.py:396:0: R0915: Too many statements (273/50) (too-many-statements)
tests/http_validator.py:438:8: W0612: Unused variable 'other_supported_polices' (unused-variable)
tests/http_validator.py:442:8: W0612: Unused variable 'experimental_policies' (unused-variable)
tests/http_validator.py:880:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:880:0: R0912: Too many branches (14/12) (too-many-branches)
tests/http_validator.py:880:0: R0915: Too many statements (51/50) (too-many-statements)
tests/http_validator.py:954:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:993:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1038:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1050:16: W0612: Unused variable 'a' (unused-variable)
tests/http_validator.py:1056:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1065:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1076:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1076:0: R0914: Too many local variables (37/15) (too-many-locals)
tests/http_validator.py:1092:8: R1702: Too many nested blocks (7/5) (too-many-nested-blocks)
tests/http_validator.py:1092:8: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
tests/http_validator.py:1092:8: R1702: Too many nested blocks (7/5) (too-many-nested-blocks)
tests/http_validator.py:1092:8: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
tests/http_validator.py:1265:27: R1714: Consider merging these comparisons with 'in' by using 'element_name in ('style', 'script')'. Use a set instead if elements are hashable. (consider-using-in)
tests/http_validator.py:1092:8: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
tests/http_validator.py:1092:8: R1702: Too many nested blocks (7/5) (too-many-nested-blocks)
tests/http_validator.py:1321:30: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:1092:8: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
tests/http_validator.py:1076:0: R0912: Too many branches (91/12) (too-many-branches)
tests/http_validator.py:1076:0: R0915: Too many statements (248/50) (too-many-statements)
tests/http_validator.py:1405:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1411:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1431:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1431:0: R0912: Too many branches (15/12) (too-many-branches)
tests/http_validator.py:1510:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1534:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1584:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1603:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1640:20: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/http_validator.py:1652:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1664:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1677:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1696:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1713:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1713:0: R0912: Too many branches (15/12) (too-many-branches)
tests/http_validator.py:1763:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1804:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1835:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1845:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:[19](https://github.com/Webperf-se/webperf_core/actions/runs/8861949583/job/24334366228#step:6:20)46:0: C0115: Missing class docstring (missing-class-docstring)
tests/http_validator.py:1950:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
tests/http_validator.py:1964:15: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
tests/http_validator.py:1967:0: C0115: Missing class docstring (missing-class-docstring)
tests/http_validator.py:1971:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
tests/http_validator.py:1982:0: C0115: Missing class docstring (missing-class-docstring)
tests/http_validator.py:1986:8: R17[25](https://github.com/Webperf-se/webperf_core/actions/runs/8861949583/job/24334366228#step:6:26): Consider using Python 3 style super() without arguments (super-with-arguments)
tests/http_validator.py:1998:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/http_validator.py:1998:0: R0911: Too many return statements (11/6) (too-many-return-statements)
