### ISSUE TITLE
PyLint for Improved Code Quality - tests/page_not_found.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#320]
************* Module tests.page_not_found
tests/page_not_found.py:31:0: C0301: Line too long (118/100) (line-too-long)
tests/page_not_found.py:57:0: C0301: Line too long (113/100) (line-too-long)
tests/page_not_found.py:1:0: C0114: Missing module docstring (missing-module-docstring)
tests/page_not_found.py:6:0: E0401: Unable to import 'requests' (import-error)
tests/page_not_found.py:8:0: E0401: Unable to import 'bs4' (import-error)
tests/page_not_found.py:9:0: E0401: Unable to import 'config' (import-error)
tests/page_not_found.py:10:0: W0401: Wildcard import tests.utils (wildcard-import)
tests/page_not_found.py:20:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/page_not_found.py:24:11: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/page_not_found.py:27:19: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/page_not_found.py:29:19: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/page_not_found.py:36:16: C0103: Argument name "langCode" doesn't conform to snake_case naming style (invalid-name)
tests/page_not_found.py:36:0: R0914: Too many local variables (22/15) (too-many-locals)
tests/page_not_found.py:65:11: W0718: Catching too general exception Exception (broad-exception-caught)
tests/page_not_found.py:72:4: C0103: Variable name "requestText" doesn't conform to snake_case naming style (invalid-name)
tests/page_not_found.py:73:4: C0103: Variable name "hasRequestText" doesn't conform to snake_case naming style (invalid-name)
tests/page_not_found.py:76:7: C0121: Comparison 'request != False' should be 'request is not False' if checking for the singleton value False, or 'request' if testing for truthiness (singleton-comparison)
tests/page_not_found.py:78:12: C0103: Variable name "requestText" doesn't conform to snake_case naming style (invalid-name)
tests/page_not_found.py:79:12: C0103: Variable name "hasRequestText" doesn't conform to snake_case naming style (invalid-name)
tests/page_not_found.py:98:12: W0702: No exception type(s) specified (bare-except)
tests/page_not_found.py:100:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/page_not_found.py:36:0: R0912: Too many branches (13/12) (too-many-branches)
tests/page_not_found.py:36:0: R0915: Too many statements (64/50) (too-many-statements)
tests/page_not_found.py:151:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/page_not_found.py:165:4: W0702: No exception type(s) specified (bare-except)
tests/page_not_found.py:166:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/page_not_found.py:170:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/page_not_found.py:184:4: W0702: No exception type(s) specified (bare-except)
tests/page_not_found.py:185:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/page_not_found.py:193:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/page_not_found.py:209:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/page_not_found.py:218:4: W0702: No exception type(s) specified (bare-except)
tests/page_not_found.py:214:12: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
tests/page_not_found.py:219:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/page_not_found.py:224:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/page_not_found.py:225:4: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
tests/page_not_found.py:231:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/page_not_found.py:231:0: R0915: Too many statements (54/50) (too-many-statements)
tests/page_not_found.py:364:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/page_not_found.py:4:0: C0411: standard import "datetime" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/page_not_found.py:5:0: C0411: standard import "sys" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/page_not_found.py:6:0: C0411: third party import "requests" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/page_not_found.py:7:0: C0411: standard import "urllib" should be placed before third party import "requests" and first party import "models.Rating"  (wrong-import-order)
tests/page_not_found.py:8:0: C0411: third party import "bs4.BeautifulSoup" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/page_not_found.py:9:0: C0411: third party import "config" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/page_not_found.py:11:0: C0411: standard import "gettext" should be placed before third party imports "requests", "bs4.BeautifulSoup", "config" and first party imports "models.Rating", "tests.utils.*"  (wrong-import-order)
tests/page_not_found.py:10:0: W0614: Unused import(s) hashlib, shutil, socket, ssl, json, time, uuid, re, dns, IP2Location, os, ip2location_db, ex, googlePageSpeedApiKey, gitHubApiKey, use_cache, cache_time_delta, dns_server, change_url_to_test_url, is_file_older_than, get_cache_path, get_cache_file, has_cache_file, clean_cache_files, set_cache_file, get_content_type, get_url_headers, has_redirect, convert_to_seconds, is_sitemap, dns_lookup, dns_response_to_list, get_eu_countries, get_exception_countries, is_country_code_in_eu, is_country_code_in_exception_list, is_country_code_in_eu_or_on_exception_list, get_country_code_from_ip2location, get_best_country_code, get_friendly_url_name, timedelta, Path and urlparse from wildcard import of tests.utils (unused-wildcard-import)

**Comment by 7h3Rabbit** [comment]
tests/page_not_found.py:27:0: C0301: Line too long (118/100) (line-too-long)
tests/page_not_found.py:50:0: C0301: Line too long (113/100) (line-too-long)
tests/page_not_found.py:16:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/page_not_found.py:20:11: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/page_not_found.py:23:19: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/page_not_found.py:25:19: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/page_not_found.py:32:0: R0914: Too many local variables (23/15) (too-many-locals)
tests/page_not_found.py:58:11: W0718: Catching too general exception Exception (broad-exception-caught)
tests/page_not_found.py:65:4: C0103: Variable name "requestText" doesn't conform to snake_case naming style (invalid-name)
tests/page_not_found.py:66:4: C0103: Variable name "hasRequestText" doesn't conform to snake_case naming style (invalid-name)
tests/page_not_found.py:69:7: C0121: Comparison 'request != False' should be 'request is not False' if checking for the singleton value False, or 'request' if testing for truthiness (singleton-comparison)
tests/page_not_found.py:71:12: C0103: Variable name "requestText" doesn't conform to snake_case naming style (invalid-name)
tests/page_not_found.py:72:12: C0103: Variable name "hasRequestText" doesn't conform to snake_case naming style (invalid-name)
tests/page_not_found.py:91:12: W0702: No exception type(s) specified (bare-except)
tests/page_not_found.py:93:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/page_not_found.py:32:0: R0912: Too many branches (13/12) (too-many-branches)
tests/page_not_found.py:32:0: R0915: Too many statements (62/50) (too-many-statements)
tests/page_not_found.py:144:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/page_not_found.py:158:4: W0702: No exception type(s) specified (bare-except)
tests/page_not_found.py:159:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/page_not_found.py:163:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/page_not_found.py:177:4: W0702: No exception type(s) specified (bare-except)
tests/page_not_found.py:178:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/page_not_found.py:186:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/page_not_found.py:202:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/page_not_found.py:211:4: W0702: No exception type(s) specified (bare-except)
tests/page_not_found.py:207:12: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
tests/page_not_found.py:212:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/page_not_found.py:217:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/page_not_found.py:218:4: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
tests/page_not_found.py:224:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/page_not_found.py:224:0: R0915: Too many statements (54/50) (too-many-statements)
tests/page_not_found.py:357:0: C0116: Missing function or method docstring (missing-function-docstring)
