### ISSUE TITLE
PyLint for Improved Code Quality - tests/privacy_webbkollen.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#323]
************* Module tests.privacy_webbkollen
tests/privacy_webbkollen.py:107:0: C0301: Line too long (153/100) (line-too-long)
tests/privacy_webbkollen.py:1:0: C0114: Missing module docstring (missing-module-docstring)
tests/privacy_webbkollen.py:8:0: E0401: Unable to import 'requests' (import-error)
tests/privacy_webbkollen.py:13:0: E0401: Unable to import 'bs4' (import-error)
tests/privacy_webbkollen.py:14:0: E0401: Unable to import 'config' (import-error)
tests/privacy_webbkollen.py:15:0: W0401: Wildcard import tests.utils (wildcard-import)
tests/privacy_webbkollen.py:21:0: C0103: Constant name "regex_allowed_chars" doesn't conform to UPPER_CASE naming style (invalid-name)
tests/privacy_webbkollen.py:25:0: R1731: Consider using 'time_sleep = max(time_sleep, 5)' instead of unnecessary if block (consider-using-max-builtin)
tests/privacy_webbkollen.py:26:4: C0103: Constant name "time_sleep" doesn't conform to UPPER_CASE naming style (invalid-name)
tests/privacy_webbkollen.py:30:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/privacy_webbkollen.py:30:16: C0103: Argument name "langCode" doesn't conform to snake_case naming style (invalid-name)
tests/privacy_webbkollen.py:30:0: R0914: Too many local variables (44/15) (too-many-locals)
tests/privacy_webbkollen.py:31:4: W0621: Redefining name 'time' from outer scope (line 15) (redefined-outer-name)
tests/privacy_webbkollen.py:31:4: C0415: Import outside toplevel (time) (import-outside-toplevel)
tests/privacy_webbkollen.py:34:18: R1735: Consider using '{}' instead of a call to 'dict'. (use-dict-literal)
tests/privacy_webbkollen.py:48:10: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/privacy_webbkollen.py:61:11: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/privacy_webbkollen.py:66:16: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
tests/privacy_webbkollen.py:73:26: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/privacy_webbkollen.py:107:11: R1714: Consider merging these comparisons with 'in' by using 'header_id in ('what', 'raw-headers', 'server-location', 'localstorage', 'requests')'. Use a set instead if elements are hashable. (consider-using-in)
tests/privacy_webbkollen.py:156:8: R1731: Consider using 'points_for_current_result = max(points_for_current_result, 1.0)' instead of unnecessary if block (consider-using-max-builtin)
tests/privacy_webbkollen.py:180:13: R1714: Consider merging these comparisons with 'in' by using 'header_id in ('headers', 'cookies')'. Use a set instead if elements are hashable. (consider-using-in)
tests/privacy_webbkollen.py:30:0: R0912: Too many branches (31/12) (too-many-branches)
tests/privacy_webbkollen.py:30:0: R0915: Too many statements (115/50) (too-many-statements)
tests/privacy_webbkollen.py:66:16: W0612: Unused variable 'matchNum' (unused-variable)
tests/privacy_webbkollen.py:3:0: C0411: standard import "datetime.datetime" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/privacy_webbkollen.py:4:0: C0411: standard import "sys" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/privacy_webbkollen.py:5:0: C0411: standard import "socket" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/privacy_webbkollen.py:6:0: C0411: standard import "ssl" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/privacy_webbkollen.py:7:0: C0411: standard import "json" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/privacy_webbkollen.py:8:0: C0411: third party import "requests" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/privacy_webbkollen.py:9:0: C0411: standard import "urllib" should be placed before third party import "requests" and first party import "models.Rating"  (wrong-import-order)
tests/privacy_webbkollen.py:10:0: C0411: standard import "urllib.parse.urlparse" should be placed before third party import "requests" and first party import "models.Rating"  (wrong-import-order)
tests/privacy_webbkollen.py:11:0: C0411: standard import "uuid" should be placed before third party import "requests" and first party import "models.Rating"  (wrong-import-order)
tests/privacy_webbkollen.py:12:0: C0411: standard import "re" should be placed before third party import "requests" and first party import "models.Rating"  (wrong-import-order)
tests/privacy_webbkollen.py:13:0: C0411: third party import "bs4.BeautifulSoup" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/privacy_webbkollen.py:14:0: C0411: third party import "config" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/privacy_webbkollen.py:16:0: C0411: standard import "gettext" should be placed before third party imports "requests", "bs4.BeautifulSoup", "config" and first party imports "models.Rating", "tests.utils.*"  (wrong-import-order)
tests/privacy_webbkollen.py:4:0: W0611: Unused import sys (unused-import)
tests/privacy_webbkollen.py:5:0: W0611: Unused import socket (unused-import)
tests/privacy_webbkollen.py:6:0: W0611: Unused import ssl (unused-import)
tests/privacy_webbkollen.py:7:0: W0611: Unused import json (unused-import)
tests/privacy_webbkollen.py:10:0: W0611: Unused urlparse imported from urllib.parse (unused-import)
tests/privacy_webbkollen.py:11:0: W0611: Unused import uuid (unused-import)
tests/privacy_webbkollen.py:15:0: W0614: Unused import(s) useragent, hashlib, shutil, time, dns, IP2Location, os, ip2location_db, ex, googlePageSpeedApiKey, gitHubApiKey, use_cache, cache_time_delta, dns_server, change_url_to_test_url, is_file_older_than, get_cache_path, get_cache_file, has_cache_file, clean_cache_files, set_cache_file, httpRequestGetContent, get_content_type, get_url_headers, has_redirect, get_guid, convert_to_seconds, is_sitemap, dns_lookup, dns_response_to_list, get_eu_countries, get_exception_countries, is_country_code_in_eu, is_country_code_in_exception_list, is_country_code_in_eu_or_on_exception_list, get_country_code_from_ip2location, get_best_country_code, get_friendly_url_name, timedelta, Path, ParseResult and urlunparse from wildcard import of tests.utils (unused-wildcard-import)

**Comment by 7h3Rabbit** [comment]
tests/privacy_webbkollen.py:94:0: C0301: Line too long (153/100) (line-too-long)
tests/privacy_webbkollen.py:13:0: C0103: Constant name "regex_allowed_chars" doesn't conform to UPPER_CASE naming style (invalid-name)
tests/privacy_webbkollen.py:17:0: R1731: Consider using 'time_sleep = max(time_sleep, 5)' instead of unnecessary if block (consider-using-max-builtin)
tests/privacy_webbkollen.py:18:4: C0103: Constant name "time_sleep" doesn't conform to UPPER_CASE naming style (invalid-name)
tests/privacy_webbkollen.py:21:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/privacy_webbkollen.py:21:0: R0914: Too many local variables (43/15) (too-many-locals)
tests/privacy_webbkollen.py:35:10: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/privacy_webbkollen.py:48:11: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/privacy_webbkollen.py:60:26: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/privacy_webbkollen.py:94:11: R1714: Consider merging these comparisons with 'in' by using 'header_id in ('what', 'raw-headers', 'server-location', 'localstorage', 'requests')'. Use a set instead if elements are hashable. (consider-using-in)
tests/privacy_webbkollen.py:143:8: R1731: Consider using 'points_for_current_result = max(points_for_current_result, 1.0)' instead of unnecessary if block (consider-using-max-builtin)
tests/privacy_webbkollen.py:167:13: R1714: Consider merging these comparisons with 'in' by using 'header_id in ('headers', 'cookies')'. Use a set instead if elements are hashable. (consider-using-in)
tests/privacy_webbkollen.py:21:0: R0912: Too many branches (31/12) (too-many-branches)
tests/privacy_webbkollen.py:21:0: R0915: Too many statements (112/50) (too-many-statements)

**Comment by 7h3Rabbit** [comment]
************* Module tests.privacy_webbkollen
tests/privacy_webbkollen.py:19:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/privacy_webbkollen.py:19:0: R0914: Too many local variables (27/15) (too-many-locals)
tests/privacy_webbkollen.py:19:0: R0912: Too many branches (16/12) (too-many-branches)
tests/privacy_webbkollen.py:19:0: R0915: Too many statements (60/50) (too-many-statements)
tests/privacy_webbkollen.py:121:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/privacy_webbkollen.py:121:0: R0914: Too many local variables (20/15) (too-many-locals)
tests/privacy_webbkollen.py:121:0: R0912: Too many branches (14/12) (too-many-branches)
tests/privacy_webbkollen.py:121:0: R0915: Too many statements (52/50) (too-many-statements)

**Comment by 7h3Rabbit** [comment]
solved and closed
