### ISSUE TITLE
PyLint for Improved Code Quality - tests/sitespeed_base.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#326]
************* Module tests.sitespeed_base
tests/sitespeed_base.py:18:0: C0303: Trailing whitespace (trailing-whitespace)
tests/sitespeed_base.py:19:0: C0301: Line too long (118/100) (line-too-long)
tests/sitespeed_base.py:36:0: C0301: Line too long (143/100) (line-too-long)
tests/sitespeed_base.py:59:0: C0301: Line too long (103/100) (line-too-long)
tests/sitespeed_base.py:90:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
tests/sitespeed_base.py:117:0: C0301: Line too long (126/100) (line-too-long)
tests/sitespeed_base.py:132:0: C0301: Line too long (101/100) (line-too-long)
tests/sitespeed_base.py:136:0: C0301: Line too long (111/100) (line-too-long)
tests/sitespeed_base.py:143:0: C0303: Trailing whitespace (trailing-whitespace)
tests/sitespeed_base.py:152:0: C0301: Line too long (101/100) (line-too-long)
tests/sitespeed_base.py:217:0: C0301: Line too long (112/100) (line-too-long)
tests/sitespeed_base.py:256:0: C0303: Trailing whitespace (trailing-whitespace)
tests/sitespeed_base.py:261:0: C0303: Trailing whitespace (trailing-whitespace)
tests/sitespeed_base.py:31:5: W0511: TODO: CHANGE THIS IF YOU WANT TO DEBUG (fixme)
tests/sitespeed_base.py:1:0: C0114: Missing module docstring (missing-module-docstring)
tests/sitespeed_base.py:6:0: E0401: Unable to import 'config' (import-error)
tests/sitespeed_base.py:7:0: W0401: Wildcard import tests.utils (wildcard-import)
tests/sitespeed_base.py:12:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:23:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:23:0: R0914: Too many local variables (25/15) (too-many-locals)
tests/sitespeed_base.py:23:20: W0621: Redefining name 'sitespeed_use_docker' from outer scope (line 10) (redefined-outer-name)
tests/sitespeed_base.py:45:8: W0622: Redefining built-in 'input' (redefined-builtin)
tests/sitespeed_base.py:32:56: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/sitespeed_base.py:36:21: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/sitespeed_base.py:45:8: C0415: Import outside toplevel (engines.sitespeed_result) (import-outside-toplevel)
tests/sitespeed_base.py:59:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/sitespeed_base.py:62:4: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
tests/sitespeed_base.py:72:12: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
tests/sitespeed_base.py:79:12: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
tests/sitespeed_base.py:86:19: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/sitespeed_base.py:87:23: E1101: Module 'json' has no 'loads' member (no-member)
tests/sitespeed_base.py:88:24: E1101: Module 'json' has no 'loads' member (no-member)
tests/sitespeed_base.py:90:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
tests/sitespeed_base.py:72:12: W0612: Unused variable 'matchNum' (unused-variable)
tests/sitespeed_base.py:99:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:100:19: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/sitespeed_base.py:104:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:104:30: W0621: Redefining name 'sitespeed_use_docker' from outer scope (line 10) (redefined-outer-name)
tests/sitespeed_base.py:111:12: W0622: Redefining built-in 'dir' (redefined-builtin)
tests/sitespeed_base.py:117:12: C0103: Variable name "bashCommand" doesn't conform to snake_case naming style (invalid-name)
tests/sitespeed_base.py:117:26: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/sitespeed_base.py:120:12: C0415: Import outside toplevel (subprocess) (import-outside-toplevel)
tests/sitespeed_base.py:124:15: C0121: Comparison 'error != None' should be 'error is not None' (singleton-comparison)
tests/sitespeed_base.py:134:12: C0415: Import outside toplevel (subprocess) (import-outside-toplevel)
tests/sitespeed_base.py:136:12: C0103: Variable name "bashCommand" doesn't conform to snake_case naming style (invalid-name)
tests/sitespeed_base.py:136:26: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/sitespeed_base.py:144:15: C0121: Comparison 'error != None' should be 'error is not None' (singleton-comparison)
tests/sitespeed_base.py:154:11: C0121: Comparison 'process != None' should be 'process is not None' (singleton-comparison)
tests/sitespeed_base.py:139:22: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
tests/sitespeed_base.py:161:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:162:12: R1734: Consider using [] instead of list() (use-list-literal)
tests/sitespeed_base.py:168:4: W0702: No exception type(s) specified (bare-except)
tests/sitespeed_base.py:169:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/sitespeed_base.py:181:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:183:18: E1101: Module 'json' has no 'loads' member (no-member)
tests/sitespeed_base.py:205:29: R1734: Consider using [] instead of list() (use-list-literal)
tests/sitespeed_base.py:215:29: R1734: Consider using [] instead of list() (use-list-literal)
tests/sitespeed_base.py:217:19: R1714: Consider merging these comparisons with 'in' by using 'key not in ('request', 'response', 'serverIPAddress', 'httpVersion')'. Use a set instead if elements are hashable. (consider-using-in)
tests/sitespeed_base.py:223:29: R1734: Consider using [] instead of list() (use-list-literal)
tests/sitespeed_base.py:231:29: R1734: Consider using [] instead of list() (use-list-literal)
tests/sitespeed_base.py:233:19: R1714: Consider merging these comparisons with 'in' by using 'key not in ('content', 'headers', 'httpVersion')'. Use a set instead if elements are hashable. (consider-using-in)
tests/sitespeed_base.py:181:0: R0912: Too many branches (21/12) (too-many-branches)
tests/sitespeed_base.py:245:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:247:8: E1101: Module 'json' has no 'dump' member (no-member)
tests/sitespeed_base.py:249:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:7:0: W0614: Unused import(s) request_timeout, hashlib, sys, socket, ssl, requests, dns, IP2Location, ip2location_db, ex, useragent, googlePageSpeedApiKey, gitHubApiKey, dns_server, change_url_to_test_url, get_cache_path, get_cache_file, has_cache_file, clean_cache_files, set_cache_file, httpRequestGetContent, get_content_type, get_url_headers, has_redirect, get_guid, convert_to_seconds, is_sitemap, dns_lookup, dns_response_to_list, get_eu_countries, get_exception_countries, is_country_code_in_eu, is_country_code_in_exception_list, is_country_code_in_eu_or_on_exception_list, get_country_code_from_ip2location, get_best_country_code, get_friendly_url_name, datetime, timedelta and BeautifulSoup from wildcard import of tests.utils (unused-wildcard-import)

**Comment by 7h3Rabbit** [comment]
tests/sitespeed_base.py:26:0: C0301: Line too long (118/100) (line-too-long)
tests/sitespeed_base.py:43:0: C0301: Line too long (143/100) (line-too-long)
tests/sitespeed_base.py:66:0: C0301: Line too long (103/100) (line-too-long)
tests/sitespeed_base.py:97:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
tests/sitespeed_base.py:124:0: C0301: Line too long (122/100) (line-too-long)
tests/sitespeed_base.py:139:0: C0301: Line too long (101/100) (line-too-long)
tests/sitespeed_base.py:143:0: C0301: Line too long (107/100) (line-too-long)
tests/sitespeed_base.py:150:0: C0303: Trailing whitespace (trailing-whitespace)
tests/sitespeed_base.py:159:0: C0301: Line too long (101/100) (line-too-long)
tests/sitespeed_base.py:224:0: C0301: Line too long (112/100) (line-too-long)
tests/sitespeed_base.py:38:5: W0511: TODO: CHANGE THIS IF YOU WANT TO DEBUG (fixme)
tests/sitespeed_base.py:19:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:30:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:30:0: R0914: Too many local variables (24/15) (too-many-locals)
tests/sitespeed_base.py:30:20: W0621: Redefining name 'sitespeed_use_docker' from outer scope (line 15) (redefined-outer-name)
tests/sitespeed_base.py:52:8: W0622: Redefining built-in 'input' (redefined-builtin)
tests/sitespeed_base.py:39:56: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/sitespeed_base.py:43:21: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/sitespeed_base.py:52:8: C0415: Import outside toplevel (engines.sitespeed_result) (import-outside-toplevel)
tests/sitespeed_base.py:66:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/sitespeed_base.py:69:4: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
tests/sitespeed_base.py:93:19: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/sitespeed_base.py:97:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
tests/sitespeed_base.py:106:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:107:19: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/sitespeed_base.py:111:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:111:30: W0621: Redefining name 'sitespeed_use_docker' from outer scope (line 15) (redefined-outer-name)
tests/sitespeed_base.py:124:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/sitespeed_base.py:127:12: C0415: Import outside toplevel (subprocess) (import-outside-toplevel)
tests/sitespeed_base.py:131:15: C0121: Comparison 'error != None' should be 'error is not None' (singleton-comparison)
tests/sitespeed_base.py:141:12: C0415: Import outside toplevel (subprocess) (import-outside-toplevel)
tests/sitespeed_base.py:143:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/sitespeed_base.py:146:22: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
tests/sitespeed_base.py:168:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:175:4: W0702: No exception type(s) specified (bare-except)
tests/sitespeed_base.py:176:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/sitespeed_base.py:188:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:224:19: R1714: Consider merging these comparisons with 'in' by using 'key not in ('request', 'response', 'serverIPAddress', 'httpVersion')'. Use a set instead if elements are hashable. (consider-using-in)
tests/sitespeed_base.py:240:19: R1714: Consider merging these comparisons with 'in' by using 'key not in ('content', 'headers', 'httpVersion')'. Use a set instead if elements are hashable. (consider-using-in)
tests/sitespeed_base.py:188:0: R0912: Too many branches (21/12) (too-many-branches)
tests/sitespeed_base.py:252:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:256:0: C0116: Missing function or method docstring (missing-function-docstring)

**Comment by 7h3Rabbit** [comment]
************* Module tests.sitespeed_base
tests/sitespeed_base.py:122:0: C0301: Line too long (122/100) (line-too-long)
tests/sitespeed_base.py:43:5: W0511: TODO: CHANGE THIS IF YOU WANT TO DEBUG (fixme)
tests/sitespeed_base.py:19:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:35:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:35:0: R0914: Too many local variables (23/15) (too-many-locals)
tests/sitespeed_base.py:71:4: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
tests/sitespeed_base.py:97:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
tests/sitespeed_base.py:106:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:111:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:122:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/sitespeed_base.py:128:15: C0121: Comparison 'error != None' should be 'error is not None' (singleton-comparison)
tests/sitespeed_base.py:139:22: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
tests/sitespeed_base.py:159:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:166:4: W0702: No exception type(s) specified (bare-except)
tests/sitespeed_base.py:178:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:178:0: R0912: Too many branches (21/12) (too-many-branches)
tests/sitespeed_base.py:242:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:246:0: C0116: Missing function or method docstring (missing-function-docstring)

**Comment by 7h3Rabbit** [comment]
************* Module tests.sitespeed_base
tests/sitespeed_base.py:19:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:35:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:73:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:95:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:105:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:116:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:121:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:171:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:190:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:231:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:258:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/sitespeed_base.py:262:0: C0116: Missing function or method docstring (missing-function-docstring)
