### ISSUE TITLE
Adjust granularity for ylt test 

### ISSUE THREAD

**Issue by flowertwig-org** [Webperf-se/webperf_core#33]
**Background:**
Today we only use integer as rating for this test.
This cause many websites to get the same rating.

**We want to change it to:**
- YLT global score should be used (it already is)
- YLT global score should be interpreted as % (value are between 0-100)
- score should be calculated as follows: 5.0 * (<YLT global score> / 100)

**Benefits of this change are:**
- This will make the test more granular (Seperating sites more and making small changes count)

**Comment by flowertwig-org** [comment]
a new suggestion is done in #58

**Comment by 7h3Rabbit** [comment]
Solved in #58
