### ISSUE TITLE
PyLint for Improved Code Quality - tests/utils.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#330]
************* Module tests.utils
tests/utils.py:65:0: C0301: Line too long (122/100) (line-too-long)
tests/utils.py:131:0: C0303: Trailing whitespace (trailing-whitespace)
tests/utils.py:144:0: C0303: Trailing whitespace (trailing-whitespace)
tests/utils.py:151:0: C0303: Trailing whitespace (trailing-whitespace)
tests/utils.py:231:0: C0301: Line too long (130/100) (line-too-long)
tests/utils.py:236:0: C0301: Line too long (207/100) (line-too-long)
tests/utils.py:247:0: C0303: Trailing whitespace (trailing-whitespace)
tests/utils.py:263:0: C0303: Trailing whitespace (trailing-whitespace)
tests/utils.py:434:0: C0301: Line too long (169/100) (line-too-long)
tests/utils.py:435:0: C0301: Line too long (137/100) (line-too-long)
tests/utils.py:1:0: C0114: Missing module docstring (missing-module-docstring)
tests/utils.py:11:0: E0401: Unable to import 'requests' (import-error)
tests/utils.py:15:0: E0401: Unable to import 'bs4' (import-error)
tests/utils.py:16:0: E0401: Unable to import 'dns.resolver' (import-error)
tests/utils.py:17:0: E0401: Unable to import 'config' (import-error)
tests/utils.py:18:0: E0401: Unable to import 'IP2Location' (import-error)
tests/utils.py:21:0: E0401: Unable to import 'dns' (import-error)
tests/utils.py:22:0: E0401: Unable to import 'dns.dnssec' (import-error)
tests/utils.py:24:0: C0103: Constant name "ip2location_db" doesn't conform to UPPER_CASE naming style (invalid-name)
tests/utils.py:28:7: W0718: Catching too general exception Exception (broad-exception-caught)
tests/utils.py:36:0: C0103: Constant name "gitHubApiKey" doesn't conform to UPPER_CASE naming style (invalid-name)
tests/utils.py:41:0: W0702: No exception type(s) specified (bare-except)
tests/utils.py:43:4: C0103: Constant name "use_cache" doesn't conform to UPPER_CASE naming style (invalid-name)
tests/utils.py:48:0: W0702: No exception type(s) specified (bare-except)
tests/utils.py:50:4: C0103: Constant name "dns_server" doesn't conform to UPPER_CASE naming style (invalid-name)
tests/utils.py:55:0: W0702: No exception type(s) specified (bare-except)
tests/utils.py:56:4: C0103: Constant name "gitHubApiKey" doesn't conform to UPPER_CASE naming style (invalid-name)
tests/utils.py:58:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/utils.py:62:20: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/utils.py:64:20: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/utils.py:70:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/utils.py:78:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/utils.py:107:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/utils.py:123:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/utils.py:135:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/utils.py:139:8: W0622: Redefining built-in 'dir' (redefined-builtin)
tests/utils.py:155:10: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/utils.py:158:24: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/utils.py:173:23: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/utils.py:176:10: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/utils.py:181:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/utils.py:190:0: C0103: Function name "httpRequestGetContent" doesn't conform to snake_case naming style (invalid-name)
tests/utils.py:234:4: W0702: No exception type(s) specified (bare-except)
tests/utils.py:198:11: C0121: Comparison 'content != None' should be 'content is not None' (singleton-comparison)
tests/utils.py:202:56: C0121: Comparison 'gitHubApiKey != None' should be 'gitHubApiKey is not None' (singleton-comparison)
tests/utils.py:203:39: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/utils.py:215:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/utils.py:216:8: W0107: Unnecessary pass statement (unnecessary-pass)
tests/utils.py:218:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
tests/utils.py:222:18: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/utils.py:224:8: W0107: Unnecessary pass statement (unnecessary-pass)
tests/utils.py:226:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
tests/utils.py:231:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/utils.py:233:8: W0107: Unnecessary pass statement (unnecessary-pass)
tests/utils.py:236:12: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/utils.py:237:8: W0107: Unnecessary pass statement (unnecessary-pass)
tests/utils.py:190:0: R0911: Too many return statements (7/6) (too-many-return-statements)
tests/utils.py:240:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/utils.py:240:26: W0621: Redefining name 'cache_time_delta' from outer scope (line 40) (redefined-outer-name)
tests/utils.py:250:25: W0621: Redefining name 'cache_time_delta' from outer scope (line 40) (redefined-outer-name)
tests/utils.py:281:4: W0621: Redefining name 'ex' from outer scope (line 28) (redefined-outer-name)
tests/utils.py:281:11: W0718: Catching too general exception Exception (broad-exception-caught)
tests/utils.py:260:11: C0121: Comparison 'content != None' should be 'content is not None' (singleton-comparison)
tests/utils.py:261:22: E1101: Module 'json' has no 'loads' member (no-member)
tests/utils.py:271:23: E1101: Module 'json' has no 'dumps' member (no-member)
tests/utils.py:275:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/utils.py:276:15: R1735: Consider using '{}' instead of a call to 'dict'. (use-dict-literal)
tests/utils.py:278:15: R1735: Consider using '{}' instead of a call to 'dict'. (use-dict-literal)
tests/utils.py:280:15: R1735: Consider using '{}' instead of a call to 'dict'. (use-dict-literal)
tests/utils.py:282:15: R1735: Consider using '{}' instead of a call to 'dict'. (use-dict-literal)
tests/utils.py:281:4: W0612: Unused variable 'ex' (unused-variable)
tests/utils.py:315:4: W0702: No exception type(s) specified (bare-except)
tests/utils.py:301:12: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
tests/utils.py:309:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/utils.py:310:8: W0107: Unnecessary pass statement (unnecessary-pass)
tests/utils.py:284:0: R0911: Too many return statements (7/6) (too-many-return-statements)
tests/utils.py:284:0: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
tests/utils.py:331:4: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
tests/utils.py:345:4: W0702: No exception type(s) specified (bare-except)
tests/utils.py:350:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/utils.py:383:4: W0621: Redefining name 'ex' from outer scope (line 28) (redefined-outer-name)
tests/utils.py:352:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/utils.py:383:11: W0718: Catching too general exception Exception (broad-exception-caught)
tests/utils.py:372:19: R1734: Consider using [] instead of list() (use-list-literal)
tests/utils.py:386:11: R1734: Consider using [] instead of list() (use-list-literal)
tests/utils.py:388:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/utils.py:389:12: R1734: Consider using [] instead of list() (use-list-literal)
tests/utils.py:400:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/utils.py:433:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/utils.py:461:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/utils.py:469:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/utils.py:477:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/utils.py:481:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/utils.py:485:11: W0718: Catching too general exception Exception (broad-exception-caught)
tests/utils.py:490:11: W0718: Catching too general exception Exception (broad-exception-caught)
tests/utils.py:494:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/utils.py:504:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/utils.py:506:7: C0121: Comparison 'request_index == None' should be 'request_index is None' (singleton-comparison)
tests/utils.py:530:4: W0702: No exception type(s) specified (bare-except)
tests/utils.py:527:36: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/utils.py:529:36: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/utils.py:12:0: C0411: standard import "urllib" should be placed before third party import "requests" (wrong-import-order)
tests/utils.py:13:0: C0411: standard import "uuid" should be placed before third party import "requests" (wrong-import-order)
tests/utils.py:14:0: C0411: standard import "re" should be placed before third party import "requests" (wrong-import-order)
tests/utils.py:19:0: C0411: standard import "os" should be placed before third party imports "requests", "bs4.BeautifulSoup", "dns.resolver", "config", "IP2Location" (wrong-import-order)
tests/utils.py:20:0: C0411: standard import "urllib.parse.ParseResult" should be placed before third party imports "requests", "bs4.BeautifulSoup", "dns.resolver", "config", "IP2Location" (wrong-import-order)
tests/utils.py:21:0: C0412: Imports from package dns are not grouped (ungrouped-imports)
tests/utils.py:7:0: W0611: Unused import socket (unused-import)
tests/utils.py:15:0: W0611: Unused BeautifulSoup imported from bs4 (unused-import)

**Comment by 7h3Rabbit** [comment]
solved and closed from prev merge
