### ISSUE TITLE
PyLint for Improved Code Quality - update_software.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#332]
************* Module update_software
update_software.py:17:0: C0301: Line too long (107/100) (line-too-long)
update_software.py:47:0: C0301: Line too long (115/100) (line-too-long)
update_software.py:48:0: C0301: Line too long (126/100) (line-too-long)
update_software.py:50:0: C0301: Line too long (114/100) (line-too-long)
update_software.py:51:0: C0301: Line too long (125/100) (line-too-long)
update_software.py:53:0: C0301: Line too long (115/100) (line-too-long)
update_software.py:54:0: C0301: Line too long (126/100) (line-too-long)
update_software.py:83:0: C0301: Line too long (155/100) (line-too-long)
update_software.py:102:0: W0311: Bad indentation. Found 16 spaces, expected 12 (bad-indentation)
update_software.py:143:0: C0303: Trailing whitespace (trailing-whitespace)
update_software.py:157:0: C0301: Line too long (127/100) (line-too-long)
update_software.py:173:0: C0303: Trailing whitespace (trailing-whitespace)
update_software.py:186:0: C0303: Trailing whitespace (trailing-whitespace)
update_software.py:201:0: C0301: Line too long (221/100) (line-too-long)
update_software.py:247:0: C0301: Line too long (104/100) (line-too-long)
update_software.py:991:8: W0702: No exception type(s) specified (bare-except)
update_software.py:984:8: W0612: Unused variable 'matchNum' (unused-variable)
update_software.py:999:0: C0116: Missing function or method docstring (missing-function-docstring)
update_software.py:1006:15: R1734: Consider using [] instead of list() (use-list-literal)
update_software.py:1009:8: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
update_software.py:1016:8: W0702: No exception type(s) specified (bare-except)
update_software.py:1009:8: W0612: Unused variable 'matchNum' (unused-variable)
update_software.py:1024:0: C0116: Missing function or method docstring (missing-function-docstring)
update_software.py:1031:15: R1734: Consider using [] instead of list() (use-list-literal)
update_software.py:1034:8: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
update_software.py:1041:8: W0702: No exception type(s) specified (bare-except)
update_software.py:1034:8: W0612: Unused variable 'matchNum' (unused-variable)
update_software.py:1049:0: C0116: Missing function or method docstring (missing-function-docstring)
update_software.py:1056:15: R1734: Consider using [] instead of list() (use-list-literal)
update_software.py:1059:8: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
update_software.py:1066:8: W0702: No exception type(s) specified (bare-except)
update_software.py:1059:8: W0612: Unused variable 'matchNum' (unused-variable)
update_software.py:1075:0: W0105: String statement has no effect (pointless-string-statement)
update_software.py:4:0: C0411: standard import "datetime.datetime" should be placed before third party import "config" (wrong-import-order)
update_software.py:5:0: C0411: standard import "pathlib.Path" should be placed before third party import "config" (wrong-import-order)
update_software.py:6:0: C0411: standard import "sys" should be placed before third party import "config" (wrong-import-order)
update_software.py:7:0: C0411: standard import "json" should be placed before third party import "config" (wrong-import-order)
update_software.py:8:0: C0411: standard import "re" should be placed before third party import "config" (wrong-import-order)
update_software.py:10:0: C0411: standard import "os" should be placed before third party imports "config", "config" (wrong-import-order)
update_software.py:12:0: C0411: third party import "packaging.version" should be placed before first party import "tests.utils.*"  (wrong-import-order)
update_software.py:6:0: C0412: Imports from package sys are not grouped (ungrouped-imports)
update_software.py:11:0: W0614: Unused import(s) hashlib, shutil, socket, ssl, requests, urllib, uuid, dns, IP2Location, ip2location_db, ex, request_timeout, useragent, googlePageSpeedApiKey, gitHubApiKey, use_cache, cache_time_delta, dns_server, change_url_to_test_url, is_file_older_than, get_cache_path, get_cache_file, has_cache_file, clean_cache_files, set_cache_file, get_content_type, get_url_headers, has_redirect, get_guid, convert_to_seconds, is_sitemap, dns_lookup, dns_response_to_list, get_eu_countries, get_exception_countries, is_country_code_in_eu, is_country_code_in_exception_list, is_country_code_in_eu_or_on_exception_list, get_country_code_from_ip2location, get_best_country_code, get_friendly_url_name, timedelta, BeautifulSoup, ParseResult, urlparse and urlunparse from wildcard import of tests.utils (unused-wildcard-import)

**Comment by 7h3Rabbit** [comment]
update_software.py:13:0: C0301: Line too long (103/100) (line-too-long)
update_software.py:15:0: C0301: Line too long (107/100) (line-too-long)
update_software.py:45:0: C0301: Line too long (115/100) (line-too-long)
update_software.py:46:0: C0301: Line too long (126/100) (line-too-long)
update_software.py:48:0: C0301: Line too long (114/100) (line-too-long)
update_software.py:49:0: C0301: Line too long (125/100) (line-too-long)
update_software.py:51:0: C0301: Line too long (115/100) (line-too-long)
update_software.py:52:0: C0301: Line too long (126/100) (line-too-long)
update_software.py:81:0: C0301: Line too long (155/100) (line-too-long)
update_software.py:100:0: W0311: Bad indentation. Found 16 spaces, expected 12 (bad-indentation)
update_software.py:141:0: C0303: Trailing whitespace (trailing-whitespace)
update_software.py:155:0: C0301: Line too long (127/100) (line-too-long)
update_software.py:171:0: C0303: Trailing whitespace (trailing-whitespace)
update_software.py:184:0: C0303: Trailing whitespace (trailing-whitespace)
update_software.py:199:0: C0301: Line too long (221/100) (line-too-long)
update_software.py:245:0: C0301: Line too long (104/100) (line-too-long)
update_software.py:247:0: C0301: Line too long (179/100) (line-too-long)
update_software.py:296:0: C0303: Trailing whitespace (trailing-whitespace)
update_software.py:313:0: C0301: Line too long (143/100) (line-too-long)
update_software.py:314:0: C0301: Line too long (137/100) (line-too-long)
update_software.py:317:0: W0311: Bad indentation. Found 24 spaces, expected 20 (bad-indentation)
update_software.py:318:0: C0301: Line too long (108/100) (line-too-long)
update_software.py:318:0: W0311: Bad indentation. Found 24 spaces, expected 20 (bad-indentation)
update_software.py:319:0: W0311: Bad indentation. Found 28 spaces, expected 24 (bad-indentation)
update_software.py:329:0: C0303: Trailing whitespace (trailing-whitespace)
update_software.py:364:0: C0301: Line too long (125/100) (line-too-long)
update_software.py:413:0: C0301: Line too long (113/100) (line-too-long)
update_software.py:888:11: C0121: Comparison 'name2 != None' should be 'name2 is not None' (singleton-comparison)
update_software.py:895:12: W0702: No exception type(s) specified (bare-except)
update_software.py:902:11: C0121: Comparison 'security_label != None' should be 'security_label is not None' (singleton-comparison)
update_software.py:905:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
update_software.py:823:0: R0912: Too many branches (24/12) (too-many-branches)
update_software.py:823:0: R0915: Too many statements (66/50) (too-many-statements)
update_software.py:852:8: W0612: Unused variable 'id' (unused-variable)
update_software.py:855:8: W0612: Unused variable 'date' (unused-variable)
update_software.py:870:12: W0612: Unused variable 'matchNum' (unused-variable)
update_software.py:917:0: C0116: Missing function or method docstring (missing-function-docstring)
update_software.py:932:0: C0116: Missing function or method docstring (missing-function-docstring)
update_software.py:942:8: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
update_software.py:946:19: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
update_software.py:942:8: W0612: Unused variable 'matchNum' (unused-variable)
update_software.py:957:0: C0116: Missing function or method docstring (missing-function-docstring)
update_software.py:972:0: C0116: Missing function or method docstring (missing-function-docstring)
update_software.py:982:8: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
update_software.py:989:8: W0702: No exception type(s) specified (bare-except)
update_software.py:982:8: W0612: Unused variable 'matchNum' (unused-variable)
update_software.py:997:0: C0116: Missing function or method docstring (missing-function-docstring)
update_software.py:1007:8: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
update_software.py:1014:8: W0702: No exception type(s) specified (bare-except)
update_software.py:1007:8: W0612: Unused variable 'matchNum' (unused-variable)
update_software.py:1022:0: C0116: Missing function or method docstring (missing-function-docstring)
update_software.py:1032:8: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
update_software.py:1039:8: W0702: No exception type(s) specified (bare-except)
update_software.py:1032:8: W0612: Unused variable 'matchNum' (unused-variable)
update_software.py:1047:0: C0116: Missing function or method docstring (missing-function-docstring)
update_software.py:1057:8: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
update_software.py:1064:8: W0702: No exception type(s) specified (bare-except)
update_software.py:1057:8: W0612: Unused variable 'matchNum' (unused-variable)
update_software.py:1073:0: W0105: String statement has no effect (pointless-string-statement)
update_software.py:10:0: C0411: third party import "packaging.version" should be placed before first party import "tests.utils.*"  (wrong-import-order)
update_software.py:5:0: C0412: Imports from package sys are not grouped (ungrouped-imports)
update_software.py:9:0: W0614: Unused import(s) hashlib, shutil, ssl, urllib, uuid, requests, IP2Location, dns, gettext, get_translation, change_url_to_test_url, is_file_older_than, get_cache_path_for_rule, get_cache_path_for_folder, get_cache_path_for_file, get_cache_file, has_cache_file, clean_cache_files, set_cache_file, get_content_type, get_url_headers, get_root_url, has_redirect, get_guid, convert_to_seconds, dns_lookup, dns_response_to_list, get_eu_countries, get_exception_countries, is_country_code_in_eu, is_country_code_in_exception_list, is_country_code_in_eu_or_on_exception_list, get_country_code_from_ip2location, get_best_country_code, get_friendly_url_name, merge_dicts, merge_dict_values, merge_list_values, IP2_LOCATION_DB, ex, REQUEST_TIMEOUT, USERAGENT, USE_CACHE, CACHE_TIME_DELTA, DNS_SERVER, GITHUB_APIKEY, ParseResult, urlparse and urlunparse from wildcard import of tests.utils (unused-wildcard-import)

**Comment by cockroacher** [comment]
After discussions it has been concluded that the long term goal is to convert this (or most parts of it) to sitespeed plugin.
Because of this, it has been deemed a waste of time to continue this conversion. Time is better spent to improve our regression tests.
