### ISSUE TITLE
PyLint for Improved Code Quality - utils.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#333]
utils.py:13:0: C0301: Line too long (226/100) (line-too-long)
utils.py:14:0: C0301: Line too long (318/100) (line-too-long)
utils.py:90:0: C0301: Line too long (103/100) (line-too-long)
utils.py:97:0: C0303: Trailing whitespace (trailing-whitespace)
utils.py:100:0: C0303: Trailing whitespace (trailing-whitespace)
utils.py:103:0: C0301: Line too long (113/100) (line-too-long)
utils.py:113:0: C0301: Line too long (104/100) (line-too-long)
utils.py:114:0: C0301: Line too long (116/100) (line-too-long)
utils.py:127:0: C0303: Trailing whitespace (trailing-whitespace)
utils.py:128:0: C0303: Trailing whitespace (trailing-whitespace)
utils.py:147:0: C0301: Line too long (103/100) (line-too-long)
utils.py:153:0: C0301: Line too long (107/100) (line-too-long)
utils.py:156:0: C0301: Line too long (117/100) (line-too-long)
utils.py:165:0: C0301: Line too long (107/100) (line-too-long)
utils.py:171:0: C0301: Line too long (108/100) (line-too-long)
utils.py:177:0: C0301: Line too long (102/100) (line-too-long)
utils.py:1:0: C0114: Missing module docstring (missing-module-docstring)
utils.py:8:0: E0401: Unable to import 'config' (import-error)
utils.py:17:12: C0103: Argument name "langCode" doesn't conform to snake_case naming style (invalid-name)
utils.py:93:11: W0718: Catching too general exception Exception (broad-exception-caught)
utils.py:29:12: C0415: Import outside toplevel (tests.page_not_found.run_test) (import-outside-toplevel)
utils.py:31:12: C0415: Import outside toplevel (tests.html_validator_w3c.run_test) (import-outside-toplevel)
utils.py:33:12: C0415: Import outside toplevel (tests.css_validator_w3c.run_test) (import-outside-toplevel)
utils.py:35:12: C0415: Import outside toplevel (tests.privacy_webbkollen.run_test) (import-outside-toplevel)
utils.py:37:12: C0415: Import outside toplevel (tests.performance_lighthouse.run_test) (import-outside-toplevel)
utils.py:39:12: C0415: Import outside toplevel (tests.seo_lighthouse.run_test) (import-outside-toplevel)
utils.py:41:12: C0415: Import outside toplevel (tests.best_practice_lighthouse.run_test) (import-outside-toplevel)
utils.py:43:12: C0415: Import outside toplevel (tests.pwa_lighthouse.run_test) (import-outside-toplevel)
utils.py:45:12: C0415: Import outside toplevel (tests.standard_files.run_test) (import-outside-toplevel)
utils.py:47:12: C0415: Import outside toplevel (tests.a11y_lighthouse.run_test) (import-outside-toplevel)
utils.py:49:12: C0415: Import outside toplevel (tests.performance_sitespeed_io.run_test) (import-outside-toplevel)
utils.py:51:12: C0415: Import outside toplevel (tests.frontend_quality_yellow_lab_tools.run_test) (import-outside-toplevel)
utils.py:53:12: C0415: Import outside toplevel (tests.a11y_pa11y.run_test) (import-outside-toplevel)
utils.py:55:12: C0415: Import outside toplevel (tests.http_validator.run_test) (import-outside-toplevel)
utils.py:58:12: C0415: Import outside toplevel (tests.energy_efficiency.run_test) (import-outside-toplevel)
utils.py:60:12: C0415: Import outside toplevel (tests.tracking_validator.run_test) (import-outside-toplevel)
utils.py:62:12: C0415: Import outside toplevel (tests.email_validator.run_test) (import-outside-toplevel)
utils.py:64:12: C0415: Import outside toplevel (tests.software.run_test) (import-outside-toplevel)
utils.py:66:12: C0415: Import outside toplevel (tests.a11y_statement.run_test) (import-outside-toplevel)
utils.py:70:11: C0121: Comparison 'the_test_result != None' should be 'the_test_result is not None' (singleton-comparison)
utils.py:82:12: W0702: No exception type(s) specified (bare-except)
utils.py:81:28: E1101: Module 'json' has no 'dumps' member (no-member)
utils.py:84:16: W0107: Unnecessary pass statement (unnecessary-pass)
utils.py:99:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
utils.py:103:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:104:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:105:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:106:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:107:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:110:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:111:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:112:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:113:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:114:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:115:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:116:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:117:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:118:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:119:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:120:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:121:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:122:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:123:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:124:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
utils.py:134:8: W0107: Unnecessary pass statement (unnecessary-pass)
utils.py:136:11: R1734: Consider using [] instead of list() (use-list-literal)
utils.py:17:0: R0912: Too many branches (23/12) (too-many-branches)
utils.py:17:0: R0915: Too many statements (66/50) (too-many-statements)
utils.py:139:0: C0116: Missing function or method docstring (missing-function-docstring)
utils.py:139:17: C0103: Argument name "langCode" doesn't conform to snake_case naming style (invalid-name)
utils.py:143:12: R1734: Consider using [] instead of list() (use-list-literal)
utils.py:139:0: R0912: Too many branches (19/12) (too-many-branches)
utils.py:206:0: C0116: Missing function or method docstring (missing-function-docstring)
utils.py:206:18: C0103: Argument name "langCode" doesn't conform to snake_case naming style (invalid-name)
utils.py:207:14: R1734: Consider using [] instead of list() (use-list-literal)
utils.py:211:4: C0103: Variable name "nOfSites" doesn't conform to snake_case naming style (invalid-name)
utils.py:8:0: C0411: third party import "config" should be placed before first party import "models.Sites"  (wrong-import-order)
utils.py:9:0: C0411: standard import "gettext" should be placed before third party import "config" and first party import "models.Sites"  (wrong-import-order)
utils.py:3:0: W0611: Unused import sys (unused-import)
utils.py:4:0: W0611: Unused import getopt (unused-import)
utils.py:7:0: W0611: Unused Sites imported from models (unused-import)
utils.py:9:0: W0611: Unused import gettext (unused-import)
utils.py:1:0: R0801: Similar lines in 2 files
==test_dnssec:[283:676]
==tests.http_validator:[1409:1802]
    return None

def validate_rrsig_no_dnskey(domain, rrsig, domain_entry):
    nsname = '8.8.8.8'
    try:
        #dns.dnssec.validate(dnskey, rrsig, dnskey)
        import dns.message
        # Create a query for the 'www.example.com' domain
        query = dns.message.make_query(domain, dns.rdatatype.A, want_dnssec=True)

        # Send the query and get the response
        response = dns.query.udp(query, '8.8.8.8')

        # Get the answer section from the response
        answer_section = response.answer

        # Get the name object for 'www.example.com'
        name = dns.name.from_text(domain)

        # Get the RRset from the answer section
        rrset = response.get_rrset(answer_section, name, dns.rdataclass.IN, dns.rdatatype.DNSKEY)

        # name = dns.name.from_text(domain)
        # Assuming 'answers' is an dns.resolver.Answer object containing the DNSKEY records
        # rrset = answers.get_rrset(dnskeys, name, dns.rdataclass.IN, dns.rdatatype.DNSKEY)
        dns.dnssec.validate(rrset, rrsig, {name: rrset})
        # name = dns.name.from_text(domain)
        # dns.dnssec.validate(dnskey, rrsig, {name, dnskey})
        # dns.dnssec.validate(dnskey, rrsig)
        print("\t\t\tDNSSEC validation passed")
    except dns.dnssec.ValidationFailure as vf:
        print('\t\t\tDNSSEC VALIDATION FAIL', vf)
        domain_entry['features'].append('DNSSEC-FALIED-VALIDATION:{0}'.format(nsname))
    except Exception as ex:
        print('\t\t\tDNSSEC GENERAL FAIL', ex)
        domain_entry['features'].append('DNSSEC-FALIED-VALIDATION:{0}'.format(nsname))
    else:
        domain_entry['features'].append('DNSSEC')
==tests.software:[105:114]
    if 'nt' not in os.name:
        sitespeed_arg += ' --xvfb'

    sitespeed_arg += ' --postScript chrome-cookies.cjs --postScript chrome-versions.cjs'

    (result_folder_name, filename) = get_result(
        url, sitespeed_use_docker, sitespeed_arg, sitespeed_timeout)

    # 1. Visit page like a normal user (duplicate-code)
utils.py:1:0: R0801: Similar lines in 2 files
==tests.best_practice_lighthouse:[17:25]
==tests.css_validator_w3c:[49:57]
    language.install()
    _local = language.gettext

    print(_local('TEXT_RUNNING_TEST'))

    print(_('TEXT_TEST_START').format(
        datetime.now().strftime('%Y-%m-%d %H:%M:%S')))
 (duplicate-code)
utils.py:1:0: R0801: Similar lines in 2 files
==tests.a11y_statement:[497:504]
==tests.email_validator:[207:214]
    urls = {}

    soup = BeautifulSoup(content, 'lxml')
    links = soup.find_all("a")

    for link in links:
        if not link.find(string=re.compile( (duplicate-code)
utils.py:1:0: R0801: Similar lines in 2 files
==tests.a11y_pa11y:[21:29]
==tests.email_validator:[139:147]
    language.install()
    _local = language.gettext

    print(_local('TEXT_RUNNING_TEST'))

    print(_('TEXT_TEST_START').format(
        datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')))
 (duplicate-code)
utils.py:1:0: R0801: Similar lines in 2 files
==tests.a11y_lighthouse:[17:25]
==tests.a11y_statement:[26:34]
    language.install()
    _local = language.gettext

    print(_local('TEXT_RUNNING_TEST'))

    print(_('TEXT_TEST_START').format(
        datetime.now().strftime('%Y-%m-%d %H:%M:%S')))
 (duplicate-code)

**Comment by 7h3Rabbit** [comment]
solved and closed, thanks @cockroacher :)
