### ISSUE TITLE
Some tests are having issues with a querystring

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#348]
Lighthouse based test, at least number 10 accessibility, do not accept querystrings in the URL. For instance:
> python default.py -L sv -t 10 -r -u https://www.regionstockholm.se/?a-query-string

Also, on a Mac with Python 3.12 the documentation should perhaps suggest a backslash before questionmarks:
> zsh: no matches found: https://www.regionstockholm.se/?a-query-string

**Comment by marcusosterberg** [comment]
According to this Reddit thread the ? character is seen as a wildcard and needs to be escaped:
https://www.reddit.com/r/zsh/comments/h9mdvc/why_do_i_get_this_error_zsh_no_matches_found/

And actually, when inserting a backslash before the questionmark the test works fine:
> python default.py -t 10 -L sv -r -u https://www.regionstockholm.se/\?a-query-string

Have not tested if Webperf Core does it automatically when reading URLs from sitemaps, sites.json, etc.

**Comment by 7h3Rabbit** [comment]
@marcusosterberg 
I get a error when trying to access cache folder on second round but nothing related to your error.
Please run the test again and provide me with the latest entry of `failures.log`

**Comment by 7h3Rabbit** [comment]
@marcusosterberg  are you able to reproduce your error in branch `issue-348`?

**Comment by 7h3Rabbit** [comment]
@marcusosterberg get latest in main and see if you still get problems, if you do, please give me failures.log

**Comment by marcusosterberg** [comment]
@7h3Rabbit got latest in main and now it seem to be working flawlessly.

- [ ] Update the documentation that questionmarks need to be escaped

**Comment by 7h3Rabbit** [comment]
@marcusosterberg 
Good, then it was solved/same as:
- #353
- #352 

Closing issue
