### ISSUE TITLE
Able to use local instance of Yellow Lab Tools

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#36]
Perhaps we should have the Yellow Lab Tools URL in the config instead? Then those who'd like to have YLT locally won't be affected by the throttling that seem to be in use when testing hundreds of pages in quick succession.

**Comment by marcusosterberg** [comment]
To find out how to install your own instance of Yellow Lab Tools:
https://github.com/YellowLabTools/YellowLabTools/wiki/Install-your-private-server

**Comment by 7h3Rabbit** [comment]
Already working, closed and solved :)
