### ISSUE TITLE
Lang strings sometimes missing

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#392]
For instance, `TEXT_REVIEW_HTTPS_NO_SUPPORT` is missing for HTTP Test (21) if you're using Swedish.

**Comment by 7h3Rabbit** [comment]
@marcusosterberg if you want you have a new baseline for the Swedish http file:
https://github.com/Webperf-se/webperf_core/tree/issue-392

**Comment by 7h3Rabbit** [comment]
@marcusosterberg You will during the day get a better regression test for translations (from #393).
It appears that there are many translations only in one or two languages.

**Comment by 7h3Rabbit** [comment]
@marcusosterberg 
Strings only in "sv" are probably obsolete and could be removed.
Strings in "en" that is not in other languages are probably missing and should be added.

String like: msgid "Page weight" only in "sv"
could be an exception, they should probably be added to other languages (as they probably come from external service)
