### ISSUE TITLE
Compressed sitemaps - common on Sitevision websites...

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#40]
Why is Götene's sitemap refused as malformed even though Örebro's is accepted? Both are Gziped:
https://www.orebro.se/sitemapindex.xml
versus
https://www.gotene.se/sitemapindex.xml

**Comment by 7h3Rabbit** [comment]
It is actually pretty simple.
https://www.gotene.se/ points its sitemap to http:// and not https://
In our function where we request sitemap `httpRequestGetContent` we are specifically not allowing redirects.
If gotene would point to sitemap using https:// (it should) it would work.

**Comment by 7h3Rabbit** [comment]
I would say as design, specially as we would never want to downgrade to HTTP.
@marcusosterberg do you agree?

**Comment by 7h3Rabbit** [comment]
@marcusosterberg i'm closing this issue, let me know if there is stil something wrong with this test.
