### ISSUE TITLE
User-agent causing 403 on cloudflare proxy

### ISSUE THREAD

**Issue by linulas** [Webperf-se/webperf_core#42]
The default user-agent causes problems when making http-requests against sites that uses cloudflare proxy, which for example causes the standard_files-test to fail. 

For example, running the standar_files-test on these sites will cause a 403-error: https://www.digg.se, https://www.gp.se/, https://www.researchgate.net/, https://www.storytel.com/.

The issue seems to be related to Googlebot/2.1; +http://www.google.com/bot.html. This could easily be fixed by removing google-bot from the user-agent, not sure if it effects other purposes though.

**Comment by flowertwig-org** [comment]
Pull request merged. Thanks @linulas  :)
Issue solved.
