### ISSUE TITLE
Feature: Check for change password URL

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#48]
Complementing the 'standard files' test?

Redirect for /.well-known/change-password to a change password page?
https://web.dev/change-password-url/

**Comment by 7h3Rabbit** [comment]
I want to close this issue, my reasoning is that not most websites have a logged in state and the one that have, are/should probably use a national id or some other nationally common e-legitimation.
@marcusosterberg  Can we close this issue?
