### ISSUE TITLE
Add test for HTTP/3

### ISSUE THREAD

**Issue by flowertwig-org** [Webperf-se/webperf_core#49]

**Comment by flowertwig-org** [comment]
currently builds on https://pypi.org/project/aioquic/

**Comment by flowertwig-org** [comment]
HTTP/3 enabled domain to test against: https://cloudflare-quic.com/

**Comment by 7h3Rabbit** [comment]
Solution for this exists in branch issue-49

**Comment by 7h3Rabbit** [comment]
Solved
