### ISSUE TITLE
Language files (or removing the Swedish info on the test results)

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#5]
If not removing, at least include English as an option.

**Comment by flowertwig-org** [comment]
decided to use built in `gettext` in python for language handling.

### How to support new language 

for creating new language source file:
`python3 <your path to pygettext.py > -d webperf-core -o locales/webperf-core.pot default.py checks.py`

copy file to your locale, for Swedish it would be:
`locales/sv/LC_MESSAGES/webperf-core.pot`

rename file ending from `.pot` to `.po`

You have now support for a new language.

### How to find pygettext.py
locate your pygettext.py file:
`locate pygettext.py`
for me it was:
`/Library/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/i18n/pygettext.py`

so command for me was:
`python3 /Library/Frameworks/Python.framework/Versions/3.8/share/doc/python3.8/examples/Tools/i18n/pygettext.py -d webperf-core -o locales/webperf-core.pot default.py `


### References

- https://phrase.com/blog/posts/translate-python-gnu-gettext/
- https://docs.python.org/3/library/gettext.html

**Comment by marcusosterberg** [comment]
For us suckers on Windows and using Anaconda, pygettext.py is found here:
C:\Users\<your_user>\anaconda3\Tools\i18n

**Comment by flowertwig-org** [comment]
implemented and merged.
