### ISSUE TITLE
locale string won't work on PythonAnywhere.com

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#51]
Currently we only state _'locales'_ in our _gettext_ functions. But that do not work when uploading Webperf Core to PythonAnywhere.com, for instance. There the string needs to be in this syntax:
> /home/<user_name>/webperf_core/locales

Should we make the locale a string in the config instead so that we don't have to change it on each and every test?

**Comment by 7h3Rabbit** [comment]
@marcusosterberg I have seen you have done some work on this.
Do you still need help?
Solving this should not require any change in `config.py`.
When I have been working with regression test (specifically issue #85) it is clear that we can solve this in the code by using the `default.py` file location as a reference.

**Comment by 7h3Rabbit** [comment]
This has be solved without config.py requirement in issue #69
