### ISSUE TITLE
Make Google tests score depend on more values

### ISSUE THREAD

**Issue by 7h3Rabbit** [Webperf-se/webperf_core#57]
More test should work in a similar way to the HTTP test.
Meaning:
- More values affecting the test score (for example SpeedIndex, Web Vitals and maybe availalbe improvements)
- Score should be more granular and not just int based (and not making so that a Speedindex of 10 to big will get you 4 in rating instead of 5, it should give you like 4.9 or something as it is still really good) 
- It should be up to date with values considered good today

**Comment by flowertwig-org** [comment]
A suggestion is done in branch for #58 , look at it and see what you think

**Comment by 7h3Rabbit** [comment]
We now use Google score (1-100) and convert it to 1-5 rating.
This works because Google uses more then 1 value for their score.2
It also turned out that they use Web Vitals that we wanted to use for our new scoring.
Solved in #58
