### ISSUE TITLE
General - All Tests should be able to contribute to more then 1 category

### ISSUE THREAD

**Issue by 7h3Rabbit** [Webperf-se/webperf_core#58]
# Background
Today the tests are basically only contributing to one category at webperf.se.
It could contribute to security or standards, but not both at the same time with different impact.
Meaning a small number of test have a big inpact on categories on webperf.se today.
Even if a test get knowlage that should impact more categories, one test can only affect one category today.
This should change to improve accuracy and diffirentiate sites more by having more input values for the scores.

Making it like above suggestion will make it easier to understand what test contribute to what category and how much.
It would also take benefit from the fact that most test already today get results that affect more then one category (and in different variation) 

# What will change?
Following new categories has been added:
- Security & Integrity
- Performance
- A11y
- Standards

Every test can contribute to 0 or more categories.
The scale for every score it can contribute to is from 1 to 5.
If the test is not contributing to a category, it will return -1 for that category.
As before, every test also has it's on over all rating (test can test stuff that is not in any category, for example the Energy Efficiency test).

# Example

We will use Best Practice (Google Lighthouse) test in this comparison.

## Today
Overall test score: 4 of 5
Review:
* Webbplatsen har ändå förbättrings­potential.
* Antal problem med god praxis: 1 st

Problem:
* Includes front-end JavaScript libraries with known security vulnerabilities

## Tomorrow
- Overall test score: 4.65 of 5
- Integrity & Security: 4.0 of 5
#### Overall:
- The website can still make some improvements on best practice.
- Includes front-end JavaScript libraries with known security vulnerabilities - 4 vulnerabilities detected
#### Integrity & Security:
- Includes front-end JavaScript libraries with known security vulnerabilities - 4 vulnerabilities detected

**Comment by flowertwig-org** [comment]
TODO:
- Remove points references in comment
- verify that new rating is ok, both overall and for categories
- Fix engines
-- SQL - Make a upgrade option
-- SQL - add new columns for category rating and review
-- SQLite - Make a upgrade option
-- SQLite - add new columns for category rating and review
-- CSV - add new columns for category rating and review
-- JSON - add new columns for category rating and review
- Fix Tests
-- 123

**Comment by 7h3Rabbit** [comment]
Waiting for feedback

**Comment by flowertwig-org** [comment]
Solved and closed
