### ISSUE TITLE
Remove Internet access requirement to run local Tests

### ISSUE THREAD

**Issue by 7h3Rabbit** [Webperf-se/webperf_core#599]
### Feature/improvement

Today we require Internet access even for otherwise local tests.
This is to get latest information for that specific test.
For example CSS test requires access to: https://developer.mozilla.org/en-US/docs/Web/CSS/Reference

We should identify all places that uses `get_http_content` for this reason and
convert it to an github action and store the content in our repo.

This way it will not require Internet access but also make sure we use same references between instances.

**Comment by 7h3Rabbit** [comment]
Please note: We need to check license requirements for this.

**Comment by cockroacher** [comment]
We should add a --credits option in webperf-core that lists all:
- information sources
- all projects we depend on
- all developers who has contributed to webperf-core directly

**Comment by cockroacher** [comment]
Hi @7h3Rabbit and @marcusosterberg,
I hope you’re both doing well! I wanted to check in and see if you have any feedback regarding the current status of "credits".
Your insights would be greatly appreciated as I move forward. See below:

# Credits
Following shows projects and contributors for webperf-core and its dependencies.
Many thanks to all of you! :D

## webperf-core
License: MIT
Contributors:
- 7h3Rabbit
- cockroacher
- flowertwig-org
- dependabot[bot]
- marcusosterberg
- krompaco
- puggan
- linulas

## lighthouse
License: Apache-2.0

## pa11y
License: LGPL-3.0-only
usage: Used in Accessibility (Pa11y) Test

## sitespeed.io
License: MIT
usage: Used in the background in most cases where we need to visit website as browser

## vnu-jar
License: MIT
usage: Used in HTML and CSS Validation Test

## yellowlabtools
License: GPL-2.0
usage: Used in Quality on frontend (Yellow Lab Tools) Test

## External Information Source(s):
### CSS Validation Test Sources:
- https://developer.mozilla.org/en-US/docs/Web/CSS/Reference

### HTML Validation Test Sources:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element#obsolete_and_deprecated_elements

### Software Test Sources:
- https://api.github.com/repos/{owner}/{repo}
- https://api.github.com/repos/{owner}/{repo}/{source}/{versions_dict[version][id]}/labels
- https://api.github.com/repos/{owner}/{repo}/{source}?state=closed&per_page=100
- https://cdn.datatables.net/releases.html
- https://httpd.apache.org/security/vulnerabilities_24.html
- https://learn.microsoft.com/en-us/lifecycle/products/internet-information-services-iis
- https://nginx.org/en/security_advisories.html
- https://nuget.optimizely.com/package/?id=EPiServer.Find
- https://openssl-library.org/news/vulnerabilities/
- https://openssl-library.org/policies/releasestrat/index.html
- https://spdx.org/licenses/
- https://svn.apache.org/viewvc/httpd/httpd/tags/
- https://wordpress.org/plugins/{name}/advanced/
- https://www.cvedetails.com/vulnerability-list.php?vendor_id=26&product_id=3427&page=1
- https://www.php.net/eol.php
- https://www.php.net/releases/

**Comment by 7h3Rabbit** [comment]
@cockroacher Cool! Looks good :)

Some feedback:
- projects we depend on should probably have a URL on them
- Nice grouping urls used by test
- We should probably have write more for every url/domain? License, maintained by or something?
- we should list packages from requirements.txt (python dependencies) also
- I can't find any URL:s to digg.se (should be some from the A11y Statement test?)
- IP2Location package and file should be here (For GDPR related info)
- We should have https://github.com/github/advisory-database here, as we use it for software test (but through part of repo and not url)
- We should have https://blocklistproject.github.io/Lists/alt-version/tracking-nl.txt used in Tracking Test
- We should have https://blocklistproject.github.io/Lists/alt-version/ads-nl.txt used in Tracking Test
- We should have https://raw.githubusercontent.com/disconnectme/disconnect-tracking-protection/master/services.json used in Tracking Test
- We should have https://webbkoll.5july.net/ as we use it for WebbKollen test.

**Comment by cockroacher** [comment]
@7h3Rabbit @marcusosterberg 

Following has been fixed:
- projects we depend on should probably have a URL on them
- we should list packages from requirements.txt (python dependencies) also

Following is on todo:
- We should probably have write more for every url/domain? License, maintained by or something?
- We should have https://github.com/github/advisory-database here, as we use it for software test (but through part of repo and not url)
- We should have https://blocklistproject.github.io/Lists/alt-version/tracking-nl.txt used in Tracking Test
- We should have https://blocklistproject.github.io/Lists/alt-version/ads-nl.txt used in Tracking Test
- We should have https://raw.githubusercontent.com/disconnectme/disconnect-tracking-protection/master/services.json used in Tracking Test
- We should have https://webbkoll.5july.net/ as we use it for WebbKollen test.

**Comment by cockroacher** [comment]
Following has been fixed:
- We should have https://github.com/github/advisory-database here, as we use it for software test (but through part of repo and not url)
- We should have https://blocklistproject.github.io/Lists/alt-version/tracking-nl.txt used in Tracking Test
- We should have https://blocklistproject.github.io/Lists/alt-version/ads-nl.txt used in Tracking Test
- We should have https://raw.githubusercontent.com/disconnectme/disconnect-tracking-protection/master/services.json used in Tracking Test

**Comment by cockroacher** [comment]
# Credits
Following shows projects and contributors for webperf-core and its dependencies.
Many thanks to all of you! :D

Contributors:
- [7h3Rabbit](https://github.com/7h3Rabbit)
- [cockroacher](https://github.com/cockroacher)
- [marcusosterberg](https://github.com/marcusosterberg)
- [flowertwig-org](https://github.com/flowertwig-org)
- [dependabot[bot]](https://github.com/apps/dependabot)
- [krompaco](https://github.com/krompaco)
- [linulas](https://github.com/linulas)
- [perlan](https://github.com/perlan)
- [puggan](https://github.com/puggan)


## Projects we depend on:

### [lighthouse](https://www.npmjs.com/package/lighthouse)
Usage: Used in Google Lighthouse based Tests
License: APACHE-2.0

### [pa11y](https://www.npmjs.com/package/pa11y)
Usage: Used in Accessibility (Pa11y) Test
License: LGPL-3.0

### [sitespeed.io](https://www.npmjs.com/package/sitespeed.io)
Usage: Used in the background in most cases where we need to visit website as browser
License: MIT

### [vnu-jar](https://www.npmjs.com/package/vnu-jar)
Usage: Used in HTML and CSS Validation Test
License: MIT

### [yellowlabtools](https://www.npmjs.com/package/yellowlabtools)
Usage: Used in Quality on frontend (Yellow Lab Tools) Test
License: GPL-2.0

### [beautifulsoup4](https://pypi.org/project/beautifulsoup4/)
Usage: Used to parse HTML content

### [lxml](https://pypi.org/project/lxml/)
Usage: Used to parse XML content

### [requests](https://pypi.org/project/requests/)
Usage: Used to request content not normally requested by users, like robots.txt

### [urllib3](https://pypi.org/project/urllib3/)
Usage: Used to parse url

### [dnspython](https://pypi.org/project/dnspython/)
Usage: Used to get and parse DNS content

### [certifi](https://pypi.org/project/certifi/)

### [selenium](https://pypi.org/project/selenium/)

### [IP2Location](https://pypi.org/project/IP2Location/)
Usage: Used to get a proximate location related to IP/IP-range

### [Pillow](https://pypi.org/project/Pillow/)
Reguired by sitespeed.io

### [OpenCV-Python](https://pypi.org/project/OpenCV-Python/)
Reguired by sitespeed.io

### [Numpy](https://pypi.org/project/Numpy/)
Reguired by sitespeed.io

### [cryptography](https://pypi.org/project/cryptography/)

### [pylint](https://pypi.org/project/pylint/)
Usage: Used by our devs to ensure code quality

### [packaging](https://pypi.org/project/packaging/)
Usage: Used to understand and compare software versions

## External Information Source(s):
### Update HTML and CSS Test Sources:
- https://developer.mozilla.org/en-US/docs/Web/CSS/Reference
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element#obsolete_and_deprecated_elements

### Update Software Test Sources:
- https://github.com/github/advisory-database/tree/main/advisories/github-reviewed
- https://api.github.com/repos/{owner}/{repo}
- https://api.github.com/repos/{owner}/{repo}/contributors
- https://api.github.com/repos/{owner}/{repo}/{source}/{versions_dict[version][id]}/labels
- https://api.github.com/repos/{owner}/{repo}/{source}?state=closed&per_page=100
- https://cdn.datatables.net/releases.html
- https://httpd.apache.org/security/vulnerabilities_24.html
- https://learn.microsoft.com/en-us/lifecycle/products/internet-information-services-iis
- https://nginx.org/en/security_advisories.html
- https://nuget.optimizely.com/package/?id=EPiServer.Find
- https://openssl-library.org/news/vulnerabilities/
- https://openssl-library.org/policies/releasestrat/index.html
- https://spdx.org/licenses/
- https://svn.apache.org/viewvc/httpd/httpd/tags/
- https://wordpress.org/plugins/{name}/advanced/
- https://www.cvedetails.com/vulnerability-list.php?vendor_id=26&product_id=3427&page=1
- https://www.php.net/eol.php
- https://www.php.net/releases/

### Tracking and Privacy Test Sources:
- https://blocklistproject.github.io/Lists/alt-version/tracking-nl.txt
- https://blocklistproject.github.io/Lists/alt-version/ads-nl.txt
- https://raw.githubusercontent.com/disconnectme/disconnect-tracking-protection/master/services.json
