### ISSUE TITLE
Sv: Bygga bort MySQL

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#6]
Köra med SQLite istället eller bara dumpa SQL-frågor i en textfil.

Att föra in resultaten till webbplatsens databas kanske borde vara en mellanprogramvara?

**Comment by flowertwig-org** [comment]
Jag jobbar gärna med denna men för att inte göra fel vill jag gärna höra mer vad vi vill göra.
Jag har redan lekt lite med en version lokalt som helt saknar DB integrationen.

Jag skulle kunna göra en version som både kan returnerar resultatet som json (direkt i konsol) och (om man angett flagga för drt5) skriver json på disk. Då hade jag sedan kunna skapa separat python modul som innehåller DB integrationen och som kan jobba med json formatet som input.

Låter bra?
