### ISSUE TITLE
Add Unittest for Sitespeed based test using cached/modified browsertime.har files

### ISSUE THREAD

**Issue by 7h3Rabbit** [Webperf-se/webperf_core#600]
### Feature/improvement

We need to improve stability for our sitespeed based tests.

We need to verify that we always identify the same features for the same browsertime.har file when our logic changes.

## We can solve this by:
Creating/manufacturing/crafting a browsertime.har file for every feature we identify (and don't identify) and store them and later let our tests use them as "cached" versions and compare results. Verifying feature X is recognized when it should and verifying feature Y is not pressnt when it should not.
Easiest way is probably by using following url schema: `https://example.com/?webperf-core-test-y-feature-x-is-enabled=true`.
Where `y` is the name of test we want to test.
Where `x` is the name of feature we want to test.
Where `true` is true or false depending if the feature should be enabled or not.

## Is this not overkill?
Probably, but _if_ we want to rewrite this all as a sitespeed plugin, we need to have a good verification implemented before that rewrite.

**Comment by 7h3Rabbit** [comment]
## Har specification:
http://www.softwareishard.com/blog/har-12-spec/

## Firefox implementation:
https://github.com/firefox-devtools/bidi-har-export

## Chrome implementation:
https://github.com/sitespeedio/chrome-har

**Comment by 7h3Rabbit** [comment]
parts in this issue has been done.

**Comment by cockroacher** [comment]
#783 - CSS Lint Test - Regression test use offline version
#790 - CSS Test - Regression test use offline version
#791 - Html Test - Regression test use offline version
#794 - 404 Test - Regression test use offline version
#795 - Software Test - Regression test use offline version
#796 - Tracking Test - Regression test use offline version
#798 - HTTP Test - Regression test use offline version
