### ISSUE TITLE
Make the HTML test look for deprecated elements

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#603]
### Feature/improvement

Quite similar to what is already present in the CSS test. To have the HTML test checking for deprecated and obsolete elements and atributes.

There is a source of these at MDN Web Docs:

* https://developer.mozilla.org/en-US/docs/Web/HTML/Element#obsolete_and_deprecated_elements
* https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

**Comment by 7h3Rabbit** [comment]
I will ignore implement attributes as there was not enough of them to take the time to implement it.
