### ISSUE TITLE
Review new metrics in Google Pagespeed API

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#62]
Seems that Google is not actually versioning their Pagespeed API. Version 5 is the last version:
> "Note: The API is versioned as v5, however the Lighthouse version is independent and updated regularly."
> – https://developers.google.com/speed/docs/insights/release_notes

Juni 1 they changed to Lighthouse 8 and after that the metric 'firstCPUidle' started to fail. A panic patch has been checked in to the main branch:
https://github.com/Webperf-se/webperf_core/blob/1da73d96e3610fee8fa7c6d1e94cc500cd4cf3fd/tests/performance_lighthouse.py#L90

However, now is a good time to review the metrics present and also change the scoring scheme. Perhaps a mix of multiple important metrics such as FCP, TTI, speed index, etc.

**Comment by 7h3Rabbit** [comment]
Solved
