### ISSUE TITLE
Add Countries to GDPR compliance for Tracking Test

### ISSUE THREAD

**Issue by flowertwig-org** [Webperf-se/webperf_core#66]
Following countries should be added (on a new exception list):
- Norway
- United Kingdom

**Comment by peterk** [comment]
I may not have all the details for this issue but are all countries on [EU's list of adequacy decisions](https://ec.europa.eu/info/law/law-topic/data-protection/international-dimension-data-protection/adequacy-decisions_en) relevant to include?

**Comment by flowertwig-org** [comment]
@peterk Can you get all county codes for the contries on that list/page with the name of the country next to it?

**Comment by 7h3Rabbit** [comment]
I will fix all county code and make change now

**Comment by 7h3Rabbit** [comment]
Solved in issue #58 , will be included for version 3.0.
