### ISSUE TITLE
Create Docker Image - (NOT so super secret topic :) )

### ISSUE THREAD

**Issue by flowertwig-org** [Webperf-se/webperf_core#69]
;)

**Comment by 7h3Rabbit** [comment]
TODO:

- Make sure all tests works
- Document how to use it
- Add Docker Hub account
- Make sure docker image updates at Docker hub when code changes (:latest)  and when creating new releases in GitHub.
- Add possibility of running WebPerf-Core in silent mode
- Add possibility to output result to STDOUT

**Comment by 7h3Rabbit** [comment]
I have no need for this issue anymore so I will not do anymore work on this issue.

**Comment by 7h3Rabbit** [comment]
relates to #98
