### ISSUE TITLE
Sv: Leta sitemap i roten

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#7]
Nu kan man få felmeddelanden som:
Connection error! Unfortunately the request for URL "https://etjanster.polisen.se/robots.txt" failed.

**Comment by flowertwig-org** [comment]
@marcusosterberg can't find sitemap test in webperf-core, where to find it? :)

**Comment by flowertwig-org** [comment]
@marcusosterberg I looked at this and if I understand you correctly.
You want it to look at "https://polisen.se/robots.txt" if it fails on "https://etjanster.polisen.se/robots.txt"?

If so, this is different from how for example google handles it.
Do we want todo this anyway?

**Comment by 7h3Rabbit** [comment]
@marcusosterberg  I'm closing this issue as it works as design. robots.txt is required on every domain (including on every subdomain).
Please read https://www.cloudflare.com/learning/bots/what-is-robots.txt/ for more information
