### ISSUE TITLE
New Test - Look for "Tillgänglighetsredogörelse"

### ISSUE THREAD

**Issue by flowertwig-org** [Webperf-se/webperf_core#70]
We should look for if the site has a "Tillgänglighetsredogörelse" or not.
Use search engine to find page.
If page is found give score.
Look for listed "problems" and give less points for every occurence

**Comment by 7h3Rabbit** [comment]
Page about "Tillgänglighetsredogörelse" at https://www.digg.se/kunskap-och-stod/digital-tillganglighet/skapa-en-tillganglighetsredogorelse

### Tillgänglighetsredogörelsen ska innehålla:

- Namnet på den offentliga aktören.
- Namnet på den digitala servicen (till exempel webbplatsens, e-tjänstens eller appens namn).
- Följsamhet till lagkraven med formuleringen: helt förenlig, delvis förenlig eller inte förenlig.
- Detaljerad, fullständig och tydlig förteckning av innehåll som inte är tillgängligt och skälen till varför det inte är tillgängligt.
- Datum för bedömning av följsamhet till lagkraven.
- Datum för senaste uppdatering.
- Utvärderingsmetod (till exempel självskattning, granskning av extern part).
- Meddelandefunktion eller länk till sådan.
- Länk till DIGG:s anmälningsfunktion (https://www. digg.se/tdosanmalan).
- Redogörelse av innehåll som undantagits på grund av oskäligt betungande anpassning (12 §) med tydlig motivering.
- Redogörelse av innehåll som inte omfattas av lagkraven (9 §).

### Skapa en ny redogörelse (e-tjänst):
https://trg.digg.se/asg.php

### Exception to law (in Sweden):
https://www.digg.se/analys-och-uppfoljning/lagen-om-tillganglighet-till-digital-offentlig-service-dos-lagen/om-lagen#Detfinnsundantag

**Comment by 7h3Rabbit** [comment]
search for:
> site:huddinge.se DIGG tillgänglighet
on https://html.duckduckgo.com/html/ ?

**Comment by 7h3Rabbit** [comment]
Could we search using the websites own search? (Can demand that they have own search?)

**Comment by 7h3Rabbit** [comment]
Solved and closed
