### ISSUE TITLE
CSS-test flags newer and valid lines as problems

### ISSUE THREAD

**Issue by krompaco** [Webperf-se/webperf_core#706]
### Feature/improvement

This is a valid way of setting an empty value `--tw-pan-x: ;`.

> .. but actually writing an empty value into a custom property, like --foo: ;, is a valid (empty) value

https://www.w3.org/TR/css-variables-1/#syntax

Running CSS-test in Docker with this version info:

```
cat package.json
{
  "name": "webperf_core",
  "version": "2024.11.3",
  "description": "You probably want to read the documentation available at homepage.",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "homepage": "https://github.com/Webperf-se/webperf_core/",
  "dependencies": {
    "lighthouse": "12.2.1",
    "pa11y": "8.0.0",
    "sitespeed.io": "35.3.1",
    "vnu-jar": "23.4.11",
    "yellowlabtools": "3.0.1"
  },
  "engines": {
    "node": "20.x"
  }
}
```
Results:

````
/usr/src/runner$ python3 default.py -t 7 -u https://liramera.se -r
..
- CSS: “--tw-pan-x”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-pan-y”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-pinch-zoom”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-gradient-from-position”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-gradient-via-position”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-gradient-to-position”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-ordinal”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-slashed-zero”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-numeric-figure”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-numeric-spacing”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-numeric-fraction”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-ring-inset”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-blur”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-brightness”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-contrast”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-grayscale”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-hue-rotate”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-invert”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-saturate”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-sepia”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-drop-shadow”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-backdrop-blur”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-backdrop-brightness”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-backdrop-contrast”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-backdrop-grayscale”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-backdrop-hue-rotate”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-backdrop-invert”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-backdrop-opacity”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-backdrop-saturate”: Parse Error. (number of errors of this type: 1)
- CSS: “--tw-backdrop-sepia”: Parse Error. (number of errors of this type: 1)
````
CSS-file that get these errors: https://liramera.se/dist/styles.css?v=gh-issue

This is also discussed here: https://github.com/tailwindlabs/tailwindcss/discussions/8150

And here: https://github.com/w3c/css-validator/issues/405 - Seems to have led to this fix: https://github.com/w3c/css-validator/commit/9a54c0d93534d3a6d3415fff297d67fd5fcf91d1
Not sure in which release this would go to?

### Other newer directives and techniques that are also flagged

- https://github.com/w3c/css-validator/issues/423 - `container-type: inline-size` - https://developer.mozilla.org/en-US/docs/Web/CSS/container-type
- .. append more examples in this issue's comments

**Comment by marcuslindblom** [comment]
Another issue is the `@layer` which is baseline but not recognized by the validator.

Also discussed here: https://github.com/w3c/css-validator/issues/410

I will add an example later to this comment

**Comment by perlan** [comment]
This comment attempt to describe the css-issues KTH has with the current css-test as of 2024-10-05:

*  Public address to the site where the errors occurs:
  https://www.kth.se/

* Validator link for https://www.kth.se/:
  https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fwww.kth.se%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en

* List of errors that occures:
  Unrecognized at-rule @layer
  revert-layer is not a all value : revert-layer
  Value Error : margin revert-layer is not a margin value : revert-layer
  etc.

 * Motivation:
   @layer och revert-layer are not recognized by the validator but they are valid according to MDN

 * Link to MDN Web CSS Reference that describes the errors:
   https://developer.mozilla.org/en-US/docs/Web/CSS/@layer
   https://developer.mozilla.org/en-US/docs/Web/CSS/revert-layer

 * List any existing issues for the errors:
   https://github.com/w3c/css-validator/issues/410
   I have not found any matchingh issue for revert-layer

**Comment by 7h3Rabbit** [comment]
@marcusosterberg Looks as expected?
![image](https://github.com/user-attachments/assets/eb0faffc-46bb-47ac-a50b-f9ba4b4a5756)

**Comment by 7h3Rabbit** [comment]
@krompaco Looks as expected?
![image](https://github.com/user-attachments/assets/3182f49d-d8e1-4e49-b517-56a402b9dd54)

**Comment by 7h3Rabbit** [comment]
@perlan Looks as expected?
![image](https://github.com/user-attachments/assets/3d6964d2-2e55-4614-bff2-a8deab34b29b)

**Comment by krompaco** [comment]
> @krompaco Looks as expected?

Looks great! A quick glance and I think those remaining are actual issues. @7h3Rabbit

**Comment by perlan** [comment]
Seems like the test reports errors for css-variables that are undefined but have a fallback value. 
For example, KTHs stylesheet uses `calc(var(--kpm-bar-height,2em)` without previously declaring the variable but as I understand it should be legal and thus accepted without errors in the test. Another example of the opposite (from the same file) is `var(--bs-nav-link-font-size)` that also not previously defined but since it has no fallback value, this is correctly reported as an error. Can fallback usage be fixed by configuration or is it a limitation of style lint?

**Comment by cockroacher** [comment]
@perlan please test this in version 2024.12.5

**Comment by perlan** [comment]
@cockroacher I just tested with 2014.12.5 and it's still the same errors as before (with a lower score)

<img width="841" alt="image" src="https://github.com/user-attachments/assets/1852694c-35e1-40da-bdf9-28e00a4ec64b" />

**Comment by cockroacher** [comment]
@perlan could you find the part in the spec that says it’s allowed and drop a link to that section here?

**Comment by perlan** [comment]
@cockroacher These two MDN links are a good start:

- https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#custom_property_fallback_values, 
- https://developer.mozilla.org/en-US/docs/Web/CSS/var.

 
This is the relevant spec link https://drafts.csswg.org/css-variables/#using-variables.

**Comment by cockroacher** [comment]
@perlan If i understand the stylelint code correctly, it has support for fallbacks. Can you check your code and also see linked stylelint code to see if you agree with me?

Look specifically at:
```js
// Second node (div) indicates fallback exists in all cases
				if (secondNode && secondNode.type === 'div') return;
```

https://github.com/stylelint/stylelint/blob/main/lib%2Frules%2Fno-unknown-custom-properties%2Findex.mjs

**Comment by perlan** [comment]
@cockroacher Yes, based on that code (and corresponding test) stylelint seems to be able to handle fallback values. 

I took another look at our CSS file and noticed that there exists other rules that also contains fallback values that stylelint doesn't complain about. For example `font-size:var(--font-size, 14px)`. The only difference I can see is that the complete rule for `--kpm-bar-height` is a little more complicated like `margin-top:calc(var(--kpm-bar-height,2em) + 1px);` so one possible explanation is that stylelint is unable to correctly validate that one. Another possibility is that the rule is not valid. Looking further though, there exists other rules like `width:calc(1.5rem + 2 * var(--space-inner-icon));` that passes so maybe it's the combination of fallback values inside a function?
Any thoughts? 

Have you tried to run the stylelint tests yourself? If you already have everything setup, it should be easy to add the `margin-top:calc(var(--kpm-bar-height,2em) + 1px);` to the test file and see if it passes or fails. If not, I will try myself but I'm unsure when I can find some time to do it...

**Comment by cockroacher** [comment]
@perlan I’ve never used custom properties in CSS before. Given that you noticed a potential issue, I would really appreciate any help and troubleshooting you can provide.

**Comment by perlan** [comment]
@cockroacher Naturally, I have a interest in getting KTHs css to pass without errors in the test so I will try to help in any way I can. I was just hoping that you already had a development environment setup for stylelint (since I haven't at the moment) but I will try to see if I can run their tests as soon as I can find a little spare time.

**Comment by cockroacher** [comment]
@perlan I setup webperf_core (and all deps) up for every time I use/code for it. Best recommendations I have for a fast setup is to use windows sandbox (view one of my repos) or use the webperf_core Docker image.

**Comment by cockroacher** [comment]
@perlan closing issue as solved.
If it turns out you found a bug in new test, please create a bug here or preferably in stylelint repo.
