### ISSUE TITLE
Sv: Bugg: Oembed lurar Standardfiler

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#8]
Exempelvis här: view-source:https://spiro.se/

XML-oembed går också på "alternate"

**Comment by puggan** [comment]
Antar att du refererar till dennan delen av html-koden, som jag tror är automatgenererad av wordpress.

```html
<link
   rel="alternate"
   type="text/xml+oembed"
   href="https://spiro.se/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fspiro.se%2F&amp;format=xml"
>
```

**Comment by flowertwig-org** [comment]
this has been solved in "features" branch. closing issue as it will be included in x-mas release
