### ISSUE TITLE
SPF records are validated incorrectly in email_validator.py

### ISSUE THREAD

**Issue by peterk** [Webperf-se/webperf_core#809]
### URL

https://ubm.se

### Webperf_core version

2024.12.8

### What environment are you running?

- [ ] Using GitHub Actions
- [ ] Using Docker Image from Dock Hub
- [X] Local machine
- [ ] Other, please describe your environment in How to reproduce.

### Has anyone else reported it already?

- [X] No, there are no other issues related to this in [Issues](https://github.com/Webperf-se/webperf_core/issues).

### Expected Behavior

Validating an SPF record like

`"v=spf1 mx include:_spf.skatteverket.se -all"`

...should return a full score as it is a valid SPF record.

### Actual Behavior.

The record is flagged as invalid (string identifier TEXT_REVIEW_SPF_UNKNOWN_SECTION) in https://github.com/Webperf-se/webperf_core/blob/370fa12986c68ecb5827de6dec273ccb538538df/tests/email_validator.py#L1406

### How to reproduce

```shell
Rerun the test on ubm.se
```

**Comment by 7h3Rabbit** [comment]
@peterk Thanks a lot for great error report and PR 😄
