### ISSUE TITLE
Test Integrity & Security (Webbkoll) - Make it possible to run local

### ISSUE THREAD

**Issue by 7h3Rabbit** [Webperf-se/webperf_core#98]

**Comment by 7h3Rabbit** [comment]
OR replace it with our own test that test for same stuff

**Comment by 7h3Rabbit** [comment]
related to issue #69

**Comment by 7h3Rabbit** [comment]
When looking at this again, use below swedish instructions (from @marcusosterberg ) to run it locally:
- Tanka ner https://codeberg.org/dataskydd.net/webbkoll-backend
- kör npm install inifrån den mappen.
- Gör anrop och få JSON. 

Ge det fem minuter och säg till om du kör fast så ska jag bistå.

**Comment by marcusosterberg** [comment]
1. Tanka ner https://codeberg.org/dataskydd.net/webbkoll-backend och packa upp
2. kör `npm install` inifrån den mappen.
3. Kör `npm start` inifrån mappen
4. Anropa `http://localhost:8100/?fetch_url=https://webperf.se` och du får JSON-svar
